'\" t
.\"     Title: gshadow
.\"    Author: Nicolas Fran\(,cois <nicolas.francois@centraliens.net>
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 2014-05-09
.\"    Manual: 文件格式和转化
.\"    Source: shadow-utils 4.2
.\"  Language: Chinese Simplified
.\"
.TH "GSHADOW" "5" "2014-05-09" "shadow\-utils 4\&.2" "文件格式和转化"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "名称"
gshadow \- 影子化了的组文件
.SH "描述"
.PP
/etc/gshadow
包含影子化了的组账户信息。
.PP
如果没有维护好密码安全，此文件绝对不能让普通用户可读。
.PP
此文件的每行包含逗号分隔的如下字段：
.PP
\fB组名\fR
.RS 4
必须是系统中已经存在的有效组。
.RE
.PP
\fB加密了的密码\fR
.RS 4
请参考
\fBcrypt\fR(3)
来了解关于解析此字符串的细节信息。
.sp
If the password field contains some string that is not a valid result of
\fBcrypt\fR(3), for instance ! or *, users will not be able to use a unix password to access the group (but group members do not need the password)\&.
.sp
此密码用于不是此组成员的用户获取此组的权限。(参考
\fBnewgrp\fR(1)
)。
.sp
此字段可以为空，此时，只有组成员可以获取组权限。
.sp
以叹号开始的密码字段意味着密码被锁定。该行的剩余字符表示锁定之前的密码。
.sp
此密码取代
/etc/group
中指定的任何密码。
.RE
.PP
\fB管理员\fR
.RS 4
必须是一个逗号分隔的用户名列表。
.sp
管理员可以更改组密码和成员。
.sp
管理员也有成员一样的权限(请看下边)。
.RE
.PP
\fB成员\fR
.RS 4
必须是一个逗号分隔的用户名列表。
.sp
成员可以免密码访问组。
.sp
You should use the same list of users as in
/etc/group\&.
.RE
.SH "文件"
.PP
/etc/group
.RS 4
组账户信息。
.RE
.PP
/etc/gshadow
.RS 4
安全组账户信息。
.RE
.SH "参见"
.PP
\fBgpasswd\fR(5),
\fBgroup\fR(5),
\fBgrpck\fR(8),
\fBgrpconv\fR(8),
\fBnewgrp\fR(1)\&.
