'\" t
.\"     Title: chgpasswd
.\"    Author: Thomas K\(/loczko <kloczek@pld.org.pl>
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 05/09/2014
.\"    Manual: Команды управления системой
.\"    Source: shadow-utils 4.2
.\"  Language: Russian
.\"
.TH "chgpasswd" "8" "05/09/2014" "shadow\-utils 4\&.2" "Команды управления системой"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВАНИЕ"
chgpasswd \- обновляет пароли групп в пакетном режиме
.SH "СИНТАКСИС"
.HP \w'\fBchgpasswd\fR\ 'u
\fBchgpasswd\fR [\fIпараметры\fR]
.SH "ОПИСАНИЕ"
.PP
Программа
\fBchgpasswd\fR
читает список пар \(Foгруппа пароль\(Fc из стандартного входного потока и обновляет информацию о существующих группах\&. Каждая строка имеет вид:
.PP
\fIимя_группы\fR:\fIпароль\fR
.PP
По умолчанию, передаваемый пароль должен быть в виде обычного текста и шифруется командой
\fBchgpasswd\fR\&.
.PP
Системный алгоритм шифрования по умолчанию может быть задан в переменной
\fBENCRYPT_METHOD\fR
в файле
/etc/login\&.defs, и может быть переопределён параметрами
\fB\-e\fR,
\fB\-m\fR
или
\fB\-c\fR\&.
.PP
Данная команда предназначена для работы в крупных системных средах, где за один раз заводится несколько учётных записей\&.
.SH "ПАРАМЕТРЫ"
.PP
Параметры команды
\fBchgpasswd\fR:
.PP
\fB\-c\fR, \fB\-\-crypt\-method\fR
.RS 4
Использовать указанный метод для шифрования паролей\&.
.sp
Возможные методы: DES, MD5, NONE и SHA256 или SHA512, если эти методы поддерживается libc\&.
.RE
.PP
\fB\-e\fR, \fB\-\-encrypted\fR
.RS 4
Передаваемые пароли заданы в шифрованном виде\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Показать краткую справку и закончить работу\&.
.RE
.PP
\fB\-m\fR, \fB\-\-md5\fR
.RS 4
Использовать алгоритм шифрования MD5 вместо DES, если пароли передаются не шифрованными\&.
.RE
.PP
\fB\-R\fR, \fB\-\-root\fR\ \&\fIКАТ_CHROOT\fR
.RS 4
Выполнить изменения в каталоге
\fIКАТ_CHROOT\fR
и использовать файлы настройки из каталога
\fIКАТ_CHROOT\fR\&.
.RE
.PP
\fB\-s\fR, \fB\-\-sha\-rounds\fR
.RS 4
Использовать указанное количество раундов шифрования паролей\&.
.sp
Значение 0 означает, что система выберет количество раундов по умолчанию для выбранного метода шифрования (5000)\&.
.sp
Минимальное значение равно 1000, а максимальное значение равно 999,999,999\&.
.sp
Вы можете использовать этот параметр только при методе шифрования SHA256 или SHA512\&.
.sp
По умолчанию, количество раундов определяется переменными SHA_CRYPT_MIN_ROUNDS и SHA_CRYPT_MAX_ROUNDS из
/etc/login\&.defs\&.
.RE
.SH "ПРЕДОСТЕРЕЖЕНИЯ"
.PP
Не забудьте установить права или umask, чтобы не позволить чтение не шифрованных файлов другими пользователями\&.
.PP
Вы должны проверить, что пароль и метод шифрования соответствует политике системных паролей\&.
.SH "НАСТРОЙКА"
.PP
На работу этого инструмента влияют следующие переменные настройки из
/etc/login\&.defs:
.PP
\fBENCRYPT_METHOD\fR (строка)
.RS 4
Задаёт системный алгоритм шифрования по умолчанию для шифрования паролей (используется, если алгоритм не указан в командной строке)\&.
.sp
Возможны следующие значения:
\fIDES\fR
(по умолчанию),
\fIMD5\fR, \fISHA256\fR, \fISHA512\fR\&.
.sp
Замечание: этот параметр переопределяет переменную
\fBMD5_CRYPT_ENAB\fR\&.
.RE
.PP
\fBMAX_MEMBERS_PER_GROUP\fR (число)
.RS 4
Максимальное количество членов в записи о группе\&. При достижения максимума заводится новая запись группы (строка) в
/etc/group
(с тем же именем, паролем и тем же GID)\&.
.sp
Значение по умолчанию равно 0, означающее, что ограничения на количество членов в группе нет\&.
.sp
Данная возможность (разделение группы) позволяет ограничить длину строк в файле групп\&. Это полезно для ограничения длины строк групп NIS в 1024 символа\&.
.sp
Если вам нужно такое ограничение, укажите значение 25\&.
.sp
Замечание: разделение групп поддерживается не всеми инструментами (даже в наборе инструментов Shadow)\&. Вы не должны использовать эту переменную, если вам действительно это ненужно\&.
.RE
.PP
\fBMD5_CRYPT_ENAB\fR (логический)
.RS 4
Обозначает, что пароль должен быть зашифрован по алгоритму на основе MD5\&. Если значение равно
\fIyes\fR, то новые пароли будут зашифрованы по алгоритму на основе MD5, совместимому с используемым в новых версиях FreeBSD\&. Он поддерживает пароли неограниченной длины и имеет более длинную строку соли\&. Установите в
\fIno\fR, если вам нужно копировать шифрованные пароли в другие системы, которые не поддерживают новый алгоритм\&. По умолчанию
\fIno\fR\&.
.sp
Эта переменная переопределяется переменной
\fBENCRYPT_METHOD\fR
или любым параметром командной строки, который задаёт алгоритм шифрования\&.
.sp
Эта переменная устарела; используйте
\fBENCRYPT_METHOD\fR\&.
.RE
.PP
\fBSHA_CRYPT_MIN_ROUNDS\fR (число), \fBSHA_CRYPT_MAX_ROUNDS\fR (число)
.RS 4
Если значение
\fBENCRYPT_METHOD\fR
равно
\fISHA256\fR
или
\fISHA512\fR, эта переменная определяет количество раундов SHA, используемых алгоритмом шифрования по умолчанию (если количество раундов не задано в командной строке)\&.
.sp
Увеличение количества раундов повышает сложность подбора пароля простым перебором\&. Но заметим, что при этом для аутентификации пользователей требуется большее количество процессорных ресурсов\&.
.sp
Если не задана, то libc выбирает значение количества раундов по умолчанию (5000)\&.
.sp
Значения должны лежать в диапазоне 1000\-999999999\&.
.sp
Если задано какое\-то одно значение \(em
\fBSHA_CRYPT_MIN_ROUNDS\fR
или
\fBSHA_CRYPT_MAX_ROUNDS\fR
\(em то будет использовано это значение\&.
.sp
Если
\fBSHA_CRYPT_MIN_ROUNDS\fR
>
\fBSHA_CRYPT_MAX_ROUNDS\fR, то используется большее значение\&.
.RE
.SH "ФАЙЛЫ"
.PP
/etc/group
.RS 4
содержит информацию о группах
.RE
.PP
/etc/gshadow
.RS 4
содержит защищаемую информацию о группах
.RE
.PP
/etc/login\&.defs
.RS 4
содержит конфигурацию подсистемы теневых паролей
.RE
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBgpasswd\fR(1),
\fBgroupadd\fR(8),
\fBlogin.defs\fR(5)\&.
