'\" t
.\"     Title: chpasswd
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 05/09/2014
.\"    Manual: Команды управления системой
.\"    Source: shadow-utils 4.2
.\"  Language: Russian
.\"
.TH "chpasswd" "8" "05/09/2014" "shadow\-utils 4\&.2" "Команды управления системой"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВАНИЕ"
chpasswd \- обновляет пароли в пакетном режиме
.SH "СИНТАКСИС"
.HP \w'\fBchpasswd\fR\ 'u
\fBchpasswd\fR [\fIпараметры\fR]
.SH "ОПИСАНИЕ"
.PP
Программа
\fBchpasswd\fR
читает список пар \(Foпользователь пароль\(Fc из стандартного входного потока и обновляет информацию о существующих пользователях\&. Каждая строка имеет вид:
.PP
\fIимя_пользователя\fR:\fIпароль\fR
.PP
По умолчанию, передаваемый пароль должен быть в виде обычного текста и шифруется командой
\fBchpasswd\fR\&. Также, если есть срок действия пароля, то он будет обновлён\&.
.PP
Системный алгоритм шифрования по умолчанию может быть задан в переменной
\fBENCRYPT_METHOD\fR
или
\fBMD5_CRYPT_ENAB\fR
в файле
/etc/login\&.defs, и может быть переопределён параметрами
\fB\-e\fR,
\fB\-m\fR
или
\fB\-c\fR\&.
.PP
Команда
\fBchpasswd\fR
сначала обновляет все пароли в памяти, а затем записывает все изменения на диск, если не было никаких ошибок\&.
.PP
Данная команда предназначена для работы в крупных системных средах, где за один раз заводится несколько учётных записей\&.
.SH "ПАРАМЕТРЫ"
.PP
Параметры команды
\fBchpasswd\fR:
.PP
\fB\-c\fR, \fB\-\-crypt\-method\fR\ \&\fIМЕТОД\fR
.RS 4
Использовать указанный метод для шифрования паролей\&.
.sp
Возможные методы: DES, MD5, NONE и SHA256 или SHA512, если эти методы поддерживается libc\&.
.sp
По умолчанию (если не указан параметр\fB\-c\fR,
\fB\-m\fR
или
\fB\-e\fR), метод шифрования определяется переменной
\fBENCRYPT_METHOD\fR
или
\fBMD5_CRYPT_ENAB\fR
из файла
/etc/login\&.defs\&.
.RE
.PP
\fB\-e\fR, \fB\-\-encrypted\fR
.RS 4
Передаваемые пароли заданы в шифрованном виде\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Показать краткую справку и закончить работу\&.
.RE
.PP
\fB\-m\fR, \fB\-\-md5\fR
.RS 4
Использовать алгоритм шифрования MD5 вместо DES, если пароли передаются не шифрованными\&.
.RE
.PP
\fB\-R\fR, \fB\-\-root\fR\ \&\fIКАТ_CHROOT\fR
.RS 4
Выполнить изменения в каталоге
\fIКАТ_CHROOT\fR
и использовать файлы настройки из каталога
\fIКАТ_CHROOT\fR\&.
.RE
.PP
\fB\-s\fR, \fB\-\-sha\-rounds\fR\ \&\fIРАУНДОВ\fR
.RS 4
Использовать указанное количество раундов шифрования паролей\&.
.sp
Значение 0 означает, что система выберет количество раундов по умолчанию для выбранного метода шифрования (5000)\&.
.sp
Минимальное значение равно 1000, а максимальное значение равно 999,999,999\&.
.sp
Вы можете использовать этот параметр только при методе шифрования SHA256 или SHA512\&.
.sp
По умолчанию, количество раундов определяется переменными
\fBSHA_CRYPT_MIN_ROUNDS\fR
и
\fBSHA_CRYPT_MAX_ROUNDS\fR
в
/etc/login\&.defs\&.
.RE
.SH "ПРЕДОСТЕРЕЖЕНИЯ"
.PP
Не забудьте установить права или umask, чтобы не позволить чтение не шифрованных файлов другими пользователями\&.
.SH "НАСТРОЙКА"
.PP
На работу этого инструмента влияют следующие переменные настройки из
/etc/login\&.defs:
.PP
\fBENCRYPT_METHOD\fR (строка)
.RS 4
Задаёт системный алгоритм шифрования по умолчанию для шифрования паролей (используется, если алгоритм не указан в командной строке)\&.
.sp
Возможны следующие значения:
\fIDES\fR
(по умолчанию),
\fIMD5\fR, \fISHA256\fR, \fISHA512\fR\&.
.sp
Замечание: этот параметр переопределяет переменную
\fBMD5_CRYPT_ENAB\fR\&.
.RE
.PP
\fBMD5_CRYPT_ENAB\fR (логический)
.RS 4
Обозначает, что пароль должен быть зашифрован по алгоритму на основе MD5\&. Если значение равно
\fIyes\fR, то новые пароли будут зашифрованы по алгоритму на основе MD5, совместимому с используемым в новых версиях FreeBSD\&. Он поддерживает пароли неограниченной длины и имеет более длинную строку соли\&. Установите в
\fIno\fR, если вам нужно копировать шифрованные пароли в другие системы, которые не поддерживают новый алгоритм\&. По умолчанию
\fIno\fR\&.
.sp
Эта переменная переопределяется переменной
\fBENCRYPT_METHOD\fR
или любым параметром командной строки, который задаёт алгоритм шифрования\&.
.sp
Эта переменная устарела; используйте
\fBENCRYPT_METHOD\fR\&.
.RE
.PP
\fBSHA_CRYPT_MIN_ROUNDS\fR (число), \fBSHA_CRYPT_MAX_ROUNDS\fR (число)
.RS 4
Если значение
\fBENCRYPT_METHOD\fR
равно
\fISHA256\fR
или
\fISHA512\fR, эта переменная определяет количество раундов SHA, используемых алгоритмом шифрования по умолчанию (если количество раундов не задано в командной строке)\&.
.sp
Увеличение количества раундов повышает сложность подбора пароля простым перебором\&. Но заметим, что при этом для аутентификации пользователей требуется большее количество процессорных ресурсов\&.
.sp
Если не задана, то libc выбирает значение количества раундов по умолчанию (5000)\&.
.sp
Значения должны лежать в диапазоне 1000\-999999999\&.
.sp
Если задано какое\-то одно значение \(em
\fBSHA_CRYPT_MIN_ROUNDS\fR
или
\fBSHA_CRYPT_MAX_ROUNDS\fR
\(em то будет использовано это значение\&.
.sp
Если
\fBSHA_CRYPT_MIN_ROUNDS\fR
>
\fBSHA_CRYPT_MAX_ROUNDS\fR, то используется большее значение\&.
.RE
.SH "ФАЙЛЫ"
.PP
/etc/passwd
.RS 4
содержит информацию о пользователях
.RE
.PP
/etc/shadow
.RS 4
содержит защищаемую информацию о пользователях
.RE
.PP
/etc/login\&.defs
.RS 4
содержит конфигурацию подсистемы теневых паролей
.RE
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBpasswd\fR(1),
\fBnewusers\fR(8),
\fBlogin.defs\fR(5),\fBuseradd\fR(8)\&.
