'\" t
.\"     Title: faillog
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 05/09/2014
.\"    Manual: Команды управления системой
.\"    Source: shadow-utils 4.2
.\"  Language: Russian
.\"
.TH "faillog" "8" "05/09/2014" "shadow\-utils 4\&.2" "Команды управления системой"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВАНИЕ"
faillog \- показывает записи из файла faillog или задаёт предел неудачных попыток входа в систему
.SH "СИНТАКСИС"
.HP \w'\fBfaillog\fR\ 'u
\fBfaillog\fR [\fIпараметры\fR]
.SH "ОПИСАНИЕ"
.PP
Программа
\fBfaillog\fR
показывает содержимое журнала неудачных попыток (файл
/var/log/faillog)\&. Также она может быть использована для управления счётчиком неудачных попыток и их ограничением\&. При запуске
\fBfaillog\fR
без параметров выводятся записи faillog только тех пользователей, у которых имеется хотя бы одна неудачная попытка входа\&.
.SH "ПАРАМЕТРЫ"
.PP
Параметры команды
\fBfaillog\fR:
.PP
\fB\-a\fR, \fB\-\-all\fR
.RS 4
Показать записи faillog для всех пользователей из базы данных
faillog\&.
.sp
Список пользователей можно ограничить с помощью параметра
\fB\-u\fR\&.
.sp
В режиме вывода это ограничивает вывод списком существующих пользователей, но при этом для них выводятся даже пустые записи faillog\&.
.sp
Параметры
\fB\-l\fR,
\fB\-m\fR,
\fB\-r\fR,
\fB\-t\fR
изменяют записи пользователей, даже если они не существует в системе\&. Это полезно для сброса записей пользователей, которые были удалены или для предварительной установки политики для диапазона пользователей\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Показать краткую справку и закончить работу\&.
.RE
.PP
\fB\-l\fR, \fB\-\-lock\-secs\fR\ \&\fIСЕКУНД\fR
.RS 4
Блокировать учётную запись на указанное количество
\fIСЕКУНД\fR
после неудачной попытки входа\&.
.sp
Для этого параметра требуется право на запись в
/var/log/faillog\&.
.RE
.PP
\fB\-m\fR, \fB\-\-maximum\fR\ \&\fIМАКС_ЧИСЛО\fR
.RS 4
Установить максимальное количество неудачных попыток входа перед блокировкой учётной записи равным
\fIМАКС_ЧИСЛО\fR\&.
.sp
Если значение
\fIМАКС_ЧИСЛО\fR
равно 0, то количество неудачных попыток входа не ограничивается\&.
.sp
Для предотвращения атаки отказа в обслуживании максимальное количество неудачных попыток входа у
\fIroot\fR
всегда должно быть равно 0\&.
.sp
Для этого параметра требуется право на запись в
/var/log/faillog\&.
.RE
.PP
\fB\-r\fR, \fB\-\-reset\fR
.RS 4
Сбросить счётчик неудачных попыток входа\&.
.sp
Для этого параметра требуется право на запись в
/var/log/faillog\&.
.RE
.PP
\fB\-R\fR, \fB\-\-root\fR\ \&\fIКАТ_CHROOT\fR
.RS 4
Выполнить изменения в каталоге
\fIКАТ_CHROOT\fR
и использовать файлы настройки из каталога
\fIКАТ_CHROOT\fR\&.
.RE
.PP
\fB\-t\fR, \fB\-\-time\fR\ \&\fIДНЕЙ\fR
.RS 4
Показать записи faillog новее чем
\fIДНЕЙ\fR\&.
.RE
.PP
\fB\-u\fR, \fB\-\-user\fR\ \&\fIУЧЁТНАЯ ЗАПИСЬ\fR|\fIДИАПАЗОН\fR
.RS 4
Показать запись faillog или изменить счётчики неудачных попыток и ограничения (если задан параметр
\fB\-l\fR,
\fB\-m\fR
или
\fB\-r\fR) только для указанных учётных записей\&.
.sp
Пользователя можно указать по отдельному имени, числовому идентификатору или в виде
\fIДИАПАЗОНА\fR
пользователей\&. Такой
\fIДИАПАЗОН\fR
можно задавать в виде максимального и минимального значений(\fIUID_МИН\-UID_МАКС\fR), максимального (\fI\-UID_МАКС\fR) или минимального (\fIUID_МИН\-\fR) значения\&.
.RE
.PP
Если параметры
\fB\-l\fR,
\fB\-m\fR
или
\fB\-r\fR
не заданы, то
\fBfaillog\fR
показывает записи faillog указанных пользователей\&.
.SH "ПРЕДОСТЕРЕЖЕНИЯ"
.PP
Программа
\fBfaillog\fR
выводит только записи о пользователях, последняя попытка входа которых была неудачной\&. Чтобы увидеть запись о пользователе, последняя попытка входа которого была удачной, вы должны специально указать имя пользователя с помощью параметра
\fB\-u\fR, или для показа всех пользователей указать параметр
\fB\-a\fR\&.
.SH "ФАЙЛЫ"
.PP
/var/log/faillog
.RS 4
журнал неудавшихся попыток входа в систему
.RE
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBlogin\fR(1),
\fBfaillog\fR(5)\&.
