'\" t
.\"     Title: groupdel
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 05/09/2014
.\"    Manual: Команды управления системой
.\"    Source: shadow-utils 4.2
.\"  Language: Russian
.\"
.TH "groupdel" "8" "05/09/2014" "shadow\-utils 4\&.2" "Команды управления системой"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВАНИЕ"
groupdel \- удаляет группу
.SH "СИНТАКСИС"
.HP \w'\fBgroupdel\fR\ 'u
\fBgroupdel\fR [\fIпараметры\fR] \fIГРУППА\fR
.SH "ОПИСАНИЕ"
.PP
Программа
\fBgroupdel\fR
изменяет системные файлы учётных записей, удаляя все записи, относящиеся к
\fIГРУППЕ\fR\&. Группа с таким именем должна существовать\&.
.SH "ПАРАМЕТРЫ"
.PP
Параметры команды
\fBgroupdel\fR:
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Показать краткую справку и закончить работу\&.
.RE
.PP
\fB\-R\fR, \fB\-\-root\fR\ \&\fIКАТ_CHROOT\fR
.RS 4
Выполнить изменения в каталоге
\fIКАТ_CHROOT\fR
и использовать файлы настройки из каталога
\fIКАТ_CHROOT\fR\&.
.RE
.SH "ПРЕДОСТЕРЕЖЕНИЯ"
.PP
Вы не можете удалить группу, если она является первичной для существующего пользователя\&. Вы должны удалить пользователя перед тем как удалять группу\&.
.PP
Вы должны вручную проверить все файловые системы, чтобы убедиться, что не осталось файлов, принадлежащих удалённой группе\&.
.SH "НАСТРОЙКА"
.PP
На работу этого инструмента влияют следующие переменные настройки из
/etc/login\&.defs:
.PP
\fBMAX_MEMBERS_PER_GROUP\fR (число)
.RS 4
Максимальное количество членов в записи о группе\&. При достижения максимума заводится новая запись группы (строка) в
/etc/group
(с тем же именем, паролем и тем же GID)\&.
.sp
Значение по умолчанию равно 0, означающее, что ограничения на количество членов в группе нет\&.
.sp
Данная возможность (разделение группы) позволяет ограничить длину строк в файле групп\&. Это полезно для ограничения длины строк групп NIS в 1024 символа\&.
.sp
Если вам нужно такое ограничение, укажите значение 25\&.
.sp
Замечание: разделение групп поддерживается не всеми инструментами (даже в наборе инструментов Shadow)\&. Вы не должны использовать эту переменную, если вам действительно это ненужно\&.
.RE
.SH "ФАЙЛЫ"
.PP
/etc/group
.RS 4
содержит информацию о группах
.RE
.PP
/etc/gshadow
.RS 4
содержит защищаемую информацию о группах
.RE
.SH "ВОЗВРАЩАЕМЫЕ ЗНАЧЕНИЯ"
.PP
Программа
\fBgroupdel\fR
завершая работу, возвращает следующие значения:
.PP
\fI0\fR
.RS 4
успешное выполнение
.RE
.PP
\fI2\fR
.RS 4
ошибка в параметрах команды
.RE
.PP
\fI6\fR
.RS 4
указанная группа не существует
.RE
.PP
\fI8\fR
.RS 4
не удалось удалить первичную пользовательскую группу
.RE
.PP
\fI10\fR
.RS 4
не удалось изменить файл групп
.RE
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBchfn\fR(1),
\fBchsh\fR(1),
\fBpasswd\fR(1),
\fBgpasswd\fR(8),
\fBgroupadd\fR(8),
\fBgroupmod\fR(8),
\fBuseradd\fR(8),
\fBuserdel\fR(8),
\fBusermod\fR(8)\&.
