'\" t
.\"     Title: groupadd
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 05/09/2014
.\"    Manual: Команды управления системой
.\"    Source: shadow-utils 4.2
.\"  Language: Russian
.\"
.TH "groupadd" "8" "05/09/2014" "shadow\-utils 4\&.2" "Команды управления системой"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВАНИЕ"
groupadd \- создаёт новую группу
.SH "СИНТАКСИС"
.HP \w'\fBgroupadd\fR\ 'u
\fBgroupadd\fR [\fIпараметры\fR] \fIгруппа\fR
.SH "ОПИСАНИЕ"
.PP
Программа
\fBgroupadd\fR
создаёт новую группу согласно указанным значениям командной строки и системным значениям по умолчанию\&. Новая группа будет добавлена в системные файлы\&.
.SH "ПАРАМЕТРЫ"
.PP
Параметры команды
\fBgroupadd\fR:
.PP
\fB\-f\fR, \fB\-\-force\fR
.RS 4
Завершить работу и вернуть состояние успешного выполнения, если группа уже существует\&. Если используется вместе с параметром
\fB\-g\fR
и указанный GID уже существует, то выбирается другой (уникальный) GID (то есть параметр
\fB\-g\fR
игнорируется)\&.
.RE
.PP
\fB\-g\fR, \fB\-\-gid\fR\ \&\fIGID\fR
.RS 4
Числовое значение идентификатора группы (ID)\&. Оно должно быть уникальным, если не используется параметр
\fB\-o\fR\&. Значение должно быть неотрицательным\&. По умолчанию используется наименьшее значение ID большее или равное
\fBGID_MIN\fR
и большее чем у остальных групп\&.
.sp
Смотрите также описание
\fB\-r\fR
и
\fBGID_MAX\fR\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Показать краткую справку и закончить работу\&.
.RE
.PP
\fB\-K\fR, \fB\-\-key\fR\ \&\fIКЛЮЧ\fR=\fIЗНАЧЕНИЕ\fR
.RS 4
Изменить значения по умолчанию (GID_MIN, GID_MAX и другие), которые хранятся в файле
/etc/login\&.defs\&. Можно указать несколько параметров
\fB\-K\fR\&.
.sp
Пример:
\fB\-K\fR\ \&\fIGID_MIN\fR=\fI100\fR\ \&\fB\-K\fR\ \&\fIGID_MAX\fR=\fI499\fR
.sp
Замечание: запись вида
\fB\-K\fR\ \&\fIGID_MIN\fR=\fI10\fR,\fIGID_MAX\fR=\fI499\fR
пока не работает\&.
.RE
.PP
\fB\-o\fR, \fB\-\-non\-unique\fR
.RS 4
Разрешить добавление группы с не уникальным GID\&.
.RE
.PP
\fB\-p\fR, \fB\-\-password\fR\ \&\fIПАРОЛЬ\fR
.RS 4
Шифрованное значение пароля, которое возвращает функция
\fBcrypt\fR(3)\&. По умолчанию пароль отключён\&.
.sp
\fBЗамечание:\fR
Этот параметр использовать не рекомендуется, так как пароль (или не шифрованный пароль) будет видим другими пользователям в списке процессов\&.
.sp
Вы должны проверить, что пароль соответствует политике системных паролей\&.
.RE
.PP
\fB\-r\fR, \fB\-\-system\fR
.RS 4
Создать системную группу\&.
.sp
Числовые идентификаторы для системных групп выбираются из диапазона
\fBSYS_GID_MIN\fR\-\fBSYS_GID_MAX\fR, определённых в
login\&.defs, а не из
\fBGID_MIN\fR\-\fBGID_MAX\fR\&.
.RE
.PP
\fB\-R\fR, \fB\-\-root\fR\ \&\fIКАТ_CHROOT\fR
.RS 4
Выполнить изменения в каталоге
\fIКАТ_CHROOT\fR
и использовать файлы настройки из каталога
\fIКАТ_CHROOT\fR\&.
.RE
.SH "НАСТРОЙКА"
.PP
На работу этого инструмента влияют следующие переменные настройки из
/etc/login\&.defs:
.PP
\fBGID_MAX\fR (число), \fBGID_MIN\fR (число)
.RS 4
Диапазон идентификаторов групп, используемый в программах
\fBuseradd\fR,
\fBgroupadd\fR
или
\fBnewusers\fR
для создания обычных групп\&.
.sp
Значение по умолчанию для
\fBGID_MIN\fR
(соотв\&.
\fBGID_MAX\fR) равно 1000 (соотв\&. 60000)\&.
.RE
.PP
\fBMAX_MEMBERS_PER_GROUP\fR (число)
.RS 4
Максимальное количество членов в записи о группе\&. При достижения максимума заводится новая запись группы (строка) в
/etc/group
(с тем же именем, паролем и тем же GID)\&.
.sp
Значение по умолчанию равно 0, означающее, что ограничения на количество членов в группе нет\&.
.sp
Данная возможность (разделение группы) позволяет ограничить длину строк в файле групп\&. Это полезно для ограничения длины строк групп NIS в 1024 символа\&.
.sp
Если вам нужно такое ограничение, укажите значение 25\&.
.sp
Замечание: разделение групп поддерживается не всеми инструментами (даже в наборе инструментов Shadow)\&. Вы не должны использовать эту переменную, если вам действительно это ненужно\&.
.RE
.PP
\fBSYS_GID_MAX\fR (число), \fBSYS_GID_MIN\fR (число)
.RS 4
Диапазон идентификаторов групп, используемый в программах
\fBuseradd\fR,
\fBgroupadd\fR
или
\fBnewusers\fR
для создания системных групп\&.
.sp
Значение по умолчанию для
\fBSYS_GID_MIN\fR
(соотв\&.\fBSYS_GID_MAX\fR) равно 101 (соотв\&.
\fBGID_MIN\fR\-1)\&.
.RE
.SH "ФАЙЛЫ"
.PP
/etc/group
.RS 4
содержит информацию о группах
.RE
.PP
/etc/gshadow
.RS 4
содержит защищаемую информацию о группах
.RE
.PP
/etc/login\&.defs
.RS 4
содержит конфигурацию подсистемы теневых паролей
.RE
.SH "ПРЕДОСТЕРЕЖЕНИЯ"
.PP
Имена групп должны начинаться со строчной буквы или символа подчёркивания, и должны состоять только из строчных букв, цифр, символов подчёркивания и минус\&. Они могут заканчиваться знаком доллара\&. Это можно описать регулярным выражением: [a\-z_][a\-z0\-9_\-]*[$]?
.PP
Имена групп могут быть длиной не более 16 знаков\&.
.PP
Нельзя добавить группу NIS или LDAP\&. Это необходимо делать на соответствующем сервере\&.
.PP
Если имя группы уже существует во внешней базе данных групп, например в NIS или LDAP, то
\fBgroupadd\fR
не станет создавать группу\&.
.SH "ВОЗВРАЩАЕМЫЕ ЗНАЧЕНИЯ"
.PP
Программа
\fBgroupadd\fR
завершая работу, возвращает следующие значения:
.PP
\fI0\fR
.RS 4
успешное выполнение
.RE
.PP
\fI2\fR
.RS 4
ошибка в параметрах команды
.RE
.PP
\fI3\fR
.RS 4
недопустимое значение параметра
.RE
.PP
\fI4\fR
.RS 4
не уникальный GID (если не задан параметр
\fB\-o\fR)
.RE
.PP
\fI9\fR
.RS 4
не уникальное имя группы
.RE
.PP
\fI10\fR
.RS 4
не удалось изменить файл групп
.RE
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBchfn\fR(1),
\fBchsh\fR(1),
\fBpasswd\fR(1),
\fBgpasswd\fR(8),
\fBgroupdel\fR(8),
\fBgroupmod\fR(8),
\fBlogin.defs\fR(5),
\fBuseradd\fR(8),
\fBuserdel\fR(8),
\fBusermod\fR(8)\&.
