'\" t
.\"     Title: groupmems
.\"    Author: George Kraft, IV
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 05/09/2014
.\"    Manual: Команды управления системой
.\"    Source: shadow-utils 4.2
.\"  Language: Russian
.\"
.TH "groupmems" "8" "05/09/2014" "shadow\-utils 4\&.2" "Команды управления системой"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВАНИЕ"
groupmems \- управляет членами первичной группы пользователя
.SH "СИНТАКСИС"
.HP \w'\fBgroupmems\fR\ 'u
\fBgroupmems\fR \-a\ \fIимя_пользователя\fR | \-d\ \fIимя_пользователя\fR | [\-g\ \fIимя_группы\fR] | \-l | \-p 
.SH "ОПИСАНИЕ"
.PP
Программа
\fBgroupmems\fR
позволяет пользователю управлять списком членов своей группы не имея привилегий суперпользователя\&. Программа
\fBgroupmems\fR
работает в системах, где в качестве первичной группы пользователя является группа с именем совпадающим с именем пользователя (то есть, guest / guest)\&.
.PP
Только суперпользователь как администратор может использовать
\fBgroupmems\fR, чтобы изменить список членов не своей группы\&.
.SH "ПАРАМЕТРЫ"
.PP
Параметры команды
\fBgroupmems\fR:
.PP
\fB\-a\fR, \fB\-\-add\fR\ \&\fIимя_пользователя\fR
.RS 4
Добавить нового пользователя в группу\&.
.sp
Если существует файл
/etc/gshadow
и записи о группе нет в файле
/etc/gshadow, то будет создана новая запись\&.
.RE
.PP
\fB\-d\fR, \fB\-\-delete\fR\ \&\fIимя_пользователя\fR
.RS 4
Удалить пользователя из группы\&.
.sp
Если существует файл
/etc/gshadow, то пользователь будет удалён из списка членов и администраторов группы\&.
.sp
Если существует файл
/etc/gshadow
и записи о группе нет в файле
/etc/gshadow, то будет создана новая запись\&.
.RE
.PP
\fB\-g\fR, \fB\-\-group\fR\ \&\fIимя_группы\fR
.RS 4
Суперпользователь может указать группу, в которой нужно изменить список членов\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Показать краткую справку и закончить работу\&.
.RE
.PP
\fB\-l\fR, \fB\-\-list\fR
.RS 4
Показать список членов группы\&.
.RE
.PP
\fB\-p\fR, \fB\-\-purge\fR
.RS 4
Вычистить всех пользователей из списка членов группы\&.
.sp
Если существует файл
/etc/gshadow
и записи о группе нет в файле
/etc/gshadow, то будет создана новая запись\&.
.RE
.PP
\fB\-R\fR, \fB\-\-root\fR\ \&\fIКАТ_CHROOT\fR
.RS 4
Выполнить изменения в каталоге
\fIКАТ_CHROOT\fR
и использовать файлы настройки из каталога
\fIКАТ_CHROOT\fR\&.
.RE
.SH "НАСТРОЙКА"
.PP
Исполняемый файл программы
\fBgroupmems\fR
должен иметь права
2770, принадлежать пользователю
\fIroot\fR
и группе
\fIgroups\fR\&. Системный администратор может добавлять пользователей в группу
\fIgroups\fR, разрешая или запрещая им запускать программу
\fBgroupmems\fR
для управления членством в своей группе\&.
.sp
.if n \{\
.RS 4
.\}
.nf
	$ groupadd \-r groups
	$ chmod 2770 groupmems
	$ chown root\&.groups groupmems
	$ groupmems \-g groups \-a gk4
    
.fi
.if n \{\
.RE
.\}
.SH "НАСТРОЙКА"
.PP
На работу этого инструмента влияют следующие переменные настройки из
/etc/login\&.defs:
.PP
\fBMAX_MEMBERS_PER_GROUP\fR (число)
.RS 4
Максимальное количество членов в записи о группе\&. При достижения максимума заводится новая запись группы (строка) в
/etc/group
(с тем же именем, паролем и тем же GID)\&.
.sp
Значение по умолчанию равно 0, означающее, что ограничения на количество членов в группе нет\&.
.sp
Данная возможность (разделение группы) позволяет ограничить длину строк в файле групп\&. Это полезно для ограничения длины строк групп NIS в 1024 символа\&.
.sp
Если вам нужно такое ограничение, укажите значение 25\&.
.sp
Замечание: разделение групп поддерживается не всеми инструментами (даже в наборе инструментов Shadow)\&. Вы не должны использовать эту переменную, если вам действительно это ненужно\&.
.RE
.SH "ФАЙЛЫ"
.PP
/etc/group
.RS 4
содержит информацию о группах
.RE
.PP
/etc/gshadow
.RS 4
содержит защищаемую информацию о группах
.RE
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBchfn\fR(1),
\fBchsh\fR(1),
\fBpasswd\fR(1),
\fBgroupadd\fR(8),
\fBgroupdel\fR(8),
\fBuseradd\fR(8),
\fBuserdel\fR(8),
\fBusermod\fR(8)\&.
