'\" t
.\"     Title: groupmod
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 05/09/2014
.\"    Manual: Команды управления системой
.\"    Source: shadow-utils 4.2
.\"  Language: Russian
.\"
.TH "groupmod" "8" "05/09/2014" "shadow\-utils 4\&.2" "Команды управления системой"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВАНИЕ"
groupmod \- изменяет определение группы в системе
.SH "СИНТАКСИС"
.HP \w'\fBgroupmod\fR\ 'u
\fBgroupmod\fR [\fIпараметры\fR] \fIГРУППА\fR
.SH "ОПИСАНИЕ"
.PP
Команда
\fBgroupmod\fR
изменяет определение указанной
\fIГРУППЫ\fR, изменяя соответствующую запись в базе данных групп\&.
.SH "ПАРАМЕТРЫ"
.PP
Параметры команды
\fBgroupmod\fR:
.PP
\fB\-g\fR, \fB\-\-gid\fR\ \&\fIGID\fR
.RS 4
Имя группы будет изменено с
\fIГРУППА\fR
на
\fIGID\fR\&.
.sp
Десятичное значение
\fIGID\fR
должно быть неотрицательным\&. Это значение должно быть уникальным, если не указан параметр
\fB\-o\fR\&.
.sp
У пользователей, которых эта группа является первичной, будет выполнено соответствующее обновление\&.
.sp
У всех файлов, которые имеют ID старой группы и должны продолжать принадлежать
\fIGROUP\fR, нужно изменить их ID вручную\&.
.sp
Никаких проверок по
\fBGID_MIN\fR,
\fBGID_MAX\fR,
\fBSYS_GID_MIN\fR
или
\fBSYS_GID_MAX\fR
из
/etc/login\&.defs
не производится\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Показать краткую справку и закончить работу\&.
.RE
.PP
\fB\-n\fR, \fB\-\-new\-name\fR\ \&\fIНОВАЯ_ГРУППА\fR
.RS 4
Имя группы будет изменено с
\fIГРУППА\fR
на
\fIНОВАЯ_ГРУППА\fR\&.
.RE
.PP
\fB\-o\fR, \fB\-\-non\-unique\fR
.RS 4
При использовании с параметром
\fB\-g\fR
разрешается изменять
\fIGID\fR
группы не уникальным значением\&.
.RE
.PP
\fB\-p\fR, \fB\-\-password\fR\ \&\fIПАРОЛЬ\fR
.RS 4
Шифрованное значение пароля, которое возвращает функция
\fBcrypt\fR(3)\&.
.sp
\fBЗамечание:\fR
Этот параметр использовать не рекомендуется, так как пароль (или не шифрованный пароль) будет видим другими пользователям в списке процессов\&.
.sp
Вы должны проверить, что пароль соответствует политике системных паролей\&.
.RE
.PP
\fB\-R\fR, \fB\-\-root\fR\ \&\fIКАТ_CHROOT\fR
.RS 4
Выполнить изменения в каталоге
\fIКАТ_CHROOT\fR
и использовать файлы настройки из каталога
\fIКАТ_CHROOT\fR\&.
.RE
.SH "НАСТРОЙКА"
.PP
На работу этого инструмента влияют следующие переменные настройки из
/etc/login\&.defs:
.PP
\fBMAX_MEMBERS_PER_GROUP\fR (число)
.RS 4
Максимальное количество членов в записи о группе\&. При достижения максимума заводится новая запись группы (строка) в
/etc/group
(с тем же именем, паролем и тем же GID)\&.
.sp
Значение по умолчанию равно 0, означающее, что ограничения на количество членов в группе нет\&.
.sp
Данная возможность (разделение группы) позволяет ограничить длину строк в файле групп\&. Это полезно для ограничения длины строк групп NIS в 1024 символа\&.
.sp
Если вам нужно такое ограничение, укажите значение 25\&.
.sp
Замечание: разделение групп поддерживается не всеми инструментами (даже в наборе инструментов Shadow)\&. Вы не должны использовать эту переменную, если вам действительно это ненужно\&.
.RE
.SH "ФАЙЛЫ"
.PP
/etc/group
.RS 4
содержит информацию о группах
.RE
.PP
/etc/gshadow
.RS 4
содержит защищаемую информацию о группах
.RE
.PP
/etc/login\&.defs
.RS 4
содержит конфигурацию подсистемы теневых паролей
.RE
.PP
/etc/passwd
.RS 4
содержит информацию о пользователях
.RE
.SH "ВОЗВРАЩАЕМЫЕ ЗНАЧЕНИЯ"
.PP
Команда
\fBgroupmod\fR
завершая работу, возвращает следующие значения:
.PP
\fI0\fR
.RS 4
успешное выполнение
.RE
.PP
\fI2\fR
.RS 4
ошибка в параметрах команды
.RE
.PP
\fI3\fR
.RS 4
недопустимое значение параметра
.RE
.PP
\fI4\fR
.RS 4
указанная группа не существует
.RE
.PP
\fI6\fR
.RS 4
указанная группа не существует
.RE
.PP
\fI9\fR
.RS 4
такое имя группы уже используется
.RE
.PP
\fI10\fR
.RS 4
не удалось изменить файл групп
.RE
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBchfn\fR(1),
\fBchsh\fR(1),
\fBpasswd\fR(1),
\fBgpasswd\fR(8),
\fBgroupadd\fR(8),
\fBgroupdel\fR(8),
\fBlogin.defs\fR(5),
\fBuseradd\fR(8),
\fBuserdel\fR(8),
\fBusermod\fR(8)\&.
