'\" t
.\"     Title: grpck
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 05/09/2014
.\"    Manual: Команды управления системой
.\"    Source: shadow-utils 4.2
.\"  Language: Russian
.\"
.TH "grpck" "8" "05/09/2014" "shadow\-utils 4\&.2" "Команды управления системой"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВАНИЕ"
grpck \- проверяет корректность файлов групп
.SH "СИНТАКСИС"
.HP \w'\fBgrpck\fR\ 'u
\fBgrpck\fR [параметры] [\fIгруппа\fR\ [\ \fIshadow\fR\ ]]
.SH "ОПИСАНИЕ"
.PP
Программа
\fBgrpck\fR
проверяет целостность информации о группах в системе\&. Проверяются формат и правильность данных всех записей в файлах
/etc/group
и
/etc/gshadow\&. В случае обнаружения ошибок пользователю предлагается подтвердить удаление записей, имеющих неверный формат или восстановление которых невозможно\&.
.PP
Выполняются следующие проверки:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
правильное количество полей
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
уникальность и корректность имени группы
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
корректность идентификатора группы
(только для /etc/group)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
корректность списка членов
и администраторов
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
соответствие записи в файле
/etc/gshadow
(и
/etc/group
при проверках
gshadow)
.RE
.PP
Ошибки в количестве полей и уникальности имён групп невосстановимы\&. Если запись содержит неверное число полей, пользователя попросят подтвердить удаление всей строки\&. Если пользователь ответит отрицательно, дальнейшая проверка выполняться не будет\&. При ошибке повторения имени группы также возникает запрос на удаление, но в случае отказа проверка будет продолжена\&. Обо всех остальных ошибках выводится предупреждение и пользователю предлагается запустить команду
\fBgroupmod\fR, чтобы исправить ошибку\&.
.PP
Команды, которые работают с файлом
/etc/groupи /etc/gshadow, не способны изменить повреждённые или дублирующиеся записи\&. В этом случае нужно использовать
\fBgrpck\fR
для удаления испорченной записи\&.
.SH "ПАРАМЕТРЫ"
.PP
Параметры
\fB\-r\fR,
\fB\-s\fR
не могут использоваться одновременно\&.
.PP
Параметры команды
\fBgrpck\fR:
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Показать краткую справку и закончить работу\&.
.RE
.PP
\fB\-r\fR, \fB\-\-read\-only\fR
.RS 4
Запускать команду
\fBgrpck\fR
в режиме только для чтения\&. При этом на все вопросы об изменениях устанавливается ответ
\fIнет\fR
и участие пользователя не требуется\&.
.RE
.PP
\fB\-R\fR, \fB\-\-root\fR\ \&\fIКАТ_CHROOT\fR
.RS 4
Выполнить изменения в каталоге
\fIКАТ_CHROOT\fR
и использовать файлы настройки из каталога
\fIКАТ_CHROOT\fR\&.
.RE
.PP
\fB\-s\fR, \fB\-\-sort\fR
.RS 4
Отсортировать все записи в файле
/etc/groupи /etc/gshadow
по числовому идентификатору группы (GID)\&.
.RE
.PP
By default,
\fBgrpck\fR
operates on
/etc/groupand /etc/gshadow\&. The user may select alternate files with the
\fIgroup\fRand \fIshadow\fR parameters\&.
.SH "НАСТРОЙКА"
.PP
На работу этого инструмента влияют следующие переменные настройки из
/etc/login\&.defs:
.PP
\fBMAX_MEMBERS_PER_GROUP\fR (число)
.RS 4
Максимальное количество членов в записи о группе\&. При достижения максимума заводится новая запись группы (строка) в
/etc/group
(с тем же именем, паролем и тем же GID)\&.
.sp
Значение по умолчанию равно 0, означающее, что ограничения на количество членов в группе нет\&.
.sp
Данная возможность (разделение группы) позволяет ограничить длину строк в файле групп\&. Это полезно для ограничения длины строк групп NIS в 1024 символа\&.
.sp
Если вам нужно такое ограничение, укажите значение 25\&.
.sp
Замечание: разделение групп поддерживается не всеми инструментами (даже в наборе инструментов Shadow)\&. Вы не должны использовать эту переменную, если вам действительно это ненужно\&.
.RE
.SH "ФАЙЛЫ"
.PP
/etc/group
.RS 4
содержит информацию о группах
.RE
.PP
/etc/gshadow
.RS 4
содержит защищаемую информацию о группах
.RE
.PP
/etc/passwd
.RS 4
содержит информацию о пользователях
.RE
.SH "ВОЗВРАЩАЕМЫЕ ЗНАЧЕНИЯ"
.PP
Команда
\fBgrpck\fR
завершая работу, возвращает следующие значения:
.PP
\fI0\fR
.RS 4
успешное выполнение
.RE
.PP
\fI1\fR
.RS 4
ошибка в параметрах команды
.RE
.PP
\fI2\fR
.RS 4
есть одна или более неправильных записей групп
.RE
.PP
\fI3\fR
.RS 4
не удалось открыть файл групп
.RE
.PP
\fI4\fR
.RS 4
не удалось заблокировать файл групп
.RE
.PP
\fI5\fR
.RS 4
не удалось изменить файл групп
.RE
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBgroup\fR(5),
\fBgroupmod\fR(8),
\fBgshadow\fR(5),\fBpasswd\fR(5),
\fBpwck\fR(8),
\fBshadow\fR(5)\&.
