'\" t
.\"     Title: lastlog
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 05/09/2014
.\"    Manual: Команды управления системой
.\"    Source: shadow-utils 4.2
.\"  Language: Russian
.\"
.TH "lastlog" "8" "05/09/2014" "shadow\-utils 4\&.2" "Команды управления системой"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВАНИЕ"
lastlog \- выводит отчёт о последней регистрации в системе всех или указанного пользователя
.SH "СИНТАКСИС"
.HP \w'\fBlastlog\fR\ 'u
\fBlastlog\fR [\fIпараметры\fR]
.SH "ОПИСАНИЕ"
.PP
Программа
\fBlastlog\fR
упорядочивает и выводит содержимое файла
/var/log/lastlog, который содержит даты последнего входа пользователей в систему\&. Выводятся
\fIимя пользователя\fR,
\fIпорт\fR
и
\fIдата последнего входа в систему\fR\&. По умолчанию (вызов без параметров) показываются записи файла lastlog, отсортированные согласно расположению пользователей в файле
/etc/passwd\&.
.SH "ПАРАМЕТРЫ"
.PP
Параметры команды
\fBlastlog\fR:
.PP
\fB\-b\fR, \fB\-\-before\fR\ \&\fIДНЕЙ\fR
.RS 4
Показать записи lastlog за последние
\fIДНЕЙ\fR\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Показать краткую справку и закончить работу\&.
.RE
.PP
\fB\-R\fR, \fB\-\-root\fR\ \&\fIКАТ_CHROOT\fR
.RS 4
Выполнить изменения в каталоге
\fIКАТ_CHROOT\fR
и использовать файлы настройки из каталога
\fIКАТ_CHROOT\fR\&.
.RE
.PP
\fB\-t\fR, \fB\-\-time\fR\ \&\fIДНЕЙ\fR
.RS 4
Показать записи lastlog новее чем
\fIДНЕЙ\fR\&.
.RE
.PP
\fB\-u\fR, \fB\-\-user\fR\ \&\fIУЧЁТНАЯ ЗАПИСЬ\fR|\fIДИАПАЗОН\fR
.RS 4
Показать запись lastlog только для указанного пользователя(ей)\&.
.sp
Пользователя можно указать по отдельному имени, числовому идентификатору или в виде
\fIДИАПАЗОНА\fR
пользователей\&. Такой
\fIДИАПАЗОН\fR
можно задавать в виде максимального и минимального значений(\fIUID_МИН\-UID_МАКС\fR), максимального (\fI\-UID_МАКС\fR) или минимального (\fIUID_МИН\-\fR) значения\&.
.RE
.PP
Если пользователь никогда не регистрировался в системе, то будет показано сообщение
\fI** Никогда не входил в систему**\fR
вместо названия порта и даты\&.
.PP
Будут показаны записи только для пользователей, имеющих в системе данный момент\&. В журнале могут существовать записи для удалённых ранее пользователей\&.
.SH "ЗАМЕЧАНИЕ"
.PP
Файл
lastlog
содержит информацию о последней регистрации в системе каждого пользователя\&. Вы не должны применять к нему ротацию журнальных файлов\&. Этот файл является разреженным, поэтому его размер на диске гораздо меньше, чем показывает команда \(Fo\fBls \-l\fR\(Fc (которая может показывать, что это очень большой файл, если значения идентификаторов пользователей в системе достигают больших значений)\&. Чтобы увидеть реальный размер введите \(Fo\fBls \-s\fR\(Fc\&.
.SH "ФАЙЛЫ"
.PP
/var/log/lastlog
.RS 4
содержит список завершённых сеансов работы с системой
.RE
.SH "ПРЕДОСТЕРЕЖЕНИЯ"
.PP
Большие промежутки в значениях идентификаторов пользователей приводят к тому, что программа некоторое время ничего не выводит на экран (то есть, если в базе данных lastlog нет пользователей с идентификаторами с 170 по 800, то во время обработки UID с 171 по 799 программа кажется повисшей)\&.
