'\" t
.\"     Title: newusers
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 05/09/2014
.\"    Manual: Команды управления системой
.\"    Source: shadow-utils 4.2
.\"  Language: Russian
.\"
.TH "newusers" "8" "05/09/2014" "shadow\-utils 4\&.2" "Команды управления системой"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВАНИЕ"
newusers \- обновляет и создаёт новые учётные записи пользователей в пакетном режиме
.SH "СИНТАКСИС"
.HP \w'\fBnewusers\fR\ 'u
\fBnewusers\fR [\fIпараметры\fR] [\fIфайл\fR]
.SH "ОПИСАНИЕ"
.PP
Программа
\fBnewusers\fR
читает
\fIфайл\fR
(или по умолчанию стандартный ввод) и использует эту информацию для обновления группы существующих или создания новых учётных записей\&. Каждая строка имеет формат стандартного файла паролей (смотрите
\fBpasswd\fR(5)) за исключением:
.PP
pw_name:pw_passwd:pw_uid:pw_gid:pw_gecos:pw_dir:pw_shell
.PP
\fIpw_name\fR
.RS 4
Имя пользователя\&.
.sp
Это может быть имя нового пользователя или имя существующего пользователя (или пользователя, созданного
\fBnewusers\fR
ранее)\&. Если пользователь существует, то будет изменена информация о пользователе, или же создаётся новый пользователь\&.
.RE
.PP
\fIpw_passwd\fR
.RS 4
Это поле будет зашифровано и использовано как новое значение шифрованного пароля\&.
.RE
.PP
\fI pw_gid\fR
.RS 4
Это поле используется для определения UID пользователя\&.
.sp
Если это поле пусто, то командой
\fBnewusers\fR
автоматически определяется новый (неиспользованный) UID\&.
.sp
Если в этом поле указано число, то оно будет использовано в качестве UID\&.
.sp
Если в поле содержится имя существующего пользователя (или имя пользователя, созданного
\fBnewusers\fR
ранее), то использует UID указанного пользователя\&.
.sp
Если изменяется UID существующего пользователя, то у файлов, которыми владел этот пользователь, нужно вручную переопределить владельца\&.
.RE
.PP
\fIpw_gid\fR
.RS 4
Это поле используется для определения ID первичной группы пользователя\&.
.sp
Если в этом поле содержится имя существующей группы (или группы, созданной
\fBnewusers\fR
ранее), то в качестве ID первичной группы пользователя будет использован GID этой группы\&.
.sp
Если в этом поле содержится число, то это число будет использовано как ID первичной группы пользователя\&. Если с таким GID не существует, то будет создана новая группа с этим GID и именем пользователя\&.
.sp
Если это поле пусто, то новая группа будет создана с именем пользователя, а GID будет определён
\fBnewusers\fR
автоматически (для использования в качестве ID первичной группы пользователя и GID новой группы)\&.
.sp
Если поле содержит имя группы, которой не существует (и которая не была создана
\fBnewusers\fR
ранее), то будет создана новая группа с указанным именем, GID будет определён
\fBnewusers\fR
автоматически (для использования в качестве ID первичной группы пользователя и GID новой группы)\&.
.RE
.PP
\fIpw_gecos\fR
.RS 4
Это поле копируется в поле GECOS записи пользователя\&.
.RE
.PP
\fIpw_dir\fR
.RS 4
Это поле используется для определения домашнего каталога пользователя\&.
.sp
Если это поле указывает на несуществующий каталог, то указанный каталог создаётся, его владельцем назначается создаваемый или обновляемый пользователь и его первичная группа\&.
.sp
Если изменяется домашний каталог существующего пользователя, то команда
\fBnewusers\fR
не перемещает или копирует содержимое старого каталога в новое место\&. Это нужно выполнить вручную\&.
.RE
.PP
\fIpw_shell\fR
.RS 4
В этом поле задаётся пользовательская оболочка\&. Никаких проверок поля не делается\&.
.RE
.PP
Команда
\fBnewusers\fR
сначала пытается создать или изменить всех указанных пользователей, а затем записать эти изменения в базы данных пользователей или групп\&. Если происходит ошибка (кроме ошибок при последней записи в базы данных), то изменения в базы не сохраняются\&.
.PP
Данная команда предназначена для работы в крупных системных средах, где за один раз обновляется несколько учётных записей\&.
.SH "ПАРАМЕТРЫ"
.PP
Параметры команды
\fBnewusers\fR:
.PP
\fB\-c\fR, \fB\-\-crypt\-method\fR
.RS 4
Использовать указанный метод для шифрования паролей\&.
.sp
Возможные методы: DES, MD5, NONE и SHA256 или SHA512, если эти методы поддерживается libc\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Показать краткую справку и закончить работу\&.
.RE
.PP
\fB\-r\fR, \fB\-\-system\fR
.RS 4
Создать системную учётную запись\&.
.sp
Системные пользователи создаются без информации об устаревании в
/etc/shadow, и их числовые идентификаторы выбираются из диапазона
\fBSYS_UID_MIN\fR\-\fBSYS_UID_MAX\fR, определённого в
login\&.defs, а не из
\fBUID_MIN\fR\-\fBUID_MAX\fR
(это же касается и части с
\fBGID\fR
при создании групп)\&.
.RE
.PP
\fB\-R\fR, \fB\-\-root\fR\ \&\fIКАТ_CHROOT\fR
.RS 4
Выполнить изменения в каталоге
\fIКАТ_CHROOT\fR
и использовать файлы настройки из каталога
\fIКАТ_CHROOT\fR\&.
.RE
.PP
\fB\-s\fR, \fB\-\-sha\-rounds\fR
.RS 4
Использовать указанное количество раундов шифрования паролей\&.
.sp
Значение 0 означает, что система выберет количество раундов по умолчанию для выбранного метода шифрования (5000)\&.
.sp
Минимальное значение равно 1000, а максимальное значение равно 999,999,999\&.
.sp
Вы можете использовать этот параметр только при методе шифрования SHA256 или SHA512\&.
.sp
По умолчанию, количество раундов определяется переменными SHA_CRYPT_MIN_ROUNDS и SHA_CRYPT_MAX_ROUNDS из
/etc/login\&.defs\&.
.RE
.SH "ПРЕДОСТЕРЕЖЕНИЯ"
.PP
Файл с входными данными должен быть защищён, так как в нём содержатся не шифрованные пароли\&.
.PP
Вы должны проверить, что пароль и метод шифрования соответствует политике системных паролей\&.
.SH "НАСТРОЙКА"
.PP
На работу этого инструмента влияют следующие переменные настройки из
/etc/login\&.defs:
.PP
\fBENCRYPT_METHOD\fR (строка)
.RS 4
Задаёт системный алгоритм шифрования по умолчанию для шифрования паролей (используется, если алгоритм не указан в командной строке)\&.
.sp
Возможны следующие значения:
\fIDES\fR
(по умолчанию),
\fIMD5\fR, \fISHA256\fR, \fISHA512\fR\&.
.sp
Замечание: этот параметр переопределяет переменную
\fBMD5_CRYPT_ENAB\fR\&.
.RE
.PP
\fBGID_MAX\fR (число), \fBGID_MIN\fR (число)
.RS 4
Диапазон идентификаторов групп, используемый в программах
\fBuseradd\fR,
\fBgroupadd\fR
или
\fBnewusers\fR
для создания обычных групп\&.
.sp
Значение по умолчанию для
\fBGID_MIN\fR
(соотв\&.
\fBGID_MAX\fR) равно 1000 (соотв\&. 60000)\&.
.RE
.PP
\fBMAX_MEMBERS_PER_GROUP\fR (число)
.RS 4
Максимальное количество членов в записи о группе\&. При достижения максимума заводится новая запись группы (строка) в
/etc/group
(с тем же именем, паролем и тем же GID)\&.
.sp
Значение по умолчанию равно 0, означающее, что ограничения на количество членов в группе нет\&.
.sp
Данная возможность (разделение группы) позволяет ограничить длину строк в файле групп\&. Это полезно для ограничения длины строк групп NIS в 1024 символа\&.
.sp
Если вам нужно такое ограничение, укажите значение 25\&.
.sp
Замечание: разделение групп поддерживается не всеми инструментами (даже в наборе инструментов Shadow)\&. Вы не должны использовать эту переменную, если вам действительно это ненужно\&.
.RE
.PP
\fBMD5_CRYPT_ENAB\fR (логический)
.RS 4
Обозначает, что пароль должен быть зашифрован по алгоритму на основе MD5\&. Если значение равно
\fIyes\fR, то новые пароли будут зашифрованы по алгоритму на основе MD5, совместимому с используемым в новых версиях FreeBSD\&. Он поддерживает пароли неограниченной длины и имеет более длинную строку соли\&. Установите в
\fIno\fR, если вам нужно копировать шифрованные пароли в другие системы, которые не поддерживают новый алгоритм\&. По умолчанию
\fIno\fR\&.
.sp
Эта переменная переопределяется переменной
\fBENCRYPT_METHOD\fR
или любым параметром командной строки, который задаёт алгоритм шифрования\&.
.sp
Эта переменная устарела; используйте
\fBENCRYPT_METHOD\fR\&.
.RE
.PP
\fBPASS_MAX_DAYS\fR (число)
.RS 4
Максимальное число дней использования пароля\&. Если пароль старее этого числа, то будет запущена процедура смены пароля\&. Если значение не задано, то предполагается значение \-1 (то есть возможность ограничения не используется)\&.
.RE
.PP
\fBPASS_MIN_DAYS\fR (число)
.RS 4
Максимальное число дней между изменениями пароля\&. Любая смена пароля ранее заданного срока выполнена не будет\&. Если значение не задано, то предполагается значение \-1 (то есть возможность ограничения не используется)\&.
.RE
.PP
\fBPASS_WARN_AGE\fR (число)
.RS 4
Число дней за которое начнёт выдаваться предупреждение об устаревании пароля\&. Нулевое значение означает, что предупреждение выдаётся в день устаревания, при отрицательном значении предупреждение выдаваться не будет\&. Если значение не задано, выдача предупреждения отключается\&.
.RE
.PP
\fBSHA_CRYPT_MIN_ROUNDS\fR (число), \fBSHA_CRYPT_MAX_ROUNDS\fR (число)
.RS 4
Если значение
\fBENCRYPT_METHOD\fR
равно
\fISHA256\fR
или
\fISHA512\fR, эта переменная определяет количество раундов SHA, используемых алгоритмом шифрования по умолчанию (если количество раундов не задано в командной строке)\&.
.sp
Увеличение количества раундов повышает сложность подбора пароля простым перебором\&. Но заметим, что при этом для аутентификации пользователей требуется большее количество процессорных ресурсов\&.
.sp
Если не задана, то libc выбирает значение количества раундов по умолчанию (5000)\&.
.sp
Значения должны лежать в диапазоне 1000\-999999999\&.
.sp
Если задано какое\-то одно значение \(em
\fBSHA_CRYPT_MIN_ROUNDS\fR
или
\fBSHA_CRYPT_MAX_ROUNDS\fR
\(em то будет использовано это значение\&.
.sp
Если
\fBSHA_CRYPT_MIN_ROUNDS\fR
>
\fBSHA_CRYPT_MAX_ROUNDS\fR, то используется большее значение\&.
.RE
.PP
\fBSUB_GID_MIN\fR (number), \fBSUB_GID_MAX\fR (number), \fBSUB_GID_COUNT\fR (number)
.RS 4
If
/etc/subuid
exists, the commands
\fBuseradd\fR
and
\fBnewusers\fR
(unless the user already have subordinate group IDs) allocate
\fBSUB_GID_COUNT\fR
unused group IDs from the range
\fBSUB_GID_MIN\fR
to
\fBSUB_GID_MAX\fR
for each new user\&.
.sp
The default values for
\fBSUB_GID_MIN\fR,
\fBSUB_GID_MAX\fR,
\fBSUB_GID_COUNT\fR
are respectively 100000, 600100000 and 10000\&.
.RE
.PP
\fBSUB_UID_MIN\fR (number), \fBSUB_UID_MAX\fR (number), \fBSUB_UID_COUNT\fR (number)
.RS 4
If
/etc/subuid
exists, the commands
\fBuseradd\fR
and
\fBnewusers\fR
(unless the user already have subordinate user IDs) allocate
\fBSUB_UID_COUNT\fR
unused user IDs from the range
\fBSUB_UID_MIN\fR
to
\fBSUB_UID_MAX\fR
for each new user\&.
.sp
The default values for
\fBSUB_UID_MIN\fR,
\fBSUB_UID_MAX\fR,
\fBSUB_UID_COUNT\fR
are respectively 100000, 600100000 and 10000\&.
.RE
.PP
\fBSYS_GID_MAX\fR (число), \fBSYS_GID_MIN\fR (число)
.RS 4
Диапазон идентификаторов групп, используемый в программах
\fBuseradd\fR,
\fBgroupadd\fR
или
\fBnewusers\fR
для создания системных групп\&.
.sp
Значение по умолчанию для
\fBSYS_GID_MIN\fR
(соотв\&.\fBSYS_GID_MAX\fR) равно 101 (соотв\&.
\fBGID_MIN\fR\-1)\&.
.RE
.PP
\fBSYS_UID_MAX\fR (число), \fBSYS_UID_MIN\fR (число)
.RS 4
Диапазон идентификаторов пользователей, используемый в программах
\fBuseradd\fR
или
\fBnewusers\fR
для создания системных пользователей\&.
.sp
Значение по умолчанию для
\fBSYS_UID_MIN\fR
(соотв\&.
\fBSYS_UID_MAX\fR) равно 101 (соотв\&.
\fBUID_MIN\fR\-1)\&.
.RE
.PP
\fBUID_MAX\fR (число), \fBUID_MIN\fR (число)
.RS 4
Диапазон идентификаторов пользователей, используемый в программах
\fBuseradd\fR
или
\fBnewusers\fR
для создания обычных пользователей\&.
.sp
Значение по умолчанию для
\fBUID_MIN\fR
(соотв\&.
\fBUID_MAX\fR) равно 1000 (соотв\&. 60000)\&.
.RE
.PP
\fBUMASK\fR (число)
.RS 4
Задаёт начальное значение маски доступа для создаваемых файлов\&. Если не указано, то маска устанавливается в 022\&.
.sp
Команды
\fBuseradd\fR
и
\fBnewusers\fR
используют эту маску для установки прав доступа к домашнему каталогу, который они создают\&.
.sp
Также она используется программой
\fBlogin\fR
для задания начального значения umask пользователя\&. Заметим, что эта маска может быть переопределена из пользовательской строки GECOS (если установлена переменная
\fBQUOTAS_ENAB\fR) или указанием ограничения с идентификатором
\fIK\fR, в
\fBlimits\fR(5)\&.
.RE
.SH "ФАЙЛЫ"
.PP
/etc/passwd
.RS 4
содержит информацию о пользователях
.RE
.PP
/etc/shadow
.RS 4
содержит защищаемую информацию о пользователях
.RE
.PP
/etc/group
.RS 4
содержит информацию о группах
.RE
.PP
/etc/gshadow
.RS 4
содержит защищаемую информацию о группах
.RE
.PP
/etc/login\&.defs
.RS 4
содержит конфигурацию подсистемы теневых паролей
.RE
.PP
/etc/subgid
.RS 4
Per user subordinate group IDs\&.
.RE
.PP
/etc/subuid
.RS 4
Per user subordinate user IDs\&.
.RE
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBlogin.defs\fR(5),
\fBpasswd\fR(1),
\fBsubgid\fR(5), \fBsubuid\fR(5),\fBuseradd\fR(8)\&.
