'\" t
.\"     Title: pwck
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 05/09/2014
.\"    Manual: Команды управления системой
.\"    Source: shadow-utils 4.2
.\"  Language: Russian
.\"
.TH "pwck" "8" "05/09/2014" "shadow\-utils 4\&.2" "Команды управления системой"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВАНИЕ"
pwck \- проверяет целостность файлов паролей
.SH "СИНТАКСИС"
.HP \w'\fBpwck\fR\ 'u
\fBpwck\fR [параметры] [\fIpasswd\fR\ [\ \fIshadow\fR\ ]]
.SH "ОПИСАНИЕ"
.PP
Программа
\fBpwck\fR
проверяет целостность информации о пользователях и аутентификации\&. Проверяется формат всех записей файлов
/etc/passwd
и
/etc/shadow
и корректность данных каждого поля\&. В случае обнаружения ошибок пользователю предлагается подтвердить удаление записей, имеющих неверный формат или восстановление которых невозможно\&.
.PP
Выполняются следующие проверки:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
правильное количество полей
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
уникальность и корректность имени пользователя
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
корректность идентификатора пользователя и группы
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
корректность первичной группы
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
корректность домашнего каталога
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
корректность регистрационной оболочки
.RE
.PP
Проверки
shadow
выполняются, если указан второй файловый параметр или когда в системе существует файл
/etc/shadow\&.
.PP
Выполняются следующие проверки:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
что каждая запись passwd имеет соответствующую запись shadow и каждая запись shadow имеет соответствующую запись passwd
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
пароли указаны в теневом файле
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
записи shadow содержат корректное количество полей
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
записи shadow уникальны в shadow
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
дата последней смены пароля не находится в будущем
.RE
.PP
Ошибки в количестве полей и уникальности имён пользователей невосстановимы\&. Если запись содержит неверное число полей, пользователя попросят подтвердить удаление всей записи\&. Если пользователь ответит отрицательно, дальнейшая проверка выполняться не будет\&. При ошибке повторения имени пользователя также возникает запрос на удаление, но в случае отказа проверка будет продолжена\&. Обо всех остальных ошибках выводится предупреждение и пользователю предлагается запустить команду
\fBusermod\fR, чтобы исправить ошибку\&.
.PP
Команды, которые работают с файлом
/etc/passwd, не могут изменять повреждённые или дублирующиеся записи\&. Как раз в этом случае и нужно использовать
\fBpwck\fR
для удаления испорченной записи\&.
.SH "ПАРАМЕТРЫ"
.PP
Параметры
\fB\-r\fR,
\fB\-s\fR
не могут использоваться одновременно\&.
.PP
Параметры команды
\fBpwck\fR:
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Показать краткую справку и закончить работу\&.
.RE
.PP
\fB\-q\fR, \fB\-\-quiet\fR
.RS 4
Сообщать только об ошибках\&. Предупреждения, которые не требуют от пользователя никаких действий, показаны не будут\&.
.RE
.PP
\fB\-r\fR, \fB\-\-read\-only\fR
.RS 4
Выполнять команду
\fBpwck\fR
в режиме \(Foтолько чтение\(Fc\&.
.RE
.PP
\fB\-R\fR, \fB\-\-root\fR\ \&\fIКАТ_CHROOT\fR
.RS 4
Выполнить изменения в каталоге
\fIКАТ_CHROOT\fR
и использовать файлы настройки из каталога
\fIКАТ_CHROOT\fR\&.
.RE
.PP
\fB\-s\fR, \fB\-\-sort\fR
.RS 4
Отсортировать все записи в файлах
/etc/passwd
и
/etc/shadow
по числовому идентификатору пользователя\&.
.RE
.PP
По умолчанию, команда
\fBpwck\fR
работает с файлами
/etc/passwd
и
/etc/shadow\&. Пользователь может указать другие файлы с помощью параметров
\fIpasswd\fR
и
\fIshadow\fR\&.
.SH "НАСТРОЙКА"
.PP
На работу этого инструмента влияют следующие переменные настройки из
/etc/login\&.defs:
.PP
\fBPASS_MAX_DAYS\fR (число)
.RS 4
Максимальное число дней использования пароля\&. Если пароль старее этого числа, то будет запущена процедура смены пароля\&. Если значение не задано, то предполагается значение \-1 (то есть возможность ограничения не используется)\&.
.RE
.PP
\fBPASS_MIN_DAYS\fR (число)
.RS 4
Максимальное число дней между изменениями пароля\&. Любая смена пароля ранее заданного срока выполнена не будет\&. Если значение не задано, то предполагается значение \-1 (то есть возможность ограничения не используется)\&.
.RE
.PP
\fBPASS_WARN_AGE\fR (число)
.RS 4
Число дней за которое начнёт выдаваться предупреждение об устаревании пароля\&. Нулевое значение означает, что предупреждение выдаётся в день устаревания, при отрицательном значении предупреждение выдаваться не будет\&. Если значение не задано, выдача предупреждения отключается\&.
.RE
.SH "ФАЙЛЫ"
.PP
/etc/group
.RS 4
содержит информацию о группах
.RE
.PP
/etc/passwd
.RS 4
содержит информацию о пользователях
.RE
.PP
/etc/shadow
.RS 4
содержит защищаемую информацию о пользователях
.RE
.SH "ВОЗВРАЩАЕМЫЕ ЗНАЧЕНИЯ"
.PP
Команда
\fBpwck\fR
завершая работу, возвращает следующие значения:
.PP
\fI0\fR
.RS 4
успешное выполнение
.RE
.PP
\fI1\fR
.RS 4
ошибка в параметрах команды
.RE
.PP
\fI2\fR
.RS 4
есть одна или более записей с недопустимыми паролями
.RE
.PP
\fI3\fR
.RS 4
не удалось открыть файл паролей
.RE
.PP
\fI4\fR
.RS 4
не удалось заблокировать файл паролей
.RE
.PP
\fI5\fR
.RS 4
не удалось изменить файл паролей
.RE
.PP
\fI6\fR
.RS 4
не удалось отсортировать файл паролей
.RE
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBgroup\fR(5),
\fBgrpck\fR(8),
\fBpasswd\fR(5),
\fBshadow\fR(5),
\fBusermod\fR(8)\&.
