'\" t
.\"     Title: pwconv
.\"    Author: Marek Micha\(/lkiewicz
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 05/09/2014
.\"    Manual: Команды управления системой
.\"    Source: shadow-utils 4.2
.\"  Language: Russian
.\"
.TH "pwconv" "8" "05/09/2014" "shadow\-utils 4\&.2" "Команды управления системой"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВАНИЕ"
pwconv, pwunconv, grpconv, grpunconv \- преобразует пароли пользователей и групп в/из защищённую форму
.SH "СИНТАКСИС"
.HP \w'\fBpwconv\fR\ 'u
\fBpwconv\fR [\fIпараметры\fR]
.HP \w'\fBpwunconv\fR\ 'u
\fBpwunconv\fR [\fIпараметры\fR]
.HP \w'\fBgrpconv\fR\ 'u
\fBgrpconv\fR [\fIпараметры\fR]
.HP \w'\fBgrpunconv\fR\ 'u
\fBgrpunconv\fR [\fIпараметры\fR]
.SH "ОПИСАНИЕ"
.PP
Команда
\fBpwconv\fR
создаёт файл
\fIshadow\fR
из файла
\fIpasswd\fR
и необязательно существующего файла
\fIshadow\fR\&.
.PP
Команда
\fBpwunconv\fR
создаёт файл
\fIpasswd\fR
из файлов
\fIpasswd\fR
и
\fIshadow\fR, а затем удаляет файл
\fIshadow\fR\&.
.PP
Команда
\fBgrpconv\fR
создаёт файл
\fIgshadow\fR
из файла
\fIgroup\fR
и необязательно существующего файла
\fIgshadow\fR\&.
.PP
Команда
\fBgrpunconv\fR
создаёт файл
\fIgroup\fR
из файлов
\fIgroup\fR
и
\fIgshadow\fR, а затем удаляет файл
\fIgshadow\fR\&.
.PP
Эти четыре программы работают с файлами обычных или теневых паролей пользователей и групп:
/etc/passwd,
/etc/group,
/etc/shadow
и
/etc/gshadow\&.
.PP
Каждая программа выполняет необходимые блокировки перед преобразованиями\&. Команды
\fBpwconv\fR
и
\fBgrpconv\fR
выполняют схожий порядок действий\&. Сначала удаляются записи из теневого файла которых нет в главном файле\&. Затем обновляются записи в теневом файле которые не содержат \(Fox\(Fc вместо пароля в главном файле\&. Далее добавляются отсутствующие теневые записи\&. Наконец, пароли в главном файле заменяются символом \(Fox\(Fc\&. Данные программы можно использовать как для первоначального преобразования, так и для обновления теневого файла, если главный файл редактировался вручную\&.
.PP
Команда
\fBpwconv\fR
использует значения переменных
\fIPASS_MIN_DAYS\fR,
\fIPASS_MAX_DAYS\fR
и
\fIPASS_WARN_AGE\fR
из файла
/etc/login\&.defs
при добавлении новых записей в файл
/etc/shadow\&.
.PP
Программы
\fBpwunconv\fR
и
\fBgrpunconv\fR
также выполняют схожий порядок действий\&. Пароли в главном файле обновляются из теневого файла\&. Записи, которые существуют в главном файле, но не существуют в теневом файле оставляются как есть\&. По окончании, теневой файл удаляется\&. Информация об устаревании пароля не учитывается программой
\fBpwunconv\fR\&. Конвертируется только возможное\&.
.SH "ПАРАМЕТРЫ"
.PP
Параметры, применимые к
\fBpwconv\fR,
\fBpwunconv\fR,
\fBgrpconv\fR
и
\fBgrpunconv\fR:
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Показать краткую справку и закончить работу\&.
.RE
.PP
\fB\-R\fR, \fB\-\-root\fR\ \&\fIКАТ_CHROOT\fR
.RS 4
Выполнить изменения в каталоге
\fIКАТ_CHROOT\fR
и использовать файлы настройки из каталога
\fIКАТ_CHROOT\fR\&.
.RE
.SH "ОШИБКИ РЕАЛИЗАЦИИ"
.PP
Ошибки в файлах паролей или групп (типа неверных или дублирующихся записей) могут зациклить программу или произойдут какие\-то другие странные вещи\&. Перед конвертацией запустите
\fBpwck\fR
и
\fBgrpck\fR, чтобы исправить возможные ошибки\&.
.SH "НАСТРОЙКА"
.PP
Следующая переменная настройки в
/etc/login\&.defs
изменяет поведение
\fBgrpconv\fR
и
\fBgrpunconv\fR:
.PP
\fBMAX_MEMBERS_PER_GROUP\fR (число)
.RS 4
Максимальное количество членов в записи о группе\&. При достижения максимума заводится новая запись группы (строка) в
/etc/group
(с тем же именем, паролем и тем же GID)\&.
.sp
Значение по умолчанию равно 0, означающее, что ограничения на количество членов в группе нет\&.
.sp
Данная возможность (разделение группы) позволяет ограничить длину строк в файле групп\&. Это полезно для ограничения длины строк групп NIS в 1024 символа\&.
.sp
Если вам нужно такое ограничение, укажите значение 25\&.
.sp
Замечание: разделение групп поддерживается не всеми инструментами (даже в наборе инструментов Shadow)\&. Вы не должны использовать эту переменную, если вам действительно это ненужно\&.
.RE
.PP
Следующая переменная настройки в
/etc/login\&.defs
изменяет поведение
\fBpwconv\fR:
.PP
\fBPASS_MAX_DAYS\fR (число)
.RS 4
Максимальное число дней использования пароля\&. Если пароль старее этого числа, то будет запущена процедура смены пароля\&. Если значение не задано, то предполагается значение \-1 (то есть возможность ограничения не используется)\&.
.RE
.PP
\fBPASS_MIN_DAYS\fR (число)
.RS 4
Максимальное число дней между изменениями пароля\&. Любая смена пароля ранее заданного срока выполнена не будет\&. Если значение не задано, то предполагается значение \-1 (то есть возможность ограничения не используется)\&.
.RE
.PP
\fBPASS_WARN_AGE\fR (число)
.RS 4
Число дней за которое начнёт выдаваться предупреждение об устаревании пароля\&. Нулевое значение означает, что предупреждение выдаётся в день устаревания, при отрицательном значении предупреждение выдаваться не будет\&. Если значение не задано, выдача предупреждения отключается\&.
.RE
.SH "ФАЙЛЫ"
.PP
/etc/login\&.defs
.RS 4
содержит конфигурацию подсистемы теневых паролей
.RE
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBgrpck\fR(8),
\fBlogin.defs\fR(5),
\fBpwck\fR(8)\&.
