'\" t
.\"     Title: useradd
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 05/09/2014
.\"    Manual: Команды управления системой
.\"    Source: shadow-utils 4.2
.\"  Language: Russian
.\"
.TH "useradd" "8" "05/09/2014" "shadow\-utils 4\&.2" "Команды управления системой"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВАНИЕ"
useradd \- регистрирует нового пользователя или изменяет информацию по умолчанию о новых пользователях
.SH "СИНТАКСИС"
.HP \w'\fBuseradd\fR\ 'u
\fBuseradd\fR [\fIпараметры\fR] \fIУЧЁТНАЯ_ЗАПИСЬ\fR
.HP \w'\fBuseradd\fR\ 'u
\fBuseradd\fR \-D
.HP \w'\fBuseradd\fR\ 'u
\fBuseradd\fR \-D [\fIпараметры\fR]
.SH "ОПИСАНИЕ"
.PP
При запуске без параметра
\fB\-D\fR
команда
\fBuseradd\fR
создаёт новую учётную запись пользователя, используя значения из командной строки и системные значения по умолчанию\&. В зависимости от параметров командной строки, команда
\fBuseradd\fR
обновляет системные файлы, а также может создать домашний каталог нового пользователя и скопировать начальные файлы настроек\&.
.PP
По умолчанию, для нового пользователя также создаётся группа (смотрите параметры
\fB\-g\fR,
\fB\-N\fR,
\fB\-U\fR
и
\fBUSERGROUPS_ENAB\fR)\&.
.SH "ПАРАМЕТРЫ"
.PP
Параметры команды
\fBuseradd\fR:
.PP
\fB\-b\fR, \fB\-\-base\-dir\fR \fIБАЗОВЫЙ_КАТАЛОГ\fR
.RS 4
Базовый системный каталог по умолчанию, если другой каталог не указан с помощью параметра
\fB\-d\fR\&. Значение
\fIБАЗОВЫЙ_КАТАЛОГ\fR
объединяется с именем учётной записи для определения домашнего каталога\&. Если не указан параметр
\fB\-m\fR, то
\fIБАЗОВЫЙ_КАТАЛОГ\fR
должен существовать\&.
.sp
Если этот параметр не задан, то команда
\fBuseradd\fR
будет использовать базовый каталог, указанный в переменной
\fBHOME\fR
в файле
/etc/default/useradd
иначе
/home
(по умолчанию)\&.
.RE
.PP
\fB\-c\fR, \fB\-\-comment\fR\ \&\fIКОММЕНТАРИЙ\fR
.RS 4
Любая текстовая строка\&. Обычно, здесь коротко описывается учётная запись, и в настоящее время используется как поле для имени и фамилии пользователя\&.
.RE
.PP
\fB\-d\fR, \fB\-\-home\-dir\fR \fIДОМАШНИЙ_КАТАЛОГ\fR
.RS 4
Для создаваемого пользователя будет использован каталог
\fIДОМАШНИЙ_КАТАЛОГ\fR
в качестве начального каталога\&. По умолчанию, это значение получается объединением
\fIИМЕНИ\fR
пользователя с
\fIБАЗОВЫМ_КАТАЛОГОМ\fR
и используется как имя домашнего каталога\&. Каталог
\fIДОМАШНИЙ_КАТАЛОГ\fR
необязательно должен существовать, но не будет создан, если его нет\&.
.RE
.PP
\fB\-D\fR, \fB\-\-defaults\fR
.RS 4
Смотрите далее в подразделе \(FoИзменение значений по умолчанию\(Fc\&.
.RE
.PP
\fB\-e\fR, \fB\-\-expiredate\fR \fIДАТА_УСТАРЕВАНИЯ\fR
.RS 4
Дата, когда учётная запись пользователя будет заблокирована\&. Дата задаётся в формате
\fIГГГГ\-ММ\-ДД\fR\&.
.sp
Если этот параметр не задан, то команда
\fBuseradd\fR
будет использовать дату устаревания по умолчанию, указанную в переменной
\fBEXPIRE\fR
в файле
/etc/default/useradd, иначе пустую строку (без устаревания, по умолчанию)\&.
.RE
.PP
\fB\-f\fR, \fB\-\-inactive\fR\ \&\fIДНЕЙ\fR
.RS 4
Если указано значение 0, то учётная запись блокируется сразу после устаревания пароля, а при значении \-1 данная возможность не используется\&.
.sp
Если этот параметр не задан, то команда
\fBuseradd\fR
будет использовать срок неактивности по умолчанию, указанный в переменной
\fBINACTIVE\fR
в файле
/etc/default/useradd
или \-1 (по умолчанию)\&.
.RE
.PP
\fB\-g\fR, \fB\-\-gid\fR\ \&\fIГРУППА\fR
.RS 4
Имя или числовой идентификатор первичной группы пользователя\&. Группа с таким именем должна существовать\&. Идентификатор группы должен указывать на уже существующую группу\&.
.sp
Если не указан, то поведение
\fBuseradd\fR
зависит от переменной
\fBUSERGROUPS_ENAB\fR
в файле
/etc/login\&.defs\&. Если значение этой переменной равно
\fIyes\fR
(или в командной строке указан параметр
\fB\-U/\-\-user\-group\fR), то для пользователя будет создана группа с тем же именем как его имя для входа\&. Если значение переменной равно
\fIno\fR
(или в командной строке указан параметр
\fB\-N/\-\-no\-user\-group\fR), то useradd установит первичную группу нового пользователя равной значению переменной
\fBGROUP\fR
из файла
/etc/default/useradd, или 100 (по умолчанию)\&.
.RE
.PP
\fB\-G\fR, \fB\-\-groups\fR\ \&\fIГРУППА1\fR[\fI,ГРУППА2,\&...\fR[\fI,ГРУППАN\fR]]]
.RS 4
Список дополнительных групп, в которых числится пользователь\&. Перечисление групп осуществляется через запятую, без промежуточных пробелов\&. На указанные группы действуют те же ограничения, что и для группы указанной в параметре
\fB\-g\fR\&. По умолчанию пользователь входит только в начальную группу\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Показать краткую справку и закончить работу\&.
.RE
.PP
\fB\-k\fR, \fB\-\-skel\fR\ \&\fIКАТАЛОГ_ШАБЛОНОВ\fR
.RS 4
Каталог с шаблонами, который содержит файлы и каталоги для копирования в домашний каталог пользователя при создании домашнего каталога командой
\fBuseradd\fR\&.
.sp
Этот параметр можно использовать только с параметром
\fB\-m\fR
(или
\fB\-\-create\-home\fR)\&.
.sp
Если этот параметр не задан, то каталог шаблонов определяется переменной
\fBSKEL\fR
из файла
/etc/default/useradd, или равен
/etc/skel
(по умолчанию)\&.
.sp
Если возможно, выполняется копирование ACL и расширенных атрибутов\&.
.RE
.PP
\fB\-K\fR, \fB\-\-key\fR\ \&\fIКЛЮЧ\fR=\fIЗНАЧЕНИЕ\fR
.RS 4
Заменяет значения по умолчанию из файла
/etc/login\&.defs
(\fBUID_MIN\fR,
\fBUID_MAX\fR,
\fBUMASK\fR,
\fBPASS_MAX_DAYS\fR
и других)\&.

Пример:
\fB\-K\fR\ \&\fIPASS_MAX_DAYS\fR=\fI\-1\fR
можно использовать при создании системной учётной записи, чтобы выключить устаревание пароля, даже если системная учётная запись вообще не имеет пароля\&. Можно указывать параметр
\fB\-K\fR
несколько раз, например:
\fB\-K\fR\ \&\fIUID_MIN\fR=\fI100\fR\ \&\fB\-K\fR\ \&\fIUID_MAX\fR=\fI499\fR
.RE
.PP
\fB\-l\fR, \fB\-\-no\-log\-init\fR
.RS 4
Не добавлять пользователя в базы данных lastlog и faillog\&.
.sp
По умолчанию, записи пользователя в базах данных lastlog и faillog сбрасываются во избежание повторного использования записи, оставшейся от ранее удалённого пользователя\&.
.RE
.PP
\fB\-m\fR, \fB\-\-create\-home\fR
.RS 4
Создать домашний каталог пользователя, если он не существует\&. Файлы и каталоги, содержащиеся в каталоге шаблонов (который можно указать с помощью параметра the
\fB\-k\fR
option), будут скопированы в домашний каталог\&.
.sp
По умолчанию, если этот параметр не указан и не задана переменная
\fBCREATE_HOME\fR, домашний каталог не создаётся\&.
.RE
.PP
\fB\-M\fR
.RS 4
Не создавать домашний каталог пользователя, даже если значение системной переменной в файле
/etc/login\&.defs
(\fBCREATE_HOME\fR) равно
\fIyes\fR\&.
.RE
.PP
\fB\-N\fR, \fB\-\-no\-user\-group\fR
.RS 4
Не создавать группу с тем же именем как у пользователя, но добавить пользователя в группу, заданную параметром
\fB\-g\fR
или переменной
\fBGROUP\fR
из файла
/etc/default/useradd\&.
.sp
Поведение по умолчанию (если не указан параметр
\fB\-g\fR,
\fB\-N\fR
и
\fB\-U\fR) определяется переменной
\fBUSERGROUPS_ENAB\fR
из файла
/etc/login\&.defs\&.
.RE
.PP
\fB\-o\fR, \fB\-\-non\-unique\fR
.RS 4
Разрешить создание учётной записи с уже имеющимся (не уникальным) UID\&.
.sp
Этот параметр можно использовать только с параметром
\fB\-u\fR\&.
.RE
.PP
\fB\-p\fR, \fB\-\-password\fR\ \&\fIПАРОЛЬ\fR
.RS 4
Шифрованное значение пароля, которое возвращает функция
\fBcrypt\fR(3)\&. По умолчанию пароль отключён\&.
.sp
\fBЗамечание:\fR
Этот параметр использовать не рекомендуется, так как пароль (или не шифрованный пароль) будет видим другими пользователям в списке процессов\&.
.sp
Вы должны проверить, что пароль соответствует политике системных паролей\&.
.RE
.PP
\fB\-r\fR, \fB\-\-system\fR
.RS 4
Создать системную учётную запись\&.
.sp
Системные пользователи создаются без информации об устаревании в
/etc/shadow, и их числовые идентификаторы выбираются из диапазона
\fBSYS_UID_MIN\fR\-\fBSYS_UID_MAX\fR, определённого в
/etc/login\&.defs, а не из
\fBUID_MIN\fR\-\fBUID_MAX\fR
(это же касается и части с
\fBGID\fR
при создании групп)\&.
.sp
Заметим, что
\fBuseradd\fR
не создаёт домашний каталог для данного пользователя независимо от значения по умолчанию в
/etc/login\&.defs
(\fBCREATE_HOME\fR)\&. Если вы хотите создать домашний каталог для системной учётной записи укажите параметр
\fB\-m\fR\&.
.RE
.PP
\fB\-R\fR, \fB\-\-root\fR\ \&\fIКАТ_CHROOT\fR
.RS 4
Выполнить изменения в каталоге
\fIКАТ_CHROOT\fR
и использовать файлы настройки из каталога
\fIКАТ_CHROOT\fR\&.
.RE
.PP
\fB\-s\fR, \fB\-\-shell\fR\ \&\fIОБОЛОЧКА\fR
.RS 4
Имя регистрационной оболочки пользователя\&. По умолчанию это поле пусто, что вызывает выбор регистрационной оболочки по умолчанию согласно значению переменной
\fBSHELL\fR
из файла
/etc/default/useradd, или по умолчанию используется пустая строка\&.
.RE
.PP
\fB\-u\fR, \fB\-\-uid\fR\ \&\fIUID\fR
.RS 4
Числовое значение идентификатора пользователя (ID)\&. Оно должно быть уникальным, если не используется параметр
\fB\-o\fR\&. Значение должно быть неотрицательным\&. По умолчанию используется наименьшее значение ID большее или равное
\fBUID_MIN\fR
и большее чем у остальных пользователей\&.
.sp
Смотрите также описание
\fB\-r\fR
и
\fBUID_MAX\fR\&.
.RE
.PP
\fB\-U\fR, \fB\-\-user\-group\fR
.RS 4
Создать группу с тем же именем что и у пользователя, и добавить пользователя в эту группу\&.
.sp
Поведение по умолчанию (если не указан параметр
\fB\-g\fR,
\fB\-N\fR
и
\fB\-U\fR) определяется переменной
\fBUSERGROUPS_ENAB\fR
из файла
/etc/login\&.defs\&.
.RE
.PP
\fB\-Z\fR, \fB\-\-selinux\-user\fR\ \&\fISEUSER\fR
.RS 4
Пользователь SELinux для регистрационной оболочки пользователя\&. По умолчанию это поле пусто, что заставляет систему выбрать пользователя SELinux по умолчанию\&.
.RE
.SS "Изменение значений по умолчанию"
.PP
При запуске программы только с параметром
\fB\-D\fR
команда
\fBuseradd\fR
показывает текущие значения по умолчанию\&. Если программа запускается с параметром
\fB\-D\fR
вместе с другими параметрами, то
\fBuseradd\fR
обновляет значения по умолчанию этих указанных параметров\&. Изменяемые параметры:
.PP
\fB\-b\fR, \fB\-\-base\-dir\fR \fIБАЗОВЫЙ_КАТАЛОГ\fR
.RS 4
Начальная часть пути нового домашнего каталога пользователя\&. Имя пользователя будет добавлено в конец
\fIДОМАШНЕГО_КАТАЛОГА\fR
для создания имени нового каталога, если при создании новой учётной записи не указан параметр
\fB\-d\fR\&.
.sp
Этот параметр изменяет переменную
\fBHOME\fR
в файле
/etc/default/useradd\&.
.RE
.PP
\fB\-e\fR, \fB\-\-expiredate\fR \fIДАТА_УСТАРЕВАНИЯ\fR
.RS 4
Дата, когда учётная запись пользователя заблокирована\&.
.sp
Этот параметр изменяет переменную
\fBEXPIRE\fR
в файле
/etc/default/useradd\&.
.RE
.PP
\fB\-f\fR, \fB\-\-inactive\fR\ \&\fIДНЕЙ\fR
.RS 4
Число дней, которые должны пройти после устаревания пароля, перед тем как учётная запись будет заблокирована\&.
.sp
Этот параметр изменяет переменную
\fBINACTIVE\fR
в файле
/etc/default/useradd\&.
.RE
.PP
\fB\-g\fR, \fB\-\-gid\fR\ \&\fIГРУППА\fR
.RS 4
Имя группы или ID новой первичной группы пользователя (если используется
\fB\-N/\-\-no\-user\-group\fR
или когда значение переменной
\fBUSERGROUPS_ENAB\fR
равно
\fIno\fR
(файл
/etc/login\&.defs)\&. Группа с указанным именем должна существовать, а для числового идентификатора группы должна быть соответствующая запись\&.
.sp
Этот параметр изменяет переменную
\fBGROUP\fR
в файле
/etc/default/useradd\&.
.RE
.PP
\fB\-s\fR, \fB\-\-shell\fR\ \&\fIОБОЛОЧКА\fR
.RS 4
Имя новой регистрационной командной оболочки пользователя\&.
.sp
Этот параметр изменяет переменную
\fBSHELL\fR
в файле
/etc/default/useradd\&.
.RE
.SH "ЗАМЕЧАНИЯ"
.PP
Системный администратор сам решает, какие файлы нужно положить в каталог
/etc/skel/
(или в любой другой каталог шаблонов, указанный в
/etc/default/useradd
или в командной строке)\&.
.SH "ПРЕДОСТЕРЕЖЕНИЯ"
.PP
Нельзя добавить пользователя в группу NIS или LDAP\&. Это необходимо делать на соответствующем сервере\&.
.PP
Также, если имя пользователя уже существует во внешней базе данных такой как NIS или LDAP, то
\fBuseradd\fR
не станет создавать учётную запись пользователя\&.
.PP
Имена пользователей должны начинаться со строчной буквы или символа подчёркивания, и должны состоять только из строчных букв, цифр, символов подчёркивания и минус\&. Они могут заканчиваться знаком доллара\&. Это можно описать регулярным выражением: [a\-z_][a\-z0\-9_\-]*[$]?
.PP
Имена пользователей могут быть длиной не более 32 знаков\&.
.SH "НАСТРОЙКА"
.PP
На работу этого инструмента влияют следующие переменные настройки из
/etc/login\&.defs:
.PP
\fBCREATE_HOME\fR (логический)
.RS 4
Определяет, должен ли создаваться по умолчанию домашний каталог для новых пользователей\&.
.sp
Эта переменная не влияет на системных пользователей и может быть переопределена из командной строки\&.
.RE
.PP
\fBGID_MAX\fR (число), \fBGID_MIN\fR (число)
.RS 4
Диапазон идентификаторов групп, используемый в программах
\fBuseradd\fR,
\fBgroupadd\fR
или
\fBnewusers\fR
для создания обычных групп\&.
.sp
Значение по умолчанию для
\fBGID_MIN\fR
(соотв\&.
\fBGID_MAX\fR) равно 1000 (соотв\&. 60000)\&.
.RE
.PP
\fBMAIL_DIR\fR (строка)
.RS 4
Почтовый каталог\&. Данный параметр нужен для управления почтовым ящиком при изменении или удалении учётной записи пользователя\&. Если параметр не задан, то используется значение указанное при сборке\&.
.RE
.PP
\fBMAIL_FILE\fR (строка)
.RS 4
Определяет расположение почтовых файлов пользователя относительно домашнего каталога\&.
.RE
.PP
Переменные
\fBMAIL_DIR\fR
и
\fBMAIL_FILE\fR
используются командами
\fBuseradd\fR,
\fBusermod\fR
и
\fBuserdel\fR
для создания, перемещения или удаления почты пользователя\&.
.PP
Если значение
\fBMAIL_CHECK_ENAB\fR
равно
\fIyes\fR, то они также используются для определения переменной окружения
\fBMAIL\fR\&.
.PP
\fBMAX_MEMBERS_PER_GROUP\fR (число)
.RS 4
Максимальное количество членов в записи о группе\&. При достижения максимума заводится новая запись группы (строка) в
/etc/group
(с тем же именем, паролем и тем же GID)\&.
.sp
Значение по умолчанию равно 0, означающее, что ограничения на количество членов в группе нет\&.
.sp
Данная возможность (разделение группы) позволяет ограничить длину строк в файле групп\&. Это полезно для ограничения длины строк групп NIS в 1024 символа\&.
.sp
Если вам нужно такое ограничение, укажите значение 25\&.
.sp
Замечание: разделение групп поддерживается не всеми инструментами (даже в наборе инструментов Shadow)\&. Вы не должны использовать эту переменную, если вам действительно это ненужно\&.
.RE
.PP
\fBPASS_MAX_DAYS\fR (число)
.RS 4
Максимальное число дней использования пароля\&. Если пароль старее этого числа, то будет запущена процедура смены пароля\&. Если значение не задано, то предполагается значение \-1 (то есть возможность ограничения не используется)\&.
.RE
.PP
\fBPASS_MIN_DAYS\fR (число)
.RS 4
Максимальное число дней между изменениями пароля\&. Любая смена пароля ранее заданного срока выполнена не будет\&. Если значение не задано, то предполагается значение \-1 (то есть возможность ограничения не используется)\&.
.RE
.PP
\fBPASS_WARN_AGE\fR (число)
.RS 4
Число дней за которое начнёт выдаваться предупреждение об устаревании пароля\&. Нулевое значение означает, что предупреждение выдаётся в день устаревания, при отрицательном значении предупреждение выдаваться не будет\&. Если значение не задано, выдача предупреждения отключается\&.
.RE
.PP
\fBSUB_GID_MIN\fR (number), \fBSUB_GID_MAX\fR (number), \fBSUB_GID_COUNT\fR (number)
.RS 4
If
/etc/subuid
exists, the commands
\fBuseradd\fR
and
\fBnewusers\fR
(unless the user already have subordinate group IDs) allocate
\fBSUB_GID_COUNT\fR
unused group IDs from the range
\fBSUB_GID_MIN\fR
to
\fBSUB_GID_MAX\fR
for each new user\&.
.sp
The default values for
\fBSUB_GID_MIN\fR,
\fBSUB_GID_MAX\fR,
\fBSUB_GID_COUNT\fR
are respectively 100000, 600100000 and 10000\&.
.RE
.PP
\fBSUB_UID_MIN\fR (number), \fBSUB_UID_MAX\fR (number), \fBSUB_UID_COUNT\fR (number)
.RS 4
If
/etc/subuid
exists, the commands
\fBuseradd\fR
and
\fBnewusers\fR
(unless the user already have subordinate user IDs) allocate
\fBSUB_UID_COUNT\fR
unused user IDs from the range
\fBSUB_UID_MIN\fR
to
\fBSUB_UID_MAX\fR
for each new user\&.
.sp
The default values for
\fBSUB_UID_MIN\fR,
\fBSUB_UID_MAX\fR,
\fBSUB_UID_COUNT\fR
are respectively 100000, 600100000 and 10000\&.
.RE
.PP
\fBSYS_GID_MAX\fR (число), \fBSYS_GID_MIN\fR (число)
.RS 4
Диапазон идентификаторов групп, используемый в программах
\fBuseradd\fR,
\fBgroupadd\fR
или
\fBnewusers\fR
для создания системных групп\&.
.sp
Значение по умолчанию для
\fBSYS_GID_MIN\fR
(соотв\&.\fBSYS_GID_MAX\fR) равно 101 (соотв\&.
\fBGID_MIN\fR\-1)\&.
.RE
.PP
\fBSYS_UID_MAX\fR (число), \fBSYS_UID_MIN\fR (число)
.RS 4
Диапазон идентификаторов пользователей, используемый в программах
\fBuseradd\fR
или
\fBnewusers\fR
для создания системных пользователей\&.
.sp
Значение по умолчанию для
\fBSYS_UID_MIN\fR
(соотв\&.
\fBSYS_UID_MAX\fR) равно 101 (соотв\&.
\fBUID_MIN\fR\-1)\&.
.RE
.PP
\fBUID_MAX\fR (число), \fBUID_MIN\fR (число)
.RS 4
Диапазон идентификаторов пользователей, используемый в программах
\fBuseradd\fR
или
\fBnewusers\fR
для создания обычных пользователей\&.
.sp
Значение по умолчанию для
\fBUID_MIN\fR
(соотв\&.
\fBUID_MAX\fR) равно 1000 (соотв\&. 60000)\&.
.RE
.PP
\fBUMASK\fR (число)
.RS 4
Задаёт начальное значение маски доступа для создаваемых файлов\&. Если не указано, то маска устанавливается в 022\&.
.sp
Команды
\fBuseradd\fR
и
\fBnewusers\fR
используют эту маску для установки прав доступа к домашнему каталогу, который они создают\&.
.sp
Также она используется программой
\fBlogin\fR
для задания начального значения umask пользователя\&. Заметим, что эта маска может быть переопределена из пользовательской строки GECOS (если установлена переменная
\fBQUOTAS_ENAB\fR) или указанием ограничения с идентификатором
\fIK\fR, в
\fBlimits\fR(5)\&.
.RE
.PP
\fBUSERGROUPS_ENAB\fR (логический)
.RS 4
Включает установку группы битов umask равной битам владельца (пример: 022 \-> 002, 077 \-> 007) для не суперпользователей, если uid равен gid и имя пользователя совпадает с именем первичной группы\&.
.sp
Если значение равно
\fIyes\fR, то
\fBuserdel\fR
удаляет пользовательскую группу, если в ней нет больше членов, а
\fBuseradd\fR
по умолчанию создаёт группу с именем пользователя\&.
.RE
.SH "ФАЙЛЫ"
.PP
/etc/passwd
.RS 4
содержит информацию о пользователях
.RE
.PP
/etc/shadow
.RS 4
содержит защищаемую информацию о пользователях
.RE
.PP
/etc/group
.RS 4
содержит информацию о группах
.RE
.PP
/etc/gshadow
.RS 4
содержит защищаемую информацию о группах
.RE
.PP
/etc/default/useradd
.RS 4
значения по умолчанию для создаваемой учётной записи
.RE
.PP
/etc/skel/
.RS 4
каталог, содержащий файлы по умолчанию
.RE
.PP
/etc/subgid
.RS 4
Per user subordinate group IDs\&.
.RE
.PP
/etc/subuid
.RS 4
Per user subordinate user IDs\&.
.RE
.PP
/etc/login\&.defs
.RS 4
содержит конфигурацию подсистемы теневых паролей
.RE
.SH "ВОЗВРАЩАЕМЫЕ ЗНАЧЕНИЯ"
.PP
Команда
\fBuseradd\fR
завершая работу, возвращает следующие значения:
.PP
\fI0\fR
.RS 4
успешное выполнение
.RE
.PP
\fI1\fR
.RS 4
не удалось изменить файл паролей
.RE
.PP
\fI2\fR
.RS 4
ошибка в параметрах команды
.RE
.PP
\fI3\fR
.RS 4
недопустимое значение параметра
.RE
.PP
\fI4\fR
.RS 4
такой UID уже существует (и не задан параметр
\fB\-o\fR)
.RE
.PP
\fI6\fR
.RS 4
указанная группа не существует
.RE
.PP
\fI9\fR
.RS 4
имя пользователя уже существует
.RE
.PP
\fI10\fR
.RS 4
не удалось изменить файл групп
.RE
.PP
\fI12\fR
.RS 4
не удалось создать домашний каталог
.RE
.PP
\fI14\fR
.RS 4
can\*(Aqt update SELinux user mapping
.RE
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBchfn\fR(1),
\fBchsh\fR(1),
\fBpasswd\fR(1),
\fBcrypt\fR(3),
\fBgroupadd\fR(8),
\fBgroupdel\fR(8),
\fBgroupmod\fR(8),
\fBlogin.defs\fR(5),
\fBnewusers\fR(8),
\fBsubgid\fR(5), \fBsubuid\fR(5),\fBuserdel\fR(8),
\fBusermod\fR(8)\&.
