'\" t
.\"     Title: userdel
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 05/09/2014
.\"    Manual: Команды управления системой
.\"    Source: shadow-utils 4.2
.\"  Language: Russian
.\"
.TH "userdel" "8" "05/09/2014" "shadow\-utils 4\&.2" "Команды управления системой"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВАНИЕ"
userdel \- удаляет учётную запись и файлы пользователя
.SH "СИНТАКСИС"
.HP \w'\fBuserdel\fR\ 'u
\fBuserdel\fR [параметры] \fIУЧЁТНАЯ_ЗАПИСЬ\fR
.SH "ОПИСАНИЕ"
.PP
Команда
\fBuserdel\fR
изменяет системные файлы учётных записей, удаляя все записи, относящиеся к указанному
\fIимени_пользователя\fR\&. Заданная учётная запись должна существовать\&.
.SH "ПАРАМЕТРЫ"
.PP
Параметры команды
\fBuserdel\fR:
.PP
\fB\-f\fR, \fB\-\-force\fR
.RS 4
С этим параметром учётная запись будет удалена, даже если пользователь в этот момент работает в системе\&. Он также заставляет
\fBuserdel\fR
удалить домашний каталог пользователя и почтовый ящик, даже если другой пользователь использует тот же домашний каталог или если почтовый ящик не принадлежит данному пользователю\&. Если значение
\fBUSERGROUPS_ENAB\fR
равно
\fIyes\fR
в файле
/etc/login\&.defs
и если существует группа с именем удаляемого пользователя, то это группа будет удалена, даже если она всё ещё является первичной группой другого пользователя\&.
.sp
\fIЗамечание:\fR
Этот параметр опасно использовать; он может привести систему в нерабочее состояние\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Показать краткую справку и закончить работу\&.
.RE
.PP
\fB\-r\fR, \fB\-\-remove\fR
.RS 4
Файлы в домашнем каталоге пользователя будут удалены вместе с самим домашним каталогом и почтовым ящиком\&. Пользовательские файлы, расположенные в других файловых системах, нужно искать и удалять вручную\&.
.sp
Имя файла почтового ящика задаётся переменной
\fBMAIL_DIR\fR
в файле
login\&.defs\&.
.RE
.PP
\fB\-R\fR, \fB\-\-root\fR\ \&\fIКАТ_CHROOT\fR
.RS 4
Выполнить изменения в каталоге
\fIКАТ_CHROOT\fR
и использовать файлы настройки из каталога
\fIКАТ_CHROOT\fR\&.
.RE
.PP
\fB\-Z\fR, \fB\-\-selinux\-user\fR
.RS 4
Удаляет все пользовательские сопоставления SELinux для учётной записи пользователя\&.
.RE
.SH "НАСТРОЙКА"
.PP
На работу этого инструмента влияют следующие переменные настройки из
/etc/login\&.defs:
.PP
\fBMAIL_DIR\fR (строка)
.RS 4
Почтовый каталог\&. Данный параметр нужен для управления почтовым ящиком при изменении или удалении учётной записи пользователя\&. Если параметр не задан, то используется значение указанное при сборке\&.
.RE
.PP
\fBMAIL_FILE\fR (строка)
.RS 4
Определяет расположение почтовых файлов пользователя относительно домашнего каталога\&.
.RE
.PP
Переменные
\fBMAIL_DIR\fR
и
\fBMAIL_FILE\fR
используются командами
\fBuseradd\fR,
\fBusermod\fR
и
\fBuserdel\fR
для создания, перемещения или удаления почты пользователя\&.
.PP
Если значение
\fBMAIL_CHECK_ENAB\fR
равно
\fIyes\fR, то они также используются для определения переменной окружения
\fBMAIL\fR\&.
.PP
\fBMAX_MEMBERS_PER_GROUP\fR (число)
.RS 4
Максимальное количество членов в записи о группе\&. При достижения максимума заводится новая запись группы (строка) в
/etc/group
(с тем же именем, паролем и тем же GID)\&.
.sp
Значение по умолчанию равно 0, означающее, что ограничения на количество членов в группе нет\&.
.sp
Данная возможность (разделение группы) позволяет ограничить длину строк в файле групп\&. Это полезно для ограничения длины строк групп NIS в 1024 символа\&.
.sp
Если вам нужно такое ограничение, укажите значение 25\&.
.sp
Замечание: разделение групп поддерживается не всеми инструментами (даже в наборе инструментов Shadow)\&. Вы не должны использовать эту переменную, если вам действительно это ненужно\&.
.RE
.PP
\fBUSERDEL_CMD\fR (строка)
.RS 4
Определяет программу, которая будет запущена при удалении пользователя\&. Она должна удалять любые задания at/cron/печати удаляемого пользователя (передаётся в качестве первого аргумента)\&.
.sp
Возвращаемый сценарием код завершения не учитывается\&.
.sp
Вот простой сценарий, который удаляет задания печати, cron и at:
.sp
.if n \{\
.RS 4
.\}
.nf
#! /bin/sh

# проверить все необходимые параметры
if [ $# != 1 ]; then
	echo "Использование: $0 имя_пользователя"
	exit 1
fi

# удалить задания cron
crontab \-r \-u $1

# удалить задания at
# Заметим, что это удалит все задания с указанным UID,
# даже если он используется для другой учётной записи\&.
AT_SPOOL_DIR=/var/spool/cron/atjobs
find $AT_SPOOL_DIR \-name "[^\&.]*" \-type f \-user $1 \-delete \e;

# удалить задания печати
lprm $1

# всё
exit 0
      
.fi
.if n \{\
.RE
.\}
.RE
.PP
\fBUSERGROUPS_ENAB\fR (логический)
.RS 4
Включает установку группы битов umask равной битам владельца (пример: 022 \-> 002, 077 \-> 007) для не суперпользователей, если uid равен gid и имя пользователя совпадает с именем первичной группы\&.
.sp
Если значение равно
\fIyes\fR, то
\fBuserdel\fR
удаляет пользовательскую группу, если в ней нет больше членов, а
\fBuseradd\fR
по умолчанию создаёт группу с именем пользователя\&.
.RE
.SH "ФАЙЛЫ"
.PP
/etc/group
.RS 4
содержит информацию о группах
.RE
.PP
/etc/login\&.defs
.RS 4
содержит конфигурацию подсистемы теневых паролей
.RE
.PP
/etc/passwd
.RS 4
содержит информацию о пользователях
.RE
.PP
/etc/shadow
.RS 4
содержит защищаемую информацию о пользователях
.RE
.PP
/etc/subgid
.RS 4
Per user subordinate group IDs\&.
.RE
.PP
/etc/subuid
.RS 4
Per user subordinate user IDs\&.
.RE
.SH "ВОЗВРАЩАЕМЫЕ ЗНАЧЕНИЯ"
.PP
Команда
\fBuserdel\fR
завершая работу, возвращает следующие значения:
.PP
\fI0\fR
.RS 4
успешное выполнение
.RE
.PP
\fI1\fR
.RS 4
не удалось изменить файл паролей
.RE
.PP
\fI2\fR
.RS 4
ошибка в параметрах команды
.RE
.PP
\fI6\fR
.RS 4
указанный пользователь не существует
.RE
.PP
\fI8\fR
.RS 4
пользователь сейчас работает в системе
.RE
.PP
\fI10\fR
.RS 4
не удалось изменить файл групп
.RE
.PP
\fI12\fR
.RS 4
не удалось удалить домашний каталог
.RE
.SH "ПРЕДОСТЕРЕЖЕНИЯ"
.PP
Команда
\fBuserdel\fR
не позволит удалить учётную запись, если есть запущенные процессы, принадлежащие данной учётной записи\&. В этом случае вы можете удалить эти процессы или заблокировать пароль пользователя или учётную запись, а затем удалить учётную запись\&. Если указан параметр
\fB\-f\fR, то учётная запись будет удалена несмотря ни на что\&.
.PP
Вы должны вручную проверить все файловые системы, чтобы убедиться, что не осталось файлов, принадлежащих этому пользователю\&.
.PP
Нельзя удалить NIS атрибуты клиента NIS\&. Это необходимо сделать на NIS сервере\&.
.PP
Если значение переменной
\fBUSERGROUPS_ENAB\fR
равно
\fIyes\fR
в файле
/etc/login\&.defs, то
\fBuserdel\fR
удалит группу с именем как у пользователя\&. Чтобы избежать рассогласованности в базах данных групп и паролей,
\fBuserdel\fR
проверит, что данная группа не используется в качестве первичной для другого пользователя, и выдаст предупреждение без удаления, если такое случится\&. Параметр
\fB\-f\fR
поможет удалить группу в любом случае\&.
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBchfn\fR(1),
\fBchsh\fR(1),
\fBpasswd\fR(1),
\fBlogin.defs\fR(5),
\fBgpasswd\fR(8),
\fBgroupadd\fR(8),
\fBgroupdel\fR(8),
\fBgroupmod\fR(8),
\fBsubgid\fR(5), \fBsubuid\fR(5),\fBuseradd\fR(8),
\fBusermod\fR(8)\&.
