'\" t
.\"     Title: vipw
.\"    Author: Marek Micha\(/lkiewicz
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 05/09/2014
.\"    Manual: Команды управления системой
.\"    Source: shadow-utils 4.2
.\"  Language: Russian
.\"
.TH "vipw" "8" "05/09/2014" "shadow\-utils 4\&.2" "Команды управления системой"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВАНИЕ"
vipw, vigr \- позволяют редактировать файлы паролей, групп, теневых паролей пользователей или групп\&.
.SH "СИНТАКСИС"
.HP \w'\fBvipw\fR\ 'u
\fBvipw\fR [\fIпараметры\fR]
.HP \w'\fBvigr\fR\ 'u
\fBvigr\fR [\fIпараметры\fR]
.SH "ОПИСАНИЕ"
.PP
С помощью программ
\fBvipw\fR
и
\fBvigr\fR
можно изменять файлы
/etc/passwd
и
/etc/group, соответственно\&. Если указан параметр
\fB\-s\fR, то будут редактироваться теневые версии этих файлов,
/etc/shadow
и
/etc/gshadow, соответственно\&. На время работы программы устанавливают блокировку для предотвращения повреждения файла\&. При выборе редактора программы сначала проверяют переменную окружения
\fB$VISUAL\fR, затем
\fB$EDITOR\fR, и если ничего не найдено, запускают стандартный редактор
\fBvi\fR(1)\&.
.SH "ПАРАМЕТРЫ"
.PP
Параметры команд
\fBvipw\fR
и
\fBvigr\fR:
.PP
\fB\-g\fR, \fB\-\-group\fR
.RS 4
Редактировать базу данных групп\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Показать краткую справку и закончить работу\&.
.RE
.PP
\fB\-p\fR, \fB\-\-passwd\fR
.RS 4
Редактировать базу данных passwd\&.
.RE
.PP
\fB\-q\fR, \fB\-\-quiet\fR
.RS 4
Не выводить сообщений при работе\&.
.RE
.PP
\fB\-R\fR, \fB\-\-root\fR\ \&\fIКАТ_CHROOT\fR
.RS 4
Выполнить изменения в каталоге
\fIКАТ_CHROOT\fR
и использовать файлы настройки из каталога
\fIКАТ_CHROOT\fR\&.
.RE
.PP
\fB\-s\fR, \fB\-\-shadow\fR
.RS 4
Редактировать базу данных shadow или gshadow\&.
.RE
.SH "ОКРУЖЕНИЕ"
.PP
\fBVISUAL\fR
.RS 4
Редактор, который будет вызван\&.
.RE
.PP
\fBEDITOR\fR
.RS 4
Редактор, который будет вызван, если не задана переменная
\fBVISUAL\fR\&.
.RE
.SH "ФАЙЛЫ"
.PP
/etc/group
.RS 4
содержит информацию о группах
.RE
.PP
/etc/gshadow
.RS 4
содержит защищаемую информацию о группах
.RE
.PP
/etc/passwd
.RS 4
содержит информацию о пользователях
.RE
.PP
/etc/shadow
.RS 4
содержит защищаемую информацию о пользователях
.RE
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBvi\fR(1),
\fBgroup\fR(5),
\fBgshadow\fR(5),
\fBpasswd\fR(5), ,
\fBshadow\fR(5)\&.
