'\" t
.\"     Title: su
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 09/05/2014
.\"    Manual: Commandes utilisateur
.\"    Source: shadow-utils 4.2
.\"  Language: French
.\"
.TH "SU" "1" "09/05/2014" "shadow\-utils 4\&.2" "Commandes utilisateur"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NOM"
su \- Changer d\*(Aqidentifiant d\*(Aqutilisateur ou devenir superutilisateur
.SH "SYNOPSIS"
.HP \w'\fBsu\fR\ 'u
\fBsu\fR [\fIoptions\fR] [\fInom_utilisateur\fR]
.SH "DESCRIPTION"
.PP
La commande
\fBsu\fR
permet de devenir un autre utilisateur pour la dur\('ee d\*(Aqune session\&. Invoqu\('e sans nom d\*(Aq\fButilisateur\fR, le comportement par d\('efaut de
\fBsu\fRest de devenir superutilisateur\&. Le param\(`etre optionnel
\fB\-\fR
permet d\*(Aqobtenir un environnement similaire \(`a celui que l\*(Aqutilisateur aurait obtenu lors d\*(Aqune connexion directe\&.
.PP
Des param\(`etres suppl\('ementaires peuvent \(^etre fournis apr\(`es le nom de l\*(Aqutilisateur\&. Dans ce cas, ils sont donn\('es \(`a l\*(Aqinterpr\('eteur de commandes de connexion de l\*(Aqutilisateur\&. En particulier, le param\(`etre \(Fo\ \&\fB\-c\fR\ \&\(Fc consid\(`ere que le param\(`etre suivant est une commande pour la plupart des interpr\('eteurs de commandes\&. La commande sera ex\('ecut\('ee par l\*(Aqinterpr\('eteur indiqu\('e dans
/etc/passwd
pour l\*(Aqutilisateur cible\&.
.PP
Vous pouvez utiliser le param\(`etre
\fB\-\-\fR
pour s\('eparer les options de
\fBsu\fR
des param\(`etres fournis par l\*(Aqinterpr\('eteur de commandes\&.
.PP
Un mot de passe sera demand\('e \(`a l\*(Aqutilisateur, si n\('ecessaire\&. Les mots de passe incorrects produisent un message d\*(Aqerreur\&. Toutes les tentatives, r\('eussies ou non, sont enregistr\('ees afin de d\('etecter tout abus du syst\(`eme\&.
.PP
L\*(Aqenvironnement actuel est fourni au nouvel interpr\('eteur de commandes\&. La valeur de
\fB$PATH\fR
est r\('einitialis\('ee \(`a
/bin:/usr/bin
pour les utilisateurs normaux, ou \(`a
\fI/sbin:/bin:/usr/sbin:/usr/bin\fR
pour le superutilisateur\&. Ce comportement peut \(^etre modifi\('e avec les param\(`etres
\fIENV_PATH\fR
et
\fIENV_SUPATH\fR
dans
/etc/login\&.defs\&.
.PP
Une connexion \(`a un sous\-syst\(`eme est indiqu\('ee par la pr\('esence d\*(Aqun \(Fo\ \&*\ \&\(Fc comme premier caract\(`ere de l\*(Aqinterpr\('eteur de commandes initial\&. Le r\('epertoire personnel sera utilis\('e comme racine d\*(Aqun nouveau syst\(`eme de fichiers dans lequel l\*(Aqutilisateur sera connect\('e\&.
.SH "OPTIONS"
.PP
Les options applicables \(`a la commande
\fBsu\fR
sont\ \&:
.PP
\fB\-c\fR, \fB\-\-command\fR\ \&\fICOMMAND\fR
.RS 4
Indiquer une commande qui sera invoqu\('ee par l\*(Aqinterpr\('eteur de commandes en utilisant son option
\fB\-c\fR
.sp
The executed command will have no controlling terminal\&. This option cannot be used to execute interactive programs which need a controlling TTY\&.
.RE
.PP
\fB\-\fR, \fB\-l\fR, \fB\-\-login\fR
.RS 4
Fournir \(`a l\*(Aqutilisateur un environnement similaire \(`a celui qu\*(Aqil aurait obtenu s\*(Aqil s\*(Aq\('etait connect\('e directement\&.
.sp
When
\fB\-\fR
is used, it must be specified before any
\fBusername\fR\&. For portability it is recommended to use it as last option, before any
\fBusername\fR\&. The other forms (\fB\-l\fR
and
\fB\-\-login\fR) do not have this restriction\&.
.RE
.PP
\fB\-s\fR, \fB\-\-shell\fR\ \&\fISHELL\fR
.RS 4
Interpr\('eteur de commande devant \(^etre appel\('e\&.
.sp
L\*(Aqinterpr\('eteur de commandes \(`a appeler est choisi parmi (le choix de plus haute priorit\('e en t\(^ete)\ \&:
.PP
.RS 4
Interpr\('eteur de commande indiqu\('e par \-\-shell\&.
.RE
.PP
.RS 4
Si
\fB\-\-preserve\-environment\fR
est utilis\('e, l\*(Aqinterpr\('eteur de commandes indiqu\('e par la variable d\*(Aqenvironnement
\fB$SHELL\fR
sera utilis\('e\&.
.RE
.PP
.RS 4
Interpr\('eteur de commandes indiqu\('e dans
/etc/passwd
pour l\*(Aqutilisateur cible\&.
.RE
.PP
.RS 4
/bin/sh
si aucun interpr\('eteur de commandes ne peut \(^etre trouv\('e par l\*(Aqune des m\('ethodes ci\-dessus\&.
.RE
.sp
Si l\*(Aqutilisateur cible poss\(`ede un interpr\('eteur de commande restreint (par exemple, le champ de l\*(Aqinterpr\('eteur de commande dans
/etc/passwd
n\*(Aqest pas renseign\('e dans
/etc/shells), alors, ni l\*(Aqoption
\fB\-\-shell\fR
ni la variable d\*(Aqenvironnement
\fB$SHELL\fR
ne seront prises en compte \(`a moins que
\fBsu\fR
ne soit appel\('e par le superutilisateur\&.
.RE
.PP
\fB\-m\fR, \fB\-p\fR, \fB\-\-preserve\-environment\fR
.RS 4
Pr\('eserver l\*(Aqenvironnement actuel, sauf pour\ \&:
.PP
\fB$PATH\fR
.RS 4
r\('einitialise suivant les options
\fBENV_PATH\fR
ou
\fBENV_SUPATH\fR
dans
/etc/login\&.defs
(voir ci\-dessous)\ \&:
.RE
.PP
\fB$IFS\fR
.RS 4
r\('einitialise \(`a
\(Fo\ \&<space><tab><newline>\ \&\(Fc, s\*(Aqil a \('et\('e d\('efini\&.
.RE
.sp
Si l\*(Aqutilisateur cible poss\(`ede un interpr\('eteur de commandes restreint, cette option n\*(Aqa aucun effet (\(`a moins que
\fBsu\fR
ne soit appel\('e par le superutilisateur)\&.
.sp
Notez que le comportement par d\('efaut pour l\*(Aqenvironnement est le suivant\ \&:
.PP
.RS 4
Les variables d\*(Aqenvironnement
\fB$HOME\fR,
\fB$SHELL\fR,
\fB$USER\fR,
\fB$LOGNAME\fR,
\fB$PATH\fR
et
\fB$IFS\fR
sont r\('einitialis\('ees\&.
.RE
.PP
.RS 4
Si
\fB\-\-login\fR
n\*(Aqest pas utilis\('ee, l\*(Aqenvironnement est copi\('e sauf pour les variables ci\-dessus\&.
.RE
.PP
.RS 4
Si
\fB\-\-login\fR
est utilis\('ee, les variables d\*(Aqenvironnement
\fB$TERM\fR,
\fB$COLORTERM\fR,
\fB$DISPLAY\fR
et
\fB$XAUTHORITY\fR
sont copi\('ees si elles ont \('et\('e d\('efinies\&.
.RE
.PP
.RS 4
Si
\fB\-\-login\fR
est utilis\('ee, les variables d\*(Aqenvironnement
\fB$TZ\fR,
\fB$HZ\fR
et
\fB$MAIL\fR
sont configur\('ees en accord avec les options
\fBENV_TZ\fR,
\fBENV_HZ\fR,
\fBMAIL_DIR\fR
et
\fBMAIL_FILE\fR
de
/etc/login\&.defs
(voir ci\-dessous)\&.
.RE
.PP
.RS 4
Si
\fB\-\-login\fR
est utilis\('ee, les autres variables d\*(Aqenvironnement peuvent \(^etre configur\('ees par le fichier
\fBENVIRON_FILE\fR
(voir ci\-dessous)\&.
.RE
.RE
.SH "AVERTISSEMENTS"
.PP
Cette version de
\fBsu\fR
a de nombreuses options de compilation\&. Seules certaines d\*(Aqentre elles peuvent avoir \('et\('e activ\('ees sur votre site\&.
.SH "CONFIGURATION"
.PP
Les variables de configuration suivantes dans
/etc/login\&.defs
modifient le comportement de cet outil\ \&:
.PP
\fBCONSOLE\fR (cha\(^ine de caract\(`eres)
.RS 4
Si d\('efinie, soit un chemin complet du fichier contenant les noms de p\('eriph\('eriques (un par ligne), soit une liste de noms du p\('eriph\('erique d\('elimit\('ee par des \(Fo\ \&:\ \&\(Fc\&. Les connexions d\*(Aqun administrateur ne seront autoris\('ees que depuis ces p\('eriph\('eriques\&.
.sp
S\*(Aqil n\*(Aqest pas d\('efini, root pourra se connecter depuis n\*(Aqimporte quel p\('eriph\('erique\&.
.sp
Le p\('eriph\('erique doit \(^etre pr\('ecis\('e sans le pr\('efixe /dev/\&.
.RE
.PP
\fBCONSOLE_GROUPS\fR (cha\(^ine de caract\(`eres)
.RS 4
Une liste de groupes \(`a rajouter aux groupes suppl\('ementaires de l\*(Aqutilisateur lors d\*(Aqune connexion sur une console (d\('etermin\('e par le param\(`etre CONSOLE)\&. Par d\('efaut, aucun groupe n\*(Aqest ajout\('e\&.

\(`A utiliser avec pr\('ecaution\ \&: il est possible que les utilisateurs aient un acc\(`es permanent \(`a ces groupes, et cela m\(^eme s\*(Aqils ne sont pas connect\('es sur la console\&.
.RE
.PP
\fBDEFAULT_HOME\fR (bool\('een)
.RS 4
Indiquer si la connexion est permise si on ne peut pas acc\('eder au r\('epertoire personnel\&. Le r\('eglage par d\('efaut est \(Fo\ \&no\ \&\(Fc\&.
.sp
Si elle est configur\('ee \(`a
\fIyes\fR, l\*(Aqutilisateur va se connecter dans le r\('epertoire racine (/) s\*(Aqil n\*(Aqest pas possible d\*(Aqacc\('eder \(`a son r\('epertoire personnel\&.
.RE
.PP
\fBENV_HZ\fR (cha\(^ine de caract\(`eres)
.RS 4
Si d\('efinie, sera utilis\('ee pour d\('efinir la variable d\*(Aqenvironnement HZ lorsqu\*(Aqun utilisateur se connecte\&. La valeur doit \(^etre pr\('ec\('ed\('ee par
\fIHZ=\fR\&. Une valeur commune sur Linux est
\fIHZ=100\fR\&.
.RE
.PP
\fBENVIRON_FILE\fR (cha\(^ine de caract\(`eres)
.RS 4
Si ce fichier existe et est lisible, l\*(Aqenvironnement de connexion sera lu \(`a\ \& partir de lui\&. Chaque ligne doit \(^etre sous la forme nom=valeur\&.
.sp
Les lignes commen\(,cant par un \(Fo\ \&#\ \&\(Fc sont consid\('er\('ees comme des commentaires, et sont ignor\('ees\&.
.RE
.PP
\fBENV_PATH\fR (cha\(^ine de caract\(`eres)
.RS 4
Si d\('efinie, sera utilis\('ee pour d\('efinir la variable d\*(Aqenvironnement PATH quand un utilisateur ordinaire se connecte\&. La valeur est une liste de chemins s\('epar\('es par des deux points (par exemple
\fI/bin:/usr/bin\fR) et peut \(^etre pr\('ec\('ed\('ee par
\fIPATH=\fR\&. La valeur par d\('efaut est
\fIPATH=/bin:/usr/bin\fR\&.
.RE
.PP
\fBENV_SUPATH\fR (cha\(^ine de caract\(`eres)
.RS 4
Si d\('efinie, sera utilis\('ee pour d\('efinir la variable d\*(Aqenvironnement PATH quand le super\-utilisateur se connecte\&. La valeur est une liste de chemins s\('epar\('es par deux points (par exemple
\fI/sbin:/bin:/usr/sbin:/usr/bin\fR) et peut \(^etre pr\('ec\('ed\('ee par
\fIPATH=\fR\&. La valeur par d\('efaut est
\fIPATH=/sbin:/bin:/usr/sbin:/usr/bin\fR\&.
.RE
.PP
\fBENV_TZ\fR (cha\(^ine de caract\(`eres)
.RS 4
Si d\('efinie, sera utilis\('ee pour d\('efinir la variable d\*(Aqenvironnement TZ quand un utilisateur se connecte\&. La valeur peut \(^etre le nom d\*(Aqun fuseau horaire pr\('ec\('ed\('e par
\fITZ=\fR
(par exemple
\fITZ=CST6CDT\fR), ou le chemin complet vers le fichier contenant la sp\('ecification du fuseau horaire (par exemple
/etc/tzname)\&.
.sp
Si un chemin complet est sp\('ecifi\('e mais que le fichier n\*(Aqexiste pas ou ne peut pas \(^etre lu, la valeur par d\('efaut utilis\('ee est
\fITZ=CST6CDT\fR\&.
.RE
.PP
\fBLOGIN_STRING\fR (cha\(^ine de caract\(`eres)
.RS 4
La cha\(^ine de caract\(`eres utilis\('ee pour l\*(Aqinvite de mot de passe\&. La valeur par d\('efaut est d\*(Aqutiliser "Password: " (\(Fo\ \&mot de passe\ \&:\ \&\(Fc), ou une traduction de cette cha\(^ine\&. Si vous d\('efinissez cette variable, l\*(Aqinvite ne sera pas traduite\&.
.sp
Si la cha\(^ine contient
\fI%s\fR, ces caract\(`eres seront remplac\('es par le nom de l\*(Aqutilisateur\&.
.RE
.PP
\fBMAIL_CHECK_ENAB\fR (bool\('een)
.RS 4
Activer le contr\(^ole et l\*(Aqaffichage du statut de la bo\(^ite aux lettres durant la connexion\&.
.sp
Vous devriez le d\('esactiver si les fichiers de d\('emarrage de l\*(Aqinterpr\('eteur de commandes v\('erifient d\('ej\(`a la pr\('esence de courriers (\(Fo\ \&mail \-e\ \&\(Fc ou \('equivalent)\&.
.RE
.PP
\fBMAIL_DIR\fR (cha\(^ine de caract\(`eres)
.RS 4
R\('epertoire d\*(Aqattente des courriels (\(Fo\ \&mail spool directory\ \&\(Fc)\&. Ce param\(`etre est n\('ecessaire pour manipuler les bo\(^ites \(`a lettres lorsque le compte d\*(Aqun utilisateur est modifi\('e ou supprim\('e\&. S\*(Aqil n\*(Aqest pas sp\('ecifi\('e, une valeur par d\('efaut d\('efinie \(`a la compilation est utilis\('ee\&.
.RE
.PP
\fBMAIL_FILE\fR (cha\(^ine de caract\(`eres)
.RS 4
D\('efinir l\*(Aqemplacement des bo\(^ites aux lettres des utilisateurs relativement \(`a leur r\('epertoire personnel\&.
.RE
.PP
Les param\(`etres
\fBMAIL_DIR\fR
et
\fBMAIL_FILE\fR
sont utilis\('es par
\fBuseradd\fR,
\fBusermod\fR
et
\fBuserdel\fR
pour cr\('eer, d\('eplacer ou supprimer les bo\(^ites aux lettres des utilisateurs\&.
.PP
Si
\fBMAIL_CHECK_ENAB\fR
est r\('egl\('e sur
\fIyes\fR, ces variables servent \('egalement \(`a d\('efinir la variable d\*(Aqenvironnement
\fBMAIL\fR\&.
.PP
\fBQUOTAS_ENAB\fR (bool\('een)
.RS 4
Activer la mise en place de limites de resources depuis
/etc/limits
et ulimit, umask et niveau nice depuis les champs gecos de passwd\&.
.RE
.PP
\fBSULOG_FILE\fR (cha\(^ine de caract\(`eres)
.RS 4
Si d\('efinie, les activit\('es de su seront enregistr\('ees dans le fichier\&.
.RE
.PP
\fBSU_NAME\fR (cha\(^ine de caract\(`eres)
.RS 4
Si d\('efinie, le nom de la commande \(`a afficher lorsque \(Fo\ \&su \-\ \&\(Fc est ex\('ecut\('ee\&. Par exemple, si elle est d\('efinie \(`a \(Fo\ \&su\ \&\(Fc alors un \(Fo\ \&ps\ \&\(Fc affichera la commande comme \(Fo\ \&\-su\ \&\(Fc\&. Si non d\('efinie, alors \(Fo\ \&ps\ \&\(Fc affichera le nom du shell qui sera en fait ex\('ecut\('e, par exemple quelque chose comme \(Fo\ \&\-sh\ \&\(Fc\&.
.RE
.PP
\fBSU_WHEEL_ONLY\fR (bool\('een)
.RS 4
Si
\fIyes\fR, l\*(Aqutilisateur doit faire partie des membres du groupe avec le premier gid 0 dans
/etc/group
(appel\('e
\fIroot\fR
sur la plupart des syst\(`emes Linux) pour \(^etre capable de
\fBsu\fR
vers des comptes \(`a uid 0\&. Si ce groupe n\*(Aqexiste pas ou est vide, personne ne pourra
\fBsu\fR
vers un uid 0\&.
.RE
.PP
\fBSYSLOG_SU_ENAB\fR (bool\('een)
.RS 4
Activer la journalisation \(Fo\ \&syslog\ \&\(Fc de l\*(Aqactivit\('e de
\fBsu\fR
\- en plus de la journalisation sulog\&.
.RE
.PP
\fBUSERGROUPS_ENAB\fR (bool\('een)
.RS 4
Activer la mise en place de bits de masque de groupe (\(Fo\ \&umask group bits\ \&\(Fc) identiques \(`a ceux du propri\('etaire (exemple\ \&: 022 \-> 002, 077 \-> 007) pour les utilisateurs non privil\('egi\('es, si l\*(AqUID est identique au GID et que l\*(Aqidentifiant de connexion est identique au groupe principal\&.
.sp
Si cette variable est configur\('ee \(`a
\fIyes\fR,
\fBuserdel\fR
supprimera le groupe de l\*(Aqutilisateur s\*(Aqil ne contient pas d\*(Aqautres membres, et
\fBuseradd\fR
cr\('eera par d\('efaut un groupe portant le nom de l\*(Aqutilisateur\&.
.RE
.SH "FICHIERS"
.PP
/etc/passwd
.RS 4
Informations sur les comptes des utilisateurs\&.
.RE
.PP
/etc/shadow
.RS 4
Informations s\('ecuris\('ees sur les comptes utilisateurs\&.
.RE
.PP
/etc/login\&.defs
.RS 4
Configuration de la suite des mots de passe cach\('es \(Fo\ \&shadow password\ \&\(Fc\&.
.RE
.SH "VALEURS DE RETOUR"
.PP
En cas de succ\(`es,
\fBsu\fR
renvoie la valeur de sortie de la commande qu\*(Aqil a ex\('ecut\('ee\&.
.PP
Si cette commande s\*(Aqest termin\('ee par un signal,
\fBsu\fR
y ajoute 128 et renvoie le r\('esultat\&.
.PP
Si
\fBsu\fR
doit tuer la commande (parce qu\*(Aqil a \('et\('e demand\('e de terminer et que la commande ne s\*(Aqest pas termin\('ee \(`a temps),
\fBsu\fR
renvoie 255\&.
.PP
Certaines valeurs de retour de
\fBsu\fR
sont ind\('ependantes de la commande ex\('ecut\('ee\ \&:
.PP
\fI0\fR
.RS 4
succ\(`es (\fB\-\-help\fR
uniquement)
.RE
.PP
\fI1\fR
.RS 4
\('Echec syst\(`eme ou d\*(Aqauthentification
.RE
.PP
\fI126\fR
.RS 4
La commande demand\('ee n\*(Aqa pas \('et\('e trouv\('ee\&.
.RE
.PP
\fI127\fR
.RS 4
La commande demand\('ee n\*(Aqa pas pu \(^etre ex\('ecut\('ee\&.
.RE
.SH "VOIR AUSSI"
.PP
\fBlogin\fR(1),
\fBlogin.defs\fR(5),
\fBsg\fR(1),
\fBsh\fR(1)\&.
