'\" t
.\"     Title: expiry
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 05/09/2014
.\"    Manual: Polecenia użytkownik\('ow
.\"    Source: shadow-utils 4.2
.\"  Language: Polish
.\"
.TH "EXPIRY" "1" "05/09/2014" "shadow\-utils 4\&.2" "Polecenia użytkownik\('ow"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAZWA"
expiry \- sprawdzenie ważności i wymuszenie zmiany has\(/la
.SH "STRESZCZENIE"
.HP \w'\fBexpiry\fR\ 'u
\fBexpiry\fR \fIoption\fR
.SH "OPIS"
.PP
Polecenie
\fBexpiry\fR
sprawdza (\fB\-c\fR), kiedy wygaśnie aktualne has\(/lo oraz wymusza (\fB\-f\fR) lub wymusza jego zmianę\&.Może ono być wywo\(/lywane jako zwyk\(/le polecenie przez użytkownika\&.
.SH "OPCJE"
.PP
The options which apply to the
\fBexpiry\fR
command are:
.PP
\fB\-c\fR, \fB\-\-check\fR
.RS 4
Check the password expiration of the current user\&.
.RE
.PP
\fB\-f\fR, \fB\-\-force\fR
.RS 4
Force a password change if the current user has an expired password\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Wyświetlenie komunikatu pomocy i zakończenie dzia\(/lania\&.
.RE
.SH "PLIKI"
.PP
/etc/passwd
.RS 4
Informacja o kontach użytkownik\('ow\&.
.RE
.PP
/etc/shadow
.RS 4
Informacje chronione o użytkownikach\&.
.RE
.SH "ZOBACZ TAKŻE"
.PP
\fBpasswd\fR(5),
\fBshadow\fR(5)\&.
