'\" t
.\"     Title: gshadow
.\"    Author: Nicolas Fran\(,cois <nicolas.francois@centraliens.net>
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 05/09/2014
.\"    Manual: Форматы файлов
.\"    Source: shadow-utils 4.2
.\"  Language: Russian
.\"
.TH "gshadow" "5" "05/09/2014" "shadow\-utils 4\&.2" "Форматы файлов"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВАНИЕ"
gshadow \- файл с защищаемой информацией о группах
.SH "ОПИСАНИЕ"
.PP
Файл
/etc/gshadow
содержит защищаемую информацию о группах\&.
.PP
Этот файл должен быть недоступен обычному пользователю, если нужно обеспечить безопасность паролей\&.
.PP
Каждая строка файла содержит поля, отделёнными друг от друга двоеточием:
.PP
\fBимя группы\fR
.RS 4
Должно содержать правильное имя группы, которая существует в системе\&.
.RE
.PP
\fBшифрованный пароль\fR
.RS 4
Подробней о пароле смотрите в справочной странице
\fBcrypt\fR(3)\&.
.sp
Если поле пароля содержит строку, которая не удовлетворяет требованиям
\fBcrypt\fR(3), например содержит ! или *, то пользователь не сможет использовать пароль unix для доступа в группу (а члену группы пароль не нужен)\&.
.sp
Пароль используется, если пользователю, не являющему членом группы, требуются права этой группы (смотрите
\fBnewgrp\fR(1))\&.
.sp
Это поле может быть пустым; в этом случае только члены группы могут пользоваться правами группы\&.
.sp
Поле пароля может начинаться с восклицательного знака, означающего, что пароль заблокирован\&. Оставшиеся символы в строке представляют поле пароля до его блокировки\&.
.sp
Данный пароль заменяет любой пароль, указанный в файле
/etc/group\&.
.RE
.PP
\fBадминистраторы\fR
.RS 4
Список имён пользователей, перечисленных через запятую\&.
.sp
Администраторы могут менять пароль или членство в группе\&.
.sp
Администраторы также имеют те же права, что и члены группы (смотрите далее)\&.
.RE
.PP
\fBчлены\fR
.RS 4
Список имён пользователей, перечисленных через запятую\&.
.sp
Члены могут иметь доступ к группе без ввода пароля\&.
.sp
Вы должны использовать тот же список пользователей что и в
/etc/group\&.
.RE
.SH "ФАЙЛЫ"
.PP
/etc/group
.RS 4
содержит информацию о группах
.RE
.PP
/etc/gshadow
.RS 4
содержит защищаемую информацию о группах
.RE
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBgpasswd\fR(5),
\fBgroup\fR(5),
\fBgrpck\fR(8),
\fBgrpconv\fR(8),
\fBnewgrp\fR(1)\&.
