'\" t
.\"     Title: limits
.\"    Author: Luca Berra
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 05/09/2014
.\"    Manual: Форматы файлов
.\"    Source: shadow-utils 4.2
.\"  Language: Russian
.\"
.TH "limits" "5" "05/09/2014" "shadow\-utils 4\&.2" "Форматы файлов"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВАНИЕ"
limits \- файл контроля ресурсов
.SH "ОПИСАНИЕ"
.PP
В файле
\fIlimits\fR
(по умолчанию
/etc/limits
или определяется значением LIMITS_FILE в файле
config\&.h) описываются ограничения, которые можно изменять\&. Этот файл должен принадлежать суперпользователю и право на чтение должно быть только у суперпользователя\&.
.PP
По умолчанию учётная запись \(Foroot\(Fc ничем не ограничена\&. Фактически, никак нельзя установить ограничения с помощью этой процедуры на учётные записи, имеющие права суперпользователя (учётные записи с UID равным 0)\&.
.PP
Каждая строка описывает ограничение для одного пользователя имеет вид:
.PP
\fIuser СТРОКА_ОГРАНИЧЕНИЙ\fR
.PP
или в виде:
.PP
\fI@group СТРОКА_ОГРАНИЧЕНИЙ\fR
.PP
\fIСТРОКА_ОГРАНИЧЕНИЙ\fR
\(em это строка, в которой указаны сразу несколько ограничений\&. Каждое ограничение состоит из буквенного идентификатора и числового значения\&.
.PP
Допустимые идентификаторы:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
A: максимальное адресное пространство (КБ)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
C: максимальный размер файла core (КБ)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
D: максимальный размер данных (КБ)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
F: максимальный размер файла (КБ)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
K: маска создаваемых файлов, устанавливается с помощью вызова
\fBumask\fR(2)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
I: максимальное значение уступчивости (nice) (0\&.\&.39, преобразуемые в 20\&.\&.\-19)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
L: максимальное число возможных регистраций в системе этого пользователя
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
M: максимальное синхронизируемое адресное пространство памяти (КБ)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
N: максимальное число открытых файлов
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
O: максимальный приоритет реального времени
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
P: приоритет процесса, устанавливается с помощью вызова
\fBsetpriority\fR(2)\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
R: максимальный размер резидентного сегмента (КБ)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
S: максимальный размер стека (КБ)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
T: максимальное время использования процессора (минут)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
U: максимальное число процессов
.RE
.PP
Например, значение
\fIL2D2048N5\fR
допустимо для
\fIСТРОКИ_ОГРАНИЧЕНИЙ\fR\&. Для удобства чтения, следующие записи эквивалентны:
.sp
.if n \{\
.RS 4
.\}
.nf
      username L2D2048N5
      username L2 D2048 N5
    
.fi
.if n \{\
.RE
.\}
.PP
Заметим, что после
\fIusername\fR
оставшаяся часть строки считается строкой ограничений, поэтому комментарии недопустимы\&. Неправильная строка ограничений будет отброшена (не учтена) программой
\fBlogin\fR\&.
.PP
Запись по умолчанию выглядит как username "\fI*\fR"\&. Если у вас есть несколько записей
\fIпо умолчанию\fR
в файле
\fILIMITS_FILE\fR, то будет использоваться последняя\&.
.PP
Ограничения, задаваемые в виде \(Fo\fI@group\fR\(Fc, применяются к членам указанной группы
\fIgroup\fR\&.
.PP
Если для пользователя есть более одной строки ограничений, то учитывается только первая строка\&.
.PP
Если для пользователя не указано ни одной строки, то учитывается последняя строка
\fI@group\fR
с группой, в которую входит пользователь, или последняя строка с ограничениями по умолчанию, если не указано групп, в которые входит пользователь\&.
.PP
Чтобы полностью снять ограничения с пользователя, используется одиночное тире \(Fo\fI\-\fR\(Fc\&.
.PP
Чтобы снять ограничение с пользователя, вместо числового значения ограничения можно использовать одиночное тире \(Fo\fI\-\fR\(Fc\&.
.PP
Также заметьте, что все настройки ограничений делаются ДЛЯ КОНКРЕТНОЙ УЧЁТНОЙ ЗАПИСИ\&. Они не являются глобальными и не постоянны\&. Возможно глобальные ограничения и появятся, но пока это только в планах ;)
.SH "ФАЙЛЫ"
.PP
/etc/limits
.RS 4
.RE
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBlogin\fR(1),
\fBsetpriority\fR(2),
\fBsetrlimit\fR(2)\&.
