'\" t
.\"     Title: login.access
.\"    Author: Marek Micha\(/lkiewicz
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 05/09/2014
.\"    Manual: Форматы файлов
.\"    Source: shadow-utils 4.2
.\"  Language: Russian
.\"
.TH "login\&.access" "5" "05/09/2014" "shadow\-utils 4\&.2" "Форматы файлов"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВАНИЕ"
login.access \- файл контроля доступа в систему
.SH "ОПИСАНИЕ"
.PP
В файле
\fIlogin\&.access\fR
определяются комбинации (пользователь, узел) и/или (пользователь, терминал), которым будет разрешён или запрещён вход в систему\&.
.PP
Когда кто\-то пытается войти в систему выполняется сканирование файла
\fIlogin\&.access\fR
в поисках первой совпадающей записи (пользователь, узел), или в случае не сетевого входа, первой совпадающей записи (пользователь, терминал)\&. Из найденной записи выбирается поле прав доступа, по которому определяется разрешать ли данной учётной записи вход в систему или нет\&.
.PP
Каждая строка таблицы контроля доступа в систему состоит из трёх полей разделённых символом \(Fo:\(Fc и выглядит так:
.PP
\fIправа_доступа\fR:\fIпользователи\fR:\fIисточники\fR
.PP
Первое поле должно содержать символ \(Fo\fI+\fR\(Fc (доступ разрешён) или \(Fo\fI\-\fR\(Fc (доступ запрещён)\&. Второе поле должно содержать имя одной или более учётных записей, имена групп или
\fIALL\fR
(всегда совпадает)\&. Третье поле должно содержать одно или нескольких имён терминалов (для доступа не из сети), имена узлов, доменных имён (начинаются с \(Fo\&.\(Fc), адреса узлов, адреса подсетей (заканчиваются на \(Fo\&.\(Fc),
\fIALL\fR
(всегда совпадает) или
\fILOCAL\fR
(любая строка, не содержащая символа \(Fo\&.\(Fc)\&. Если используется NIS, то также можно использовать @имя_сетевой_группы в шаблонах узлов или именах пользователей\&.
.PP
Оператор
\fIEXCEPT\fR
помогает в написании компактных правил\&.
.PP
Поиск в файле групп производится только когда имя не совпадает с регистрирующимся пользователем\&. Рассматриваются группы только с явно прописанными в них пользователями: программа не принимает во внимание значение первичной группы пользователя\&.
.SH "ФАЙЛЫ"
.PP
/etc/login\&.defs
.RS 4
содержит конфигурацию подсистемы теневых паролей
.RE
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBlogin\fR(1)\&.
