'\" t
.\"     Title: porttime
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 05/09/2014
.\"    Manual: Форматы файлов
.\"    Source: shadow-utils 4.2
.\"  Language: Russian
.\"
.TH "porttime" "5" "05/09/2014" "shadow\-utils 4\&.2" "Форматы файлов"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВАНИЕ"
porttime \- файл с временами доступа к портам
.SH "ОПИСАНИЕ"
.PP
Файл
\fIporttime\fR
содержит список устройств tty, имена пользователей и разрешённое время входа\&.
.PP
Каждая запись состоит из трёх полей, разделённых двоеточиями\&. В первом поле содержится список устройств tty (перечисленных через запятую) или звёздочка, указывающая, что все устройства tty попадают под правило этой записи\&. Во втором поле содержится список имён пользователей (перечисленных через запятую) или звёздочка, указывающая, что все имена пользователей попадают под правило этой записи\&. В третьем поле содержится список (через запятую) допустимого времени работы\&.
.PP
Каждая запись времени доступа состоит из нуля или более дней недели, обозначенных как
\fISu\fR,
\fIMo\fR,
\fITu\fR,
\fIWe\fR,
\fITh\fR,
\fIFr\fR
и
\fISa\fR, а также временем начала и конца, записанного через дефис\&. Сокращение
\fIWk\fR
можно использовать для обозначения периода с понедельника по пятницу, а
\fIAl\fR
обозначает каждый день\&. Если день не задан, то предполагается
\fIAl\fR
в качестве значения по умолчанию\&.
.SH "ПРИМЕРЫ"
.PP
Следующая запись разрешает доступ пользователю
\fBjfh\fR
с любого порта по будням с 9:00 до 17:00\&.
.PP
*:jfh:Wk0900\-1700
.PP
Следующие записи разрешают доступ только пользователям
\fIroot\fR
и
\fIoper\fR
с
/dev/console
в любое время\&. Это показывает, что файл
/etc/porttime
обрабатывается в порядке появления записей в файле\&. Любой другой пользователь попадёт под правило второй записи, которая не разрешает доступ в любое время\&.
.sp
.if n \{\
.RS 4
.\}
.nf
      console:root,oper:Al0000\-2400
      console:*:
    
.fi
.if n \{\
.RE
.\}
.PP
Следующая запись разрешает доступ пользователю
\fIgames\fR
с любого порта в нерабочие часы\&.
.PP
*:games:Wk1700\-0900,SaSu0000\-2400
.SH "ФАЙЛЫ"
.PP
/etc/porttime
.RS 4
содержит разрешённое время работы определённых пользователей с определённых портов
.RE
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBlogin\fR(1)\&.
