'\" t
.\"     Title: shadow
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 05/09/2014
.\"    Manual: Форматы файлов
.\"    Source: shadow-utils 4.2
.\"  Language: Russian
.\"
.TH "shadow" "5" "05/09/2014" "shadow\-utils 4\&.2" "Форматы файлов"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВАНИЕ"
shadow \- файл теневых паролей
.SH "ОПИСАНИЕ"
.PP
Файл
shadow
содержит шифрованные пароли учётных записей пользователей и необязательную информацию об устаревании пароля\&.
.PP
Этот файл должен быть недоступен обычному пользователю, если нужно обеспечить безопасность паролей\&.
.PP
Каждая строка файла содержит 9 полей, разделённых двоеточиями (\(Fo:\(Fc), расположенных в следующем порядке:
.PP
\fBимя пользователя для входа в систему\fR
.RS 4
Должно содержать правильное имя учётной записи, которая существует в системе\&.
.RE
.PP
\fBшифрованный пароль\fR
.RS 4
Подробней о пароле смотрите в справочной странице
\fBcrypt\fR(3)\&.
.sp
Если поле пароля содержит строку, которая не удовлетворяет требованиям
\fBcrypt\fR(3), например содержит ! или *, то пользователь не сможет использовать этот пароль unix для входа (но может войти в систему под другими паролями)\&.
.sp
Это поле может быть пустым, то есть для указанной учётной записи не требуется аутентификация по паролю\&. Однако, некоторые приложения, читающие файл
/etc/shadow, могут вообще отказать в доступе, если поле пароля пусто\&.
.sp
Поле пароля может начинаться с восклицательного знака, означающего, что пароль заблокирован\&. Оставшиеся символы в строке представляют поле пароля до его блокировки\&.
.RE
.PP
\fBдата последней смены пароля\fR
.RS 4
Дата последней смены пароля в днях начиная с 1 января 1970 года\&.
.sp
Значение 0 имеет специальное предназначение: оно указывает, что пользователь должен сменить пароль в следующий раз при входе в систему\&.
.sp
Пустое значение обозначает, что проверка устаревания пароля выключена\&.
.RE
.PP
\fBминимальный срок действия пароля\fR
.RS 4
Минимальный срок действия пароля в днях, которые пользователь должен ждать, чтобы поменять пароль\&.
.sp
Пустое значение поля и 0 отключают минимальный срок действия пароля\&.
.RE
.PP
\fBмаксимальный срок действия пароля\fR
.RS 4
Максимальный срок действия пароля в днях, после которого пользователь должен изменить пароль\&.
.sp
По прошествии этого количества дней пароль может быть ещё действительным\&. Пользователя нужно попросить изменить пароль при следующем входе\&.
.sp
Пустое значение поля означает, что нет максимального срока действия пароля, нет периода предупреждения о пароле и нет периода неактивности пароля (смотрите далее)\&.
.sp
Если максимальный срок действия пароля меньше чем минимальный срок действия пароля, то пользователь не сможет изменить свой пароль\&.
.RE
.PP
\fBпериод предупреждения о пароле\fR
.RS 4
Количество дней до устаревания пароля (смотрите максимальный срок действия пароля) во время которых пользователю выдаётся предупреждение\&.
.sp
Пустое значение поля и 0 отключают период предупреждения о пароле\&.
.RE
.PP
\fBпериод неактивности пароля\fR
.RS 4
Количество дней после устаревания пароля (смотрите максимальный срок действия пароля) во время которых пароль всё ещё принимается (и пользователь должен обновить свой пароль при следующем входе)\&.
.sp
После устаревания пароля и истечения этого периода устаревания вход с текущим паролем становится невозможным\&. Пользователь должен обратиться к администратору\&.
.sp
Пустое значение поля означает, что период неактивности отсутствует\&.
.RE
.PP
\fBдата истечения срока действия учётной записи\fR
.RS 4
Дата истечения срока действия учётной записи, указывается в днях начиная с 1 января 1970 года\&.
.sp
Заметим, что устаревание учётной записи отличается от устаревания пароля\&. При устаревании учётной записи пользователь не сможет войти в систему\&. При устаревании пароля пользователь не может войти в систему по этому паролю\&.
.sp
Пустое значение обозначает, что учётная запись никогда не устаревает\&.
.sp
Значение 0 не должно использоваться, так как это может рассматриваться как неустаревающая учётная запись или что запись устарела 1 января 1970 года\&.
.RE
.PP
\fBзарезервированное поле\fR
.RS 4
Это поле зарезервировано для использования в будущем\&.
.RE
.SH "ФАЙЛЫ"
.PP
/etc/passwd
.RS 4
содержит информацию о пользователях
.RE
.PP
/etc/shadow
.RS 4
содержит защищаемую информацию о пользователях
.RE
.PP
/etc/shadow\-
.RS 4
резервная копия файла /etc/shadow
.sp
Заметим, что этот файл используется программами из комплекта утилит shadow, но не всеми инструментами управления пользователями и паролями\&.
.RE
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBchage\fR(1),
\fBlogin\fR(1),
\fBpasswd\fR(1),
\fBpasswd\fR(5),
\fBpwck\fR(8),
\fBpwconv\fR(8),
\fBpwunconv\fR(8),
\fBsu\fR(1),
\fBsulogin\fR(8)\&.
