'\" t
.\"     Title: suauth
.\"    Author: Marek Micha\(/lkiewicz
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 05/09/2014
.\"    Manual: Форматы файлов
.\"    Source: shadow-utils 4.2
.\"  Language: Russian
.\"
.TH "suauth" "5" "05/09/2014" "shadow\-utils 4\&.2" "Форматы файлов"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВАНИЕ"
suauth \- файл управления командой su
.SH "СИНТАКСИС"
.HP \w'\fB/etc/suauth\fR\ 'u
\fB/etc/suauth\fR
.SH "ОПИСАНИЕ"
.PP
Файл
/etc/suauth
проверяется каждый раз при запуске команды su\&. Он влияет на поведение команды su, в зависимости от:
.sp
.if n \{\
.RS 4
.\}
.nf
      1) пользователя, права которого нужно получить с помощью su
    
.fi
.if n \{\
.RE
.\}
.PP
2) пользователя, запустившего команду su (или группы, членом которой он может быть)
.PP
Формат файла показан ниже, строки начинающиеся с # считаются комментарием и игнорируются;
.sp
.if n \{\
.RS 4
.\}
.nf
      желаемый\-id:желающий\-id:ДЕЙСТВИЕ
    
.fi
.if n \{\
.RE
.\}
.PP
Где желаемый\-id может быть словом
\fIALL\fR, списком имён пользователей, перечисленных через запятую (\(Fo,\(Fc) или фразы
\fIALL EXCEPT\fR, после которой идёт список имён пользователей перечисленных через \(Fo,\(Fc\&.
.PP
желающий\-id может содержать то же, что и желательный\-id, плюс новое слово\fIGROUP\fR\&.
\fIALL EXCEPT GROUP\fR
тоже допустимо\&. После
\fIGROUP\fR
указывается одна или более названий групп, разделённых \(Fo,\(Fc\&. Недостаточно иметь id первичной группы соответствующей группы, необходимо иметь запись в файле
\fB/etc/group\fR(5)\&.
.PP
В поле ДЕЙСТВИЕ может быть только одно из следующих значений:
.PP
\fIDENY\fR
.RS 4
Команда su останавливает выполнение, даже не спрашивая пароль\&.
.RE
.PP
\fINOPASS\fR
.RS 4
Команда su выполняется без запроса пароля\&.
.RE
.PP
\fIOWNPASS\fR
.RS 4
Чтобы успешно выполнить команду su, пользователь должен ввести свой собственный пароль\&.
.RE
.PP
Заметим, что тут используются три поля, разделённых двоеточиями\&. Никаких пробелов не допускается около двоеточий\&. Также заметим, что файл просматривается строка за строкой, и первое подходящее правило будет использовано без проверки оставшихся правил\&. Это позволяет системному администратору осуществлять любой контроль, какой он пожелает\&.
.SH "ПРИМЕР"
.sp
.if n \{\
.RS 4
.\}
.nf
      # пример файла /etc/suauth
      #
      # Пара привилегированных имён пользователей
      # могут выполнить su, чтобы получить права суперпользователя введя свой пароль\&.
      #
      root:chris,birddog:OWNPASS
      #
      # Все остальные не могут выполнить su для получения root, если они 
      # не члены группы wheel\&. Так настроено в BSD\&.
      #
      root:ALL EXCEPT GROUP wheel:DENY
      #
      # Возможно учётными записями terry и birddog
      # владеет один человек\&.
      # Переход из одной записи в другую
      # можно сделать без запроса пароля\&.
      #
      terry:birddog:NOPASS
      birddog:terry:NOPASS
      #
    
.fi
.if n \{\
.RE
.\}
.SH "ФАЙЛЫ"
.PP
/etc/suauth
.RS 4
.RE
.SH "ОШИБКИ РЕАЛИЗАЦИИ"
.PP
Может быть несколько угроз\&. Анализатор файла, в частности, не прощает синтаксических ошибок, ожидая, что не будет недопустимых пробелов (кроме как в начале и конце строк) и специальных слов, разделяющих различные вещи\&.
.SH "ДИАГНОСТИКА"
.PP
Ошибки при анализе файла выводятся с помощью
\fBsyslogd\fR(8)
с уровнем ERR средства AUTH\&.
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBsu\fR(1)\&.
