'\" t
.\"     Title: newusers
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 09/05/2014
.\"    Manual: Commandes de gestion du syst\(`eme
.\"    Source: shadow-utils 4.2
.\"  Language: French
.\"
.TH "NEWUSERS" "8" "09/05/2014" "shadow\-utils 4\&.2" "Commandes de gestion du syst\(`em"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NOM"
newusers \- Mettre \(`a jour, ou cr\('eer de nouveaux utilisateurs par lots
.SH "SYNOPSIS"
.HP \w'\fBnewusers\fR\ 'u
\fBnewusers\fR [\fIoptions\fR] [\fIfichier\fR]
.SH "DESCRIPTION"
.PP
La commande
\fBnewusers\fR
lit un
\fIfichier\fR\fI\fI (ou l\*(Aqentr\('ee standard par d\('efaut) et utilise ces informations pour mettre \(`a jour un groupe d\*(Aqutilisateurs existants ou pour cr\('eer de nouveaux utilisateurs\&. Chaque ligne est au m\(^eme format que le fichier des mots de passe (consultez \fR\fI\fBpasswd\fR(5)\fR\fI) avec les exceptions suivantes\ \&:\fR\fR
.PP
pw_name:pw_passwd:pw_uid:pw_gid:pw_gecos:pw_dir:pw_shell
.PP
\fIpw_name\fR
.RS 4
C\*(Aqest le nom de l\*(Aqutilisateur\&.
.sp
Il peut s\*(Aqagir du nom d\*(Aqun nouvel utilisateur ou du nom d\*(Aqun utilisateur existant (ou d\*(Aqun utilisateur cr\('e\('e pr\('ec\('edemment par
\fBnewusers\fR)\&. Dans le cas d\*(Aqun utilisateur existant, les informations de l\*(Aqutilisateur seront modifi\('ees, sinon un nouvel utilisateur sera cr\('e\('e\&.
.RE
.PP
\fIpw_passwd\fR
.RS 4
Ce champ sera chiffr\('e et utilis\('e comme nouvelle valeur du mot de passe chiffr\('e\&.
.RE
.PP
\fIpw_uid\fR
.RS 4
Ce champ est utilis\('e pour d\('efinir l\*(AqUID de l\*(Aqutilisateur\&.
.sp
Si ce champ est vide, un nouvel UID (non utilis\('e) sera d\('efini automatiquement par
\fBnewusers\fR\&.
.sp
Si ce champ contient un nombre, ce nombre sera utilis\('e comme UID\&.
.sp
Si ce champ contient le nom d\*(Aqun utilisateur existant (ou le nom d\*(Aqun utilisateur cr\('e\('e pr\('ec\('edemment par
\fBnewusers\fR), l\*(AqUID de l\*(Aqutilisateur indiqu\('e sera utilis\('e\&.
.sp
Si l\*(AqUID d\*(Aqun utilisateur existant est modifi\('e, vous devrez configurer vous\-m\(^eme le propri\('etaire des fichiers de l\*(Aqutilisateur\&.
.RE
.PP
\fIpw_gid\fR
.RS 4
Ce champ est utilis\('e pour d\('efinir l\*(Aqidentifiant du groupe primaire de l\*(Aqutilisateur\&.
.sp
Si ce champ contient le nom d\*(Aqun groupe existant (ou d\*(Aqun groupe cr\('e\('e pr\('ec\('edemment par
\fBnewusers\fR), le GID de ce groupe sera utilis\('e comme identifiant de groupe primaire pour l\*(Aqutilisateur\&.
.sp
Si ce champ est un nombre, ce nombre sera utilis\('e comme identifiant de groupe primaire de cet utilisateur\&. Si aucun groupe n\*(Aqexiste avec ce GID, un nouveau groupe sera cr\('e\('e avec ce GID et le nom de l\*(Aqutilisateur\&.
.sp
Si ce champ est vide, un nouveau groupe sera cr\('e\('e avec le nom de l\*(Aqutilisateur et un GID sera automatiquement d\('efini par
\fBnewusers\fR
pour \(^etre utilis\('e comme identifiant de groupe primaire pour l\*(Aqutilisateur et comme GID pour le nouveau groupe\&.
.sp
Si le champ contient le nom d\*(Aqun groupe qui n\*(Aqexiste pas (et qui n\*(Aqa pas \('et\('e cr\('e\('e pr\('ec\('edemment par
\fBnewusers\fR), un nouveau groupe sera cr\('e\('e avec le nom indiqu\('e et un GID sera automatiquement d\('efini par
\fBnewusers\fR
pour \(^etre utilis\('e comme identifiant de groupe primaire pour l\*(Aqutilisateur et comme identifiant pour le nouveau groupe\&.
.RE
.PP
\fIpw_gecos\fR
.RS 4
Ce champ est copi\('e dans le champ GECOS de l\*(Aqutilisateur\&.
.RE
.PP
\fIpw_dir\fR
.RS 4
Ce champ est utilis\('e pour d\('efinir le r\('epertoire personnel de l\*(Aqutilisateur\&.
.sp
Si ce champ n\*(Aqindique pas de r\('epertoire existant, le r\('epertoire indiqu\('e est cr\('e\('e, avec comme propri\('etaire l\*(Aqutilisateur en cours de cr\('eation ou mis \(`a jour et son groupe primaire\&.
.sp
Si le r\('epertoire personnel d\*(Aqun utilisateur existant est modifi\('e,
\fBnewusers\fR
ne d\('eplace ni ne copie le contenu de l\*(Aqancien r\('epertoire personnel \(`a la nouvelle place\&. Vous devrez effectuer cela vous\-m\(^eme\&.
.RE
.PP
\fIpw_shell\fR
.RS 4
Ce champ d\('efinit l\*(Aqinterpr\('eteur de commande de l\*(Aqutilisateur\&. Aucune v\('erification n\*(Aqest effectu\('ee sur ce champ\&.
.RE
.PP
\fBnewusers\fR
essayera d\*(Aqabord de cr\('eer ou de modifier tous les utilisateurs indiqu\('es puis \('ecrira ces modifications dans les bases de donn\('ees d\*(Aqutilisateurs et de groupes\&. Si une erreur survient (en dehors de l\*(Aq\('ecriture finale des bases de donn\('ees), aucune modification ne sera propag\('ee dans les bases de donn\('ees\&.
.PP
Cette commande a \('et\('e con\(,cue pour les gros syst\(`emes pour lesquels un grand nombre de comptes sont mis \(`a jour en m\(^eme temps\&.
.SH "OPTIONS"
.PP
Les options disponibles pour la commande
\fBnewusers\fR
sont\ \&:
.PP
\fB\-c\fR, \fB\-\-crypt\-method\fR
.RS 4
Utiliser la m\('ethode pr\('ecis\('ee pour chiffrer les mots de passe\&.
.sp
Les m\('ethodes disponibles sont DES, MD5, NONE et SHA256 ou SHA512 si votre libc prend en charge ces m\('ethodes\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Afficher un message d\*(Aqaide et quitter\&.
.RE
.PP
\fB\-r\fR, \fB\-\-system\fR
.RS 4
Cr\('eer un compte syst\(`eme\&.
.sp
Les utilisateurs syst\(`eme seront cr\('e\('es sans information d\*(Aq\(^age dans
/etc/shadow
et leurs identifiants num\('eriques sont choisis dans l\*(Aqintervalle
\fBSYS_UID_MIN\fR\-\fBSYS_UID_MAX\fR, d\('efini dans
login\&.defs, au lieu de
\fBUID_MIN\fR\-\fBUID_MAX\fR
(et leur
\fBGID\fR
correspondant pour la cr\('eation de groupes)\&.
.RE
.PP
\fB\-R\fR, \fB\-\-root\fR\ \&\fICHROOT_DIR\fR
.RS 4
Appliquer les changements dans le r\('epertoire
\fIR\('EP_CHROOT\fR
et utiliser les fichiers de configuration du r\('epertoire
\fIR\('EP_CHROOT\fR\&.
.RE
.PP
\fB\-s\fR, \fB\-\-sha\-rounds\fR
.RS 4
Utiliser le nombre de rounds pr\('ecis\('e pour chiffrer les mots de passe\&.
.sp
La valeur 0 signifie que le syst\(`eme choisira la valeur par d\('efaut du nombre de rounds pour la m\('ethode de chiffrement (5\ \&000)\&.
.sp
Une valeur minimale de 1\ \&000 et une valeur maximale de 999\ \&999\ \&999 seront impos\('ees\&.
.sp
Vous ne pouvez utiliser cette m\('ethode qu\*(Aqavec les m\('ethodes de chiffrement SHA256 ou SHA512\&.
.sp
Par d\('efaut, le nombre de rounds est d\('efini par les variables SHA_CRYPT_MIN_ROUNDS et SHA_CRYPT_MAX_ROUNDS dans
/etc/login\&.defs\&.
.RE
.SH "AVERTISSEMENTS"
.PP
Le fichier d\*(Aqentr\('ee doit \(^etre correctement prot\('eg\('e puisqu\*(Aqil contient des mots de passe en clair\&.
.PP
Vous devez vous assurer que les mots de passe et la m\('ethode de chiffrement respectent la politique de mot de passe du syst\(`eme\&.
.SH "CONFIGURATION"
.PP
Les variables de configuration suivantes dans
/etc/login\&.defs
modifient le comportement de cet outil\ \&:
.PP
\fBENCRYPT_METHOD\fR (cha\(^ine de caract\(`eres)
.RS 4
D\('efinir les algorithmes de chiffrement par d\('efaut du syst\(`eme pour coder les mots de passes (si aucun algorithme n\*(Aqa \('et\('e indiqu\('e sur la ligne de commandes)\&.
.sp
Les valeurs suivantes sont accept\('ees\ \&:
\fIDES\fR
(par d\('efaut),
\fIMD5\fR, \fISHA256\fR, \fISHA512\fR\&.
.sp
Remarque\ \&: ce param\(`etre remplace la variable
\fBMD5_CRYPT_ENAB\fR\&.
.RE
.PP
\fBGID_MAX\fR (nombre), \fBGID_MIN\fR (nombre)
.RS 4
Plage d\*(Aqidentifiants num\('eriques de groupes que les commandes
\fBuseradd\fR,
\fBgroupadd\fR
ou
\fBnewusers\fR
peuvent utiliser pour la cr\('eation des groupes normaux\&.
.sp
La valeur par d\('efaut pour
\fBGID_MIN\fR
(respectivement
\fBGID_MAX\fR) est 1000 (respectivement 60000)\&.
.RE
.PP
\fBMAX_MEMBERS_PER_GROUP\fR (nombre)
.RS 4
Nombre maximum de membres par entr\('ee de groupe\&. Lorsque le maximum est atteint, une nouvelle entr\('ee de groupe (ligne) est d\('emarr\('ee dans
/etc/group
(avec le m\(^eme nom, m\(^eme mot de passe, et m\(^eme GID)\&.
.sp
La valeur par d\('efaut est 0, ce qui signifie qu\*(Aqil n\*(Aqy a pas de limites pour le nombre de membres dans un groupe\&.
.sp
Cette fonctionnalit\('e (groupe d\('ecoup\('e) permet de limiter la longueur des lignes dans le fichier de groupes\&. Ceci est utile pour s\*(Aqassurer que les lignes pour les groupes NIS ne sont pas plus grandes que 1024 caract\(`eres\&.
.sp
Si vous avez besoin de configurer cette limite, vous pouvez utiliser 25\&.
.sp
Remarque\ \&: les groupes d\('ecoup\('es ne sont peut\-\(^etre pas pris en charge par tous les outils (m\(^eme dans la suite d\*(Aqoutils Shadow)\&. Vous ne devriez pas utiliser cette variable, sauf si vous en avez vraiment besoin\&.
.RE
.PP
\fBMD5_CRYPT_ENAB\fR (bool\('een)
.RS 4
Indiquer si un mot de passe doit \(^etre chiffr\('e en utilisant l\*(Aqalgorithme bas\('e sur MD5\&. Si configur\('ee \(`a
\fIyes\fR, les nouveaux mots de passe seront chiffr\('es en utilisant l\*(Aqalgorithme bas\('e sur MD5 compatible avec celui utilis\('e par les versions r\('ecentes de FreeBSD\&. Il g\(`ere des mots de passe de longueur illimit\('ee et des cha\(^ines de salage plus longues\&. Configurez\-la \(`a
\fIno\fR
pour copier les mots de passe chiffr\('es sur d\*(Aqautres syst\(`emes qui ne comprennent pas le nouvel algorithme\&. la valeur par d\('efaut est
\fIno\fR\&.
.sp
Cette variable est \('ecras\('ee par la variable
\fBENCRYPT_METHOD\fR
ou par toute option de la ligne de commande utilis\('ee pour configurer l\*(Aqalgorithme de chiffrement\&.
.sp
Cette variable est obsol\(`ete\&. Vous devriez utiliser
\fBENCRYPT_METHOD\fR\&.
.RE
.PP
\fBPASS_MAX_DAYS\fR (nombre)
.RS 4
Nombre maximum de jours de validit\('e d\*(Aqun mot de passe\&. Apr\(`es cette dur\('ee, une modification du mot de passe est obligatoire\&. S\*(Aqil n\*(Aqest pas pr\('ecis\('e, la valeur de \-1 est utilis\('ee (ce qui enl\(`eve toute restriction)\&.
.RE
.PP
\fBPASS_MIN_DAYS\fR (nombre)
.RS 4
Nombre minimum de jours autoris\('e avant la modification d\*(Aqun mot de passe\&. Toute tentative de modification du mot de passe avant cette dur\('ee est rejet\('ee\&. S\*(Aqil n\*(Aqest pas pr\('ecis\('e, la valeur de \-1 est utilis\('ee (ce qui enl\(`eve toute restriction)\&.
.RE
.PP
\fBPASS_WARN_AGE\fR (nombre)
.RS 4
Nombre de jours durant lesquels l\*(Aqutilisateur recevra un avertissement avant que son mot de passe n\*(Aqarrive en fin de validit\('e\&. Une valeur n\('egative signifie qu\*(Aqaucun avertissement n\*(Aqest donn\('e\&. S\*(Aqil n\*(Aqest pas pr\('ecis\('e, aucun avertissement n\*(Aqest donn\('e\&.
.RE
.PP
\fBSHA_CRYPT_MIN_ROUNDS\fR (nombre), \fBSHA_CRYPT_MAX_ROUNDS\fR (nombre)
.RS 4
Quand
\fBENCRYPT_METHOD\fR
est configur\('ee \(`a
\fISHA256\fR
ou
\fISHA512\fR, cela d\('efinit le nombre de rounds de SHA utilis\('es par l\*(Aqalgorithme de chiffrement par d\('efaut (quand le nombre de rounds n\*(Aqest pas pr\('ecis\('e sur la ligne de commande)\&.
.sp
Avec beaucoup de rounds, il est plus difficile de trouver le mot de passe avec une attaque par force brute\&. Veuillez remarquer que plus de ressources processeur seront n\('ecessaires pour authentifier les utilisateurs\&.
.sp
Si non pr\('ecis\('ee, la libc utilisera le nombre de rounds par d\('efaut (5000)\&.
.sp
Les valeurs doivent \(^etre comprises dans l\*(Aqintervalle 1\ \&000\ \&\-\ \&999\ \&999\ \&999\&.
.sp
Si une seule des variables
\fBSHA_CRYPT_MIN_ROUNDS\fR
ou
\fBSHA_CRYPT_MAX_ROUNDS\fR
est configur\('ee, alors cette valeur sera utilis\('ee\&.
.sp
Si
\fBSHA_CRYPT_MIN_ROUNDS\fR
>
\fBSHA_CRYPT_MAX_ROUNDS\fR, la valeur la plus \('elev\('ee sera utilis\('ee\&.
.RE
.PP
\fBSUB_GID_MIN\fR (number), \fBSUB_GID_MAX\fR (number), \fBSUB_GID_COUNT\fR (number)
.RS 4
If
/etc/subuid
exists, the commands
\fBuseradd\fR
and
\fBnewusers\fR
(unless the user already have subordinate group IDs) allocate
\fBSUB_GID_COUNT\fR
unused group IDs from the range
\fBSUB_GID_MIN\fR
to
\fBSUB_GID_MAX\fR
for each new user\&.
.sp
The default values for
\fBSUB_GID_MIN\fR,
\fBSUB_GID_MAX\fR,
\fBSUB_GID_COUNT\fR
are respectively 100000, 600100000 and 10000\&.
.RE
.PP
\fBSUB_UID_MIN\fR (number), \fBSUB_UID_MAX\fR (number), \fBSUB_UID_COUNT\fR (number)
.RS 4
If
/etc/subuid
exists, the commands
\fBuseradd\fR
and
\fBnewusers\fR
(unless the user already have subordinate user IDs) allocate
\fBSUB_UID_COUNT\fR
unused user IDs from the range
\fBSUB_UID_MIN\fR
to
\fBSUB_UID_MAX\fR
for each new user\&.
.sp
The default values for
\fBSUB_UID_MIN\fR,
\fBSUB_UID_MAX\fR,
\fBSUB_UID_COUNT\fR
are respectively 100000, 600100000 and 10000\&.
.RE
.PP
\fBSYS_GID_MAX\fR (nombre), \fBSYS_GID_MIN\fR (nombre)
.RS 4
Plage d\*(Aqidentifiants num\('eriques de groupes que les commandes
\fBuseradd\fR,
\fBgroupadd\fR
ou
\fBnewusers\fR
peuvent utiliser pour la cr\('eation de groupes syst\(`eme\&.
.sp
La valeur par d\('efaut pour
\fBSYS_GID_MIN\fR
(respectivement
\fBSYS_GID_MAX\fR) est 101 (respectivement
\fBGID_MIN\fR\-1)\&.
.RE
.PP
\fBSYS_UID_MAX\fR (nombre), \fBSYS_UID_MIN\fR (nombre)
.RS 4
Plage d\*(Aqidentifiants num\('eriques d\*(Aqutilisateurs que les commandes
\fBuseradd\fR
ou
\fBnewusers\fR
peuvent utiliser pour la cr\('eation d\*(Aqutilisateurs syst\(`eme\&.
.sp
La valeur par d\('efaut pour
\fBSYS_UID_MIN\fR
(respectivement
\fBSYS_UID_MAX\fR) est 101 (respectivement
\fBUID_MIN\fR\-1)\&.
.RE
.PP
\fBUID_MAX\fR (nombre), \fBUID_MIN\fR (nombre)
.RS 4
Plage d\*(Aqidentifiants num\('eriques d\*(Aqutilisateurs que les commandes
\fBuseradd\fR
ou
\fBnewusers\fR
peuvent utiliser pour la cr\('eation d\*(Aqutilisateurs normaux\&.
.sp
La valeur par d\('efaut de
\fBUID_MIN\fR
(respectivement
\fBUID_MAX\fR) est 1000 (respectivement 60000)\&.
.RE
.PP
\fBUMASK\fR (nombre)
.RS 4
Valeur d\*(Aqinitialisation du masque de permissions\&. S\*(Aqil n\*(Aqest pas pr\('ecis\('e, le masque des permissions sera initialis\('e \(`a 022\&.
.sp
\fBuseradd\fR
et
\fBnewusers\fR
utilisent ce masque pour d\('efinir les permissions d\*(Aqacc\(`es des r\('epertoires personnels qu\*(Aqils cr\('eent\&.
.sp
Il est \('egalement utilis\('e par
\fBlogin\fR
pour d\('efinir l\*(Aqumask initial de l\*(Aqutilisateur\&. Veuillez noter que cet umask peut \(^etre red\('efini par les GECOS de l\*(Aqutilisateur (si
\fBQUOTAS_ENAB\fR
est activ\('e) ou en pr\('ecisant une limite avec l\*(Aqidentifiant
\fIK\fR
dans
\fBlimits\fR(5)\&.
.RE
.SH "FICHIERS"
.PP
/etc/passwd
.RS 4
Informations sur les comptes des utilisateurs\&.
.RE
.PP
/etc/shadow
.RS 4
Informations s\('ecuris\('ees sur les comptes utilisateurs\&.
.RE
.PP
/etc/group
.RS 4
Informations sur les groupes\&.
.RE
.PP
/etc/gshadow
.RS 4
Informations s\('ecuris\('ees sur les groupes\&.
.RE
.PP
/etc/login\&.defs
.RS 4
Configuration de la suite des mots de passe cach\('es \(Fo\ \&shadow password\ \&\(Fc\&.
.RE
.PP
/etc/subgid
.RS 4
Per user subordinate group IDs\&.
.RE
.PP
/etc/subuid
.RS 4
Per user subordinate user IDs\&.
.RE
.SH "VOIR AUSSI"
.PP
\fBlogin.defs\fR(5),
\fBpasswd\fR(1),
\fBsubgid\fR(5), \fBsubuid\fR(5),\fBuseradd\fR(8)\&.
