#!/bin/sh

set -e

export LC_ALL=C
unset LANG
unset LANGUAGE

succeded=0
failed=0
failed_tests=""

run_test()
{
	if $1 > $1.log
	then
		succeded=$((succeded+1))
		echo -n "+"
	else
		failed=$((failed+1))
		failed_tests="$failed_tests $1"
		echo -n "-"
	fi
	cat $1.log >> testsuite.log
}

echo "+: test passed"
echo "-: test failed"

# Empty the complete log.
> testsuite.log

run_test ./su/01/su_root.test
run_test ./su/01/su_user.test
run_test ./su/02/env_FOO-options_--login
run_test ./su/02/env_FOO-options_--login_bash
run_test ./su/02/env_FOO-options_--preserve-environment
run_test ./su/02/env_FOO-options_--preserve-environment_bash
run_test ./su/02/env_FOO-options_-
run_test ./su/02/env_FOO-options_-_bash
run_test ./su/02/env_FOO-options_-l-m
run_test ./su/02/env_FOO-options_-l-m_bash
run_test ./su/02/env_FOO-options_-l
run_test ./su/02/env_FOO-options_-l_bash
run_test ./su/02/env_FOO-options_-m_bash
run_test ./su/02/env_FOO-options_-m
run_test ./su/02/env_FOO-options_-p
run_test ./su/02/env_FOO-options_-p_bash
run_test ./su/02/env_FOO-options__bash
run_test ./su/02/env_FOO-options_
run_test ./su/02/env_FOO-options_-p-
run_test ./su/02/env_FOO-options_-p-_bash
run_test ./su/02/env_special-options_-l-p
run_test ./su/02/env_special-options_-l
run_test ./su/02/env_special-options_-l-p_bash
run_test ./su/02/env_special-options_-l_bash
run_test ./su/02/env_special-options_-p
run_test ./su/02/env_special-options_-p_bash
run_test ./su/02/env_special-options_
run_test ./su/02/env_special-options__bash
run_test ./su/02/env_special_root-options_-l-p
run_test ./su/02/env_special_root-options_-l-p_bash
run_test ./su/02/env_special_root-options_-l
run_test ./su/02/env_special_root-options_-l_bash
run_test ./su/02/env_special_root-options_-p
run_test ./su/02/env_special_root-options_-p_bash
run_test ./su/02/env_special_root-options_
run_test ./su/02/env_special_root-options__bash
run_test ./su/03/su_run_command01.test
run_test ./su/03/su_run_command02.test
run_test ./su/03/su_run_command03.test
run_test ./su/03/su_run_command04.test
run_test ./su/03/su_run_command05.test
run_test ./su/03/su_run_command06.test
run_test ./su/03/su_run_command07.test
run_test ./su/03/su_run_command08.test
run_test ./su/03/su_run_command09.test
run_test ./su/03/su_run_command10.test
run_test ./su/03/su_run_command11.test
run_test ./su/03/su_run_command12.test
run_test ./su/03/su_run_command13.test
run_test ./su/03/su_run_command14.test
run_test ./su/03/su_run_command15.test
run_test ./su/03/su_run_command16.test
run_test ./su/03/su_run_command17.test
run_test ./su/04/su_wrong_user.test
run_test ./su/04/su_user_wrong_passwd.test
run_test ./su/04/su_user_wrong_passwd_syslog.test
run_test ./su/05/su_user_wrong_passwd_syslog.test
run_test ./su/06/su_user_syslog.test
run_test ./su/07/su_user_syslog.test
run_test ./su/08/env_special-options_
run_test ./su/08/env_special_root-options_
run_test ./su/09/env_special-options_
run_test ./su/09/env_special_root-options_
run_test ./convtools/01/run
run_test ./convtools/02_grpconv_remove_gshadow_only_entries/grpconv.test
run_test ./convtools/03_grpconv_copy_passwd/grpconv.test
run_test ./convtools/04_grpconv_no_password/grpconv.test
run_test ./chage/01/run
run_test ./chage/02/run
run_test ./chsh/01/run
run_test ./debian/01/run
run_test ./usertools/01/01_useradd_add_user.test
run_test ./usertools/01/01_userdel_delete_user.test
run_test ./usertools/01/02_useradd_recreate_deleted_user.test
run_test ./usertools/01/03_useradd_additional_options.test
run_test ./usertools/01/04_useradd_add_user_with_existing_UID_fail.test
run_test ./usertools/01/04_useradd_add_user_with_existing_UID_with_-o.test
run_test ./usertools/01/04_useradd_specified_UID.test
run_test ./usertools/01/04_useradd_specified_UID_and_GID.test
run_test ./usertools/01/04_userdel_delete_user_with_non_unique_UID.test
run_test ./usertools/01/05_useradd_invalid_numeric_primary_group.test
run_test ./usertools/01/06_useradd_invalid_named_primary_group.test
run_test ./usertools/01/07_useradd_numerical_primary_group.test
run_test ./usertools/01/08_useradd_named_primary_group.test
run_test ./usertools/01/09_usermod_change_user_info.test
run_test ./usertools/01/10_usermod_rename_user.test
run_test ./usertools/01/10_usermod_rename_user_in_group.test
run_test ./usertools/01/11_usermod_change_password.test
run_test ./usertools/01/11_usermod_lock_password.test
run_test ./usertools/01/11_usermod_unlock_empty_password.test
run_test ./usertools/01/11_usermod_unlock_password.test
run_test ./usertools/01/12_usermod_change_gid_name.test
run_test ./usertools/01/12_usermod_change_gid_number.test
run_test ./usertools/01/13_useradd_negative_UID.test
run_test ./usertools/01/14_useradd_out_of_range_UID.test
run_test ./usertools/01/15_useradd_specified_large_UID.test
run_test ./usertools/01/16_useradd_add_user_to_multiple_groups.test
run_test ./usertools/01/16_useradd_add_user_to_one_group.test
run_test ./usertools/02/useradd_default_default_values.test
run_test ./usertools/02/useradd_get_default_values.test
run_test ./usertools/02/useradd_change_default_INACTIVE.test
run_test ./usertools/02/useradd_change_default_SHELL.test
run_test ./usertools/02/useradd_change_default_EXPIRE.test
run_test ./usertools/02/useradd_change_default_GROUP.test
run_test ./usertools/02/useradd_change_default_HOME.test
run_test ./usertools/02/useradd_change_defaults.test
run_test ./usertools/03/useradd_change_defaults.test
run_test ./usertools/04/01_useradd_add_user.test
run_test ./cptools/01/run1
run_test ./cptools/01/run2
run_test ./cptools/01/run3
run_test ./cptools/01/run4
run_test ./cktools/01/run1
run_test ./cktools/01/run2
run_test ./crypt/login.defs_DES-MD5_CRYPT_ENAB/01_chpasswd.test
run_test ./crypt/login.defs_DES/01_chpasswd.test
run_test ./crypt/login.defs_DES/02_chpasswd--crypt-method-MD5.test
run_test ./crypt/login.defs_DES/03_chpasswd--crypt-method-DES.test
run_test ./crypt/login.defs_DES/04_chpasswd--crypt-method-NONE.test
run_test ./crypt/login.defs_DES/05_chpasswd-e.test
run_test ./crypt/login.defs_DES/06_chpasswd-m.test
run_test ./crypt/login.defs_DES/07_chgpasswd.test
run_test ./crypt/login.defs_DES/08_chgpasswd--crypt-method-MD5.test
run_test ./crypt/login.defs_DES/09_chgpasswd--crypt-method-DES.test
run_test ./crypt/login.defs_DES/10_chgpasswd--crypt-method-NONE.test
run_test ./crypt/login.defs_DES/11_chgpasswd-e.test
run_test ./crypt/login.defs_DES/12_chgpasswd-m.test
run_test ./crypt/login.defs_MD5/01_chpasswd.test
run_test ./crypt/login.defs_MD5_CRYPT_ENAB/01_chpasswd.test
run_test ./crypt/login.defs_SHA256/01_chpasswd.test
run_test ./crypt/login.defs_SHA512/01_chpasswd.test
run_test ./crypt/login.defs_none/01_chpasswd.test
run_test ./newusers/01_create_user/newusers.test
run_test ./newusers/02_update_password/newusers.test
run_test ./newusers/03_no_update_pid/newusers.test
run_test ./newusers/04_no_update_gid/newusers.test
run_test ./newusers/05_create_user_pid/newusers.test
run_test ./newusers/06_create_user_gid/newusers.test
run_test ./newusers/07_create_user_pid_gid/newusers.test
run_test ./newusers/08_create_user_pid_other-gid/newusers.test
run_test ./newusers/09_create_user_pid-as-user-bar/newusers.test
run_test ./newusers/10_create_user_gid-as-group-bar/newusers.test
run_test ./newusers/11_update_gecos/newusers.test
run_test ./newusers/12_update_shell/newusers.test
run_test ./newusers/13_create_user_new-home/newusers.test
run_test ./newusers/14_create_user_existing-home/newusers.test
run_test ./newusers/15_update_new-home/newusers.test
run_test ./newusers/16_update_existing-home/newusers.test
run_test ./newusers/17_create_user_pid-already-used/newusers.test
run_test ./newusers/18_create_user_gid-already-used/newusers.test

echo
echo "$succeded test(s) passed"
echo "$failed test(s) failed"
echo "log written in 'testsuite.log'"
if [ "$failed" != "0" ]
then
	echo "the following tests failed:"
	echo $failed_tests
fi

