'\" t
.\"     Title: vipw
.\"    Author: Marek Micha\(/lkiewicz
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 2014-05-09
.\"    Manual: 系统管理命令
.\"    Source: shadow-utils 4.2
.\"  Language: Chinese Simplified
.\"
.TH "VIPW" "8" "2014-05-09" "shadow\-utils 4\&.2" "系统管理命令"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "名称"
vipw, vigr \- 编辑密码、组、影子密码或影子组文件。
.SH "大纲"
.HP \w'\fBvipw\fR\ 'u
\fBvipw\fR [\fI选项\fR]
.HP \w'\fBvigr\fR\ 'u
\fBvigr\fR [\fI选项\fR]
.SH "描述"
.PP
\fBvipw\fR
和
\fBvigr\fR
命令分别编辑
/etc/passwd
和
/etc/group
文件。使用
\fB\-s\fR
标识时，将编辑这些文件的影子版，即分别为
/etc/shadow
和
/etc/gshadow。这些程序将设置相应的锁，以防止文件损坏。寻找编辑器时，首先尝试环境变量
\fB$VISUAL\fR，然后是环境变量
\fB$EDITOR\fR，最后是默认编辑器
\fBvi\fR(1)。
.SH "选项"
.PP
\fBvipw\fR
和
\fBvigr\fR
命令可以接受的选项有：
.PP
\fB\-g\fR, \fB\-\-group\fR
.RS 4
编辑 group 数据库。
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
现实帮助信息并退出。
.RE
.PP
\fB\-p\fR, \fB\-\-passwd\fR
.RS 4
编辑 passwd 数据库。
.RE
.PP
\fB\-q\fR, \fB\-\-quiet\fR
.RS 4
安静模式。
.RE
.PP
\fB\-R\fR, \fB\-\-root\fR\ \&\fICHROOT_DIR\fR
.RS 4
Apply changes in the
\fICHROOT_DIR\fR
directory and use the configuration files from the
\fICHROOT_DIR\fR
directory\&.
.RE
.PP
\fB\-s\fR, \fB\-\-shadow\fR
.RS 4
编辑 shadow 或 gshadow 数据库。
.RE
.SH "环境变量"
.PP
\fBVISUAL\fR
.RS 4
要使用的编辑器。
.RE
.PP
\fBEDITOR\fR
.RS 4
\fBVISUAL\fR
没有设置的情况下，使用的编辑器。
.RE
.SH "文件"
.PP
/etc/group
.RS 4
组账户信息。
.RE
.PP
/etc/gshadow
.RS 4
安全组账户信息。
.RE
.PP
/etc/passwd
.RS 4
用户账户信息。
.RE
.PP
/etc/shadow
.RS 4
安全用户账户信息。
.RE
.SH "参见"
.PP
\fBvi\fR(1),
\fBgroup\fR(5),
\fBgshadow\fR(5),
\fBpasswd\fR(5), ,
\fBshadow\fR(5)\&.
