'\" t
.\"     Title: chage
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 05/09/2014
.\"    Manual: Пользовательские команды
.\"    Source: shadow-utils 4.2
.\"  Language: Russian
.\"
.TH "chage" "1" "05/09/2014" "shadow\-utils 4\&.2" "Пользовательские команды"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВАНИЕ"
chage \- изменяет информацию об устаревании пароля пользователя
.SH "СИНТАКСИС"
.HP \w'\fBchage\fR\ 'u
\fBchage\fR [\fIпараметры\fR] \fIУЧЁТНАЯ_ЗАПИСЬ\fR
.SH "ОПИСАНИЕ"
.PP
Программа
\fBchage\fR
изменяет количество дней между датой смены пароля и датой последней смены пароля\&. Эта информация используется системой для определения момента, когда пользователь должен сменить свой пароль\&.
.SH "ПАРАМЕТРЫ"
.PP
Параметры команды
\fBchage\fR:
.PP
\fB\-d\fR, \fB\-\-lastday\fR\ \&\fIПОСЛ_ДЕНЬ\fR
.RS 4
Установить число дней прошедших с 1 января 1970 года, когда была последняя смена пароля\&. Дата может быть также указана в виде ГГГГ\-ММ\-ДД (или в форме согласно региональным настройкам)\&.
.RE
.PP
\fB\-E\fR, \fB\-\-expiredate\fR \fIДАТА_УСТАРЕВАНИЯ\fR
.RS 4
Установить дату устаревания учётной записи пользователя, которая задаётся числом дней прошедших с 1 января 1970 года\&. Дата может быть также задана в виде ГГГГ\-ММ\-ДД (или в форме согласно региональным настройкам)\&. Пользователь, чья учётная запись была заблокирована, должен обратиться к системному администратору, если хочет в дальнейшем работать с системой\&.
.sp
Значение
\fI\-1\fR
в параметре
\fIДАТА_УСТАРЕВАНИЯ\fR
отменяет устаревание учётной записи\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Показать краткую справку и закончить работу\&.
.RE
.PP
\fB\-I\fR, \fB\-\-inactive\fR\ \&\fIДНЕЙ\fR
.RS 4
Установить количество дней неактивности после устаревания пароля перед тем как учётная запись будет заблокирована\&. В параметре
\fIДНЕЙ\fR
задаётся количество дней неактивности\&. Пользователь, чья учётная запись была заблокирована, должен обратиться к системному администратору, если хочет в дальнейшем работать с системой\&.
.sp
Значение
\fI\-1\fR
в параметре
\fIДНЕЙ\fR
отменяет неактивность учётной записи\&.
.RE
.PP
\fB\-l\fR, \fB\-\-list\fR
.RS 4
Показать информацию об устаревании учётной записи\&.
.RE
.PP
\fB\-m\fR, \fB\-\-mindays\fR\ \&\fIМИН_ДНЕЙ\fR
.RS 4
Задать
\fIминимальное количество дней\fR
между сменами пароля\&. Нулевое значение этого поля указывает на то, что пользователь может менять свой пароль когда захочет\&.
.RE
.PP
\fB\-M\fR, \fB\-\-maxdays\fR\ \&\fIМАКС_ДНЕЙ\fR
.RS 4
Установить максимальное количество дней работоспособности пароля\&. Если сумма значений
\fIМАКС_ДНЕЙ\fR
и
\fIПОСЛ_ДЕНЬ\fR
раньше текущего дня, то пользователю придётся изменить свой пароль перед использованием учётной записи\&. Для того, чтобы это не было неожиданностью можно воспользоваться параметром
\fB\-W\fR, который активирует выдачу предупреждения о смене пароля пользователя заранее\&.
.sp
Значение
\fI\-1\fR
в параметре
\fIМАКС_ДНЕЙ\fR
отменяет проверку пароля\&.
.RE
.PP
\fB\-R\fR, \fB\-\-root\fR\ \&\fIКАТ_CHROOT\fR
.RS 4
Выполнить изменения в каталоге
\fIКАТ_CHROOT\fR
и использовать файлы настройки из каталога
\fIКАТ_CHROOT\fR\&.
.RE
.PP
\fB\-W\fR, \fB\-\-warndays\fR\ \&\fIПРЕДУП_ДНЕЙ\fR
.RS 4
Установить количество дней выдачи предупреждения, перед тем как потребуется смена пароля\&. Параметр
\fIПРЕДУП_ДНЕЙ\fR
считается в днях, в течении которых пользователь будет получать предупреждение об устаревании пароля, перед тем как это случится\&.
.RE
.PP
Если ни один параметр не указан, то
\fBchage\fR
переходит в интерактивный режим, предлагая запустившему пользователю изменить значения всех полей своей учётной записи\&. Вводимое значение заменяет текущее значение поля; если введена пустая строка, то текущее значение остаётся неизменным\&. Текущее значение показано в скобках
\fI[ ]\fR\&.
.SH "ЗАМЕЧАНИЕ"
.PP
Программа
\fBchage\fR
требует наличия файла теневых паролей\&.
.PP
Программа
\fBchage\fR
работает только от суперпользователя, за исключением вызова с параметром
\fB\-l\fR, который может использоваться непривилегированным пользователем для определения даты устаревания своего пароля\&.
.SH "НАСТРОЙКА"
.PP
На работу этого инструмента влияют следующие переменные настройки из
/etc/login\&.defs:
.SH "ФАЙЛЫ"
.PP
/etc/passwd
.RS 4
содержит информацию о пользователях
.RE
.PP
/etc/shadow
.RS 4
содержит защищаемую информацию о пользователях
.RE
.SH "ВОЗВРАЩАЕМЫЕ ЗНАЧЕНИЯ"
.PP
Программа
\fBchage\fR
завершая работу, возвращает следующие значения:
.PP
\fI0\fR
.RS 4
успешное выполнение
.RE
.PP
\fI1\fR
.RS 4
доступ запрещён
.RE
.PP
\fI2\fR
.RS 4
ошибка в параметрах команды
.RE
.PP
\fI15\fR
.RS 4
не удалось найти файл теневых паролей
.RE
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBpasswd\fR(5),
\fBshadow\fR(5)\&.
