'\" t
.\"     Title: chfn
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 05/09/2014
.\"    Manual: Пользовательские команды
.\"    Source: shadow-utils 4.2
.\"  Language: Russian
.\"
.TH "chfn" "1" "05/09/2014" "shadow\-utils 4\&.2" "Пользовательские команды"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВАНИЕ"
chfn \- изменяет информацию о пользователе
.SH "СИНТАКСИС"
.HP \w'\fBchfn\fR\ 'u
\fBchfn\fR [\fIпараметры\fR] [\fIУЧЁТНАЯ_ЗАПИСЬ\fR]
.SH "ОПИСАНИЕ"
.PP
Программа
\fBchfn\fR
изменяет ФИО, рабочий телефон, рабочий номер комнаты, рабочий и домашний номер телефона для учётной записи пользователя\&. Обычно, эти данные выводятся командой
\fBfinger\fR(1)
и ей подобными программами\&. Обычный пользователь может изменить только определённые данные собственной учётной записи, разрешённые в файле
/etc/login\&.defs
(настройкой по умолчанию пользователю не разрешается менять своё имя и фамилию)\&. Суперпользователь может изменять любые данные любой учётной записи\&. Кроме того, только суперпользователь может использовать параметр
\fB\-o\fR
для изменения нестандартизованной части данных GECOS\&.
.PP
Части поля GECOS не должны содержать двоеточий\&. За исключением части
\fIдругая\fR, в них не должно содержаться запятых и знаков равно\&. Также рекомендуется избегать символов не в кодировке US\-ASCII, но это касается только номеров телефонов\&. Часть
\fIдругая\fR
используется для хранения информации об учётной записи, которая используется другими приложениями\&.
.SH "ПАРАМЕТРЫ"
.PP
Параметры команды
\fBchfn\fR:
.PP
\fB\-f\fR, \fB\-\-full\-name\fR\ \&\fIФИО\fR
.RS 4
Изменяет ФИО пользователя\&.
.RE
.PP
\fB\-h\fR, \fB\-\-home\-phone\fR\ \&\fIДОМАШНИЙ_ТЕЛЕФОН\fR
.RS 4
Изменяет номер домашнего телефона пользователя\&.
.RE
.PP
\fB\-o\fR, \fB\-\-other\fR\ \&\fIДРУГАЯ\fR
.RS 4
Изменяет другую информацию GECOS о пользователе\&. Эта часть используется для хранения информации об учётной записи, используемой другими приложениями, и может изменяться только суперпользователем\&.
.RE
.PP
\fB\-r\fR, \fB\-\-room\fR\ \&\fIНОМЕР_КОМНАТЫ\fR
.RS 4
Изменяет номер комнаты пользователя\&.
.RE
.PP
\fB\-R\fR, \fB\-\-root\fR\ \&\fIКАТ_CHROOT\fR
.RS 4
Выполнить изменения в каталоге
\fIКАТ_CHROOT\fR
и использовать файлы настройки из каталога
\fIКАТ_CHROOT\fR\&.
.RE
.PP
\fB\-u\fR, \fB\-\-help\fR
.RS 4
Показать краткую справку и закончить работу\&.
.RE
.PP
\fB\-w\fR, \fB\-\-work\-phone\fR\ \&\fIРАБОЧИЙ_ТЕЛЕФОН\fR
.RS 4
Изменяет номер рабочего телефона пользователя\&.
.RE
.PP
Если ни один параметр не указан, то
\fBchfn\fR
переходит в интерактивный режим, предлагая запустившему пользователю изменить данные своей учётной записи\&. Вводимое значение заменяет текущее значение записи; если введена пустая строка, то текущее значение остаётся неизменным\&. Текущее значение показано в скобках
\fB[ ]\fR\&. При вызове без параметров программа
\fBchfn\fR
изменяет учётную запись запустившего пользователя\&.
.SH "НАСТРОЙКА"
.PP
На работу этого инструмента влияют следующие переменные настройки из
/etc/login\&.defs:
.PP
\fBCHFN_AUTH\fR (логический)
.RS 4
Если равно yes, chfn
.RE
.PP
\fBCHFN_RESTRICT\fR (строка)
.RS 4
Этим параметром определяются части поля
\fIgecos\fR
в файле
/etc/passwd, которые могут изменять обычные пользователи с помощью программы
\fBchfn\fR\&. Строка может содержать любую комбинацию букв
\fIf\fR,
\fIr\fR,
\fIw\fR,
\fIh\fR
для изменения полного имени пользователя, номера комнаты, рабочего и домашнего телефона, соответственно\&. Для совместимости значение
\fIyes\fR
эквивалентно
\fIrwh\fR
и
\fIno\fR
эквивалентно
\fIfrwh\fR\&. Если ничего не задано, то только суперпользователь может выполнять любые изменения\&. Наиболее ограничительная настройка достигается снятием SUID бита с файла
chfn\&.
.RE
.PP
\fBLOGIN_STRING\fR (строка)
.RS 4
Строка\-приглашение к вводу пароля\&. Значение по умолчанию: \(FoPassword:\(Fc или перевод этой строки на разные языки\&. Если вы измените эту переменную, то перевод будет отсутствовать\&.
.sp
Если в строке содержится подстрока
\fI%s\fR, то она будет заменена на имя пользователя\&.
.RE
.SH "ФАЙЛЫ"
.PP
/etc/login\&.defs
.RS 4
содержит конфигурацию подсистемы теневых паролей
.RE
.PP
/etc/passwd
.RS 4
содержит информацию о пользователях
.RE
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBchsh\fR(1),
\fBlogin.defs\fR(5),
\fBpasswd\fR(5)\&.
