'\" t
.\"     Title: chsh
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 05/09/2014
.\"    Manual: Пользовательские команды
.\"    Source: shadow-utils 4.2
.\"  Language: Russian
.\"
.TH "chsh" "1" "05/09/2014" "shadow\-utils 4\&.2" "Пользовательские команды"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВАНИЕ"
chsh \- изменяет регистрационную оболочку пользователя
.SH "СИНТАКСИС"
.HP \w'\fBchsh\fR\ 'u
\fBchsh\fR [\fIпараметры\fR] [\fIУЧЁТНАЯ_ЗАПИСЬ\fR]
.SH "ОПИСАНИЕ"
.PP
Программа
\fBchsh\fR
изменяет регистрационную оболочку пользователя\&. Она определяет какая команда будет запущена после регистрации пользователя в системе\&. Обычный пользователь может изменять регистрационную оболочку только для своей учётной записи; суперпользователь может изменять регистрационную оболочку любой учётной записи\&.
.SH "ПАРАМЕТРЫ"
.PP
Параметры команды
\fBchsh\fR:
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Показать краткую справку и закончить работу\&.
.RE
.PP
\fB\-R\fR, \fB\-\-root\fR\ \&\fIКАТ_CHROOT\fR
.RS 4
Выполнить изменения в каталоге
\fIКАТ_CHROOT\fR
и использовать файлы настройки из каталога
\fIКАТ_CHROOT\fR\&.
.RE
.PP
\fB\-s\fR, \fB\-\-shell\fR\ \&\fIОБОЛОЧКА\fR
.RS 4
Имя новой регистрационной оболочки пользователя\&. Если задать пустое значение, то будет использована регистрационная оболочка по умолчанию\&.
.RE
.PP
Если параметр
\fB\-s\fR
не задан, то
\fBchsh\fR
переходит в интерактивный режим, предлагая пользователю изменить свою регистрационную оболочку\&. Вводимое значение заменяет текущее значение поля; если введена пустая строка, то текущее значение остаётся неизменным\&. Текущее значение регистрационной оболочки указано в скобках
\fI[ ]\fR\&.
.SH "ЗАМЕЧАНИЕ"
.PP
Все допустимые имена регистрационных оболочек должны быть указаны в файле
/etc/shells\&. На суперпользователя это ограничение не действует и поэтому ему разрешено указывать любое значение\&. Для учётной записи с ограниченной регистрационной оболочкой пользователь не может изменить свою регистрационную оболочку\&. Поэтому
/bin/rsh
в файле
/etc/shells
лучше не указывать, так как, если пользователь случайно изменит свою регистрационную оболочку на эту ограниченную оболочку, то не сможет восстановить её первоначальное значение\&.
.SH "НАСТРОЙКА"
.PP
На работу этого инструмента влияют следующие переменные настройки из
/etc/login\&.defs:
.PP
\fBCHSH_AUTH\fR (логический)
.RS 4
Если равно
\fIyes\fR, то программа
\fBchsh\fR
будет проводить аутентификацию перед тем как выполнить любые изменения, в случае если команда не запущены суперпользователем\&.
.RE
.PP
\fBLOGIN_STRING\fR (строка)
.RS 4
Строка\-приглашение к вводу пароля\&. Значение по умолчанию: \(FoPassword:\(Fc или перевод этой строки на разные языки\&. Если вы измените эту переменную, то перевод будет отсутствовать\&.
.sp
Если в строке содержится подстрока
\fI%s\fR, то она будет заменена на имя пользователя\&.
.RE
.SH "ФАЙЛЫ"
.PP
/etc/passwd
.RS 4
содержит информацию о пользователях
.RE
.PP
/etc/shells
.RS 4
содержит список разрешённых регистрационных оболочек
.RE
.PP
/etc/login\&.defs
.RS 4
содержит конфигурацию подсистемы теневых паролей
.RE
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBchfn\fR(1),
\fBlogin.defs\fR(5),
\fBpasswd\fR(5)\&.
