'\" t
.\"     Title: expiry
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 05/09/2014
.\"    Manual: Пользовательские команды
.\"    Source: shadow-utils 4.2
.\"  Language: Russian
.\"
.TH "expiry" "1" "05/09/2014" "shadow\-utils 4\&.2" "Пользовательские команды"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВАНИЕ"
expiry \- проверяет и изменяет пароль согласно политике устаревания
.SH "СИНТАКСИС"
.HP \w'\fBexpiry\fR\ 'u
\fBexpiry\fR \fIпараметр\fR
.SH "ОПИСАНИЕ"
.PP
Программа
\fBexpiry\fR
проверяет (параметр
\fB\-c\fR) сколько ещё времени будет работоспособен текущий пароль и вынуждает изменить его (параметр
\fB\-f\fR), если это требуется\&. Она может запускаться обычным пользователем\&.
.SH "ПАРАМЕТРЫ"
.PP
Параметры команды
\fBexpiry\fR:
.PP
\fB\-c\fR, \fB\-\-check\fR
.RS 4
Проверяет и изменяет срок действия пароля у текущего пользователя\&.
.RE
.PP
\fB\-f\fR, \fB\-\-force\fR
.RS 4
Принудительно меняет пароль, если его срок действия истёк\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Показать краткую справку и закончить работу\&.
.RE
.SH "ФАЙЛЫ"
.PP
/etc/passwd
.RS 4
содержит информацию о пользователях
.RE
.PP
/etc/shadow
.RS 4
содержит защищаемую информацию о пользователях
.RE
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBpasswd\fR(5),
\fBshadow\fR(5)\&.
