'\" t
.\"     Title: gpasswd
.\"    Author: Rafal Maszkowski
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 05/09/2014
.\"    Manual: Пользовательские команды
.\"    Source: shadow-utils 4.2
.\"  Language: Russian
.\"
.TH "gpasswd" "1" "05/09/2014" "shadow\-utils 4\&.2" "Пользовательские команды"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВАНИЕ"
gpasswd \- управление /etc/group и /etc/gshadow
.SH "СИНТАКСИС"
.HP \w'\fBgpasswd\fR\ 'u
\fBgpasswd\fR [\fIпараметр\fR] \fIгруппа\fR
.SH "ОПИСАНИЕ"
.PP
Программа
\fBgpasswd\fR
используется для управления файлом
/etc/groupи /etc/gshadow\&. В каждой группе могут быть определены
администраторы,
члены и пароль\&.
.PP
Системные администраторы могут использовать параметр
\fB\-A\fR, чтобы назначить группе администратора(ов) и параметр
\fB\-M\fR
для определения списка членов, а также имеют все права администраторов и членов группы\&.
.PP
Программа
\fBgpasswd\fR, запущенная
администратором группы
с указанием в командной строке только имени группы, предложит назначить пароль
\fIгруппе\fR\&.
.PP
Если пароль не пустой, то для членов группы вызов
\fBnewgrp\fR(1)
пароля не требует, а не члены группы должны ввести пароль\&.
.SS "Замечания о паролях групп"
.PP
Пароли групп имеют врождённую проблему с безопасностью, так как пароль знает более одного человека\&. Однако, группы являются полезным инструментом совместной работы различных пользователей\&.
.SH "ПАРАМЕТРЫ"
.PP
За исключением параметров
\fB\-A\fR
и
\fB\-M\fR, параметры нельзя использовать вместе\&.
.PP
Параметры команды
\fBgpasswd\fR:
.PP
\fB\-a\fR, \fB\-\-add\fR\ \&\fIпользователь\fR
.RS 4
Добавить
\fIпользователя\fR
в указанную
\fIгруппу\fR\&.
.RE
.PP
\fB\-d\fR, \fB\-\-delete\fR\ \&\fIпользователь\fR
.RS 4
Удалить
\fIпользователя\fR
из указанной
\fIгруппы\fR\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Показать краткую справку и закончить работу\&.
.RE
.PP
\fB\-Q\fR, \fB\-\-root\fR\ \&\fIКАТ_CHROOT\fR
.RS 4
Выполнить изменения в каталоге
\fIКАТ_CHROOT\fR
и использовать файлы настройки из каталога
\fIКАТ_CHROOT\fR\&.
.RE
.PP
\fB\-r\fR, \fB\-\-remove\-password\fR
.RS 4
Удалить пароль указанной
\fIгруппы\fR\&. Пароль группы будет пустым\&. Только члены группы смогут использовать
\fBnewgrp\fR
для входа в указанную
\fIгруппу\fR\&.
.RE
.PP
\fB\-R\fR, \fB\-\-restrict\fR
.RS 4
Ограничить доступ к указанной
\fIгруппе\fR\&. Пароль группы становится равным \(Fo!\(Fc\&. Только члены группы имеющие пароль смогут использовать
\fBnewgrp\fR
для входа в указанную
\fIгруппу\fR\&.
.RE
.PP
\fB\-A\fR, \fB\-\-administrators\fR \fIпользователь\fR, \&...
.RS 4
Задать список администраторов группы\&.
.RE
.PP
\fB\-M\fR, \fB\-\-members\fR\ \&\fIпользователь\fR, \&...
.RS 4
Задать список членов группы\&.
.RE
.SH "ПРЕДОСТЕРЕЖЕНИЯ"
.PP
Данная утилита работает только с файлом
/etc/groupи /etc/gshadow\&.
Она не может изменить группу NIS или LDAP, это нужно делать на соответствующем сервере\&.
.SH "НАСТРОЙКА"
.PP
На работу этого инструмента влияют следующие переменные настройки из
/etc/login\&.defs:
.PP
\fBENCRYPT_METHOD\fR (строка)
.RS 4
Задаёт системный алгоритм шифрования по умолчанию для шифрования паролей (используется, если алгоритм не указан в командной строке)\&.
.sp
Возможны следующие значения:
\fIDES\fR
(по умолчанию),
\fIMD5\fR, \fISHA256\fR, \fISHA512\fR\&.
.sp
Замечание: этот параметр переопределяет переменную
\fBMD5_CRYPT_ENAB\fR\&.
.RE
.PP
\fBMAX_MEMBERS_PER_GROUP\fR (число)
.RS 4
Максимальное количество членов в записи о группе\&. При достижения максимума заводится новая запись группы (строка) в
/etc/group
(с тем же именем, паролем и тем же GID)\&.
.sp
Значение по умолчанию равно 0, означающее, что ограничения на количество членов в группе нет\&.
.sp
Данная возможность (разделение группы) позволяет ограничить длину строк в файле групп\&. Это полезно для ограничения длины строк групп NIS в 1024 символа\&.
.sp
Если вам нужно такое ограничение, укажите значение 25\&.
.sp
Замечание: разделение групп поддерживается не всеми инструментами (даже в наборе инструментов Shadow)\&. Вы не должны использовать эту переменную, если вам действительно это ненужно\&.
.RE
.PP
\fBMD5_CRYPT_ENAB\fR (логический)
.RS 4
Обозначает, что пароль должен быть зашифрован по алгоритму на основе MD5\&. Если значение равно
\fIyes\fR, то новые пароли будут зашифрованы по алгоритму на основе MD5, совместимому с используемым в новых версиях FreeBSD\&. Он поддерживает пароли неограниченной длины и имеет более длинную строку соли\&. Установите в
\fIno\fR, если вам нужно копировать шифрованные пароли в другие системы, которые не поддерживают новый алгоритм\&. По умолчанию
\fIno\fR\&.
.sp
Эта переменная переопределяется переменной
\fBENCRYPT_METHOD\fR
или любым параметром командной строки, который задаёт алгоритм шифрования\&.
.sp
Эта переменная устарела; используйте
\fBENCRYPT_METHOD\fR\&.
.RE
.PP
\fBSHA_CRYPT_MIN_ROUNDS\fR (число), \fBSHA_CRYPT_MAX_ROUNDS\fR (число)
.RS 4
Если значение
\fBENCRYPT_METHOD\fR
равно
\fISHA256\fR
или
\fISHA512\fR, эта переменная определяет количество раундов SHA, используемых алгоритмом шифрования по умолчанию (если количество раундов не задано в командной строке)\&.
.sp
Увеличение количества раундов повышает сложность подбора пароля простым перебором\&. Но заметим, что при этом для аутентификации пользователей требуется большее количество процессорных ресурсов\&.
.sp
Если не задана, то libc выбирает значение количества раундов по умолчанию (5000)\&.
.sp
Значения должны лежать в диапазоне 1000\-999999999\&.
.sp
Если задано какое\-то одно значение \(em
\fBSHA_CRYPT_MIN_ROUNDS\fR
или
\fBSHA_CRYPT_MAX_ROUNDS\fR
\(em то будет использовано это значение\&.
.sp
Если
\fBSHA_CRYPT_MIN_ROUNDS\fR
>
\fBSHA_CRYPT_MAX_ROUNDS\fR, то используется большее значение\&.
.RE
.SH "ФАЙЛЫ"
.PP
/etc/group
.RS 4
содержит информацию о группах
.RE
.PP
/etc/gshadow
.RS 4
содержит защищаемую информацию о группах
.RE
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBnewgrp\fR(1),
\fBgroupadd\fR(8),
\fBgroupdel\fR(8),
\fBgroupmod\fR(8),
\fBgrpck\fR(8),
\fBgroup\fR(5), \fBgshadow\fR(5)\&.
