'\" t
.\"     Title: newgrp
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 05/09/2014
.\"    Manual: Пользовательские команды
.\"    Source: shadow-utils 4.2
.\"  Language: Russian
.\"
.TH "newgrp" "1" "05/09/2014" "shadow\-utils 4\&.2" "Пользовательские команды"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВАНИЕ"
newgrp \- выполняет регистрацию пользователя в новой группе
.SH "СИНТАКСИС"
.HP \w'\fBnewgrp\fR\ 'u
\fBnewgrp\fR [\-] [\fIгруппа\fR]
.SH "ОПИСАНИЕ"
.PP
Программа
\fBnewgrp\fR
используется для изменения ID текущей группы в работающем сеансе\&. Если указан необязательный параметр
\fB\-\fR, то окружение пользователя будет инициализировано повторно, как если бы пользователь заново вошёл в систему, иначе имеющееся окружение, включая текущий рабочий каталог, изменено не будет\&.
.PP
Программа
\fBnewgrp\fR
изменяет идентификатор текущей реальной группы на заданный или на группу по умолчанию, указанную в файле
/etc/passwd, в случае если имя группы не указано\&. Программа
\fBnewgrp\fR
также пытается добавить группу в список групп пользователя\&. Если пользователь не является суперпользователем, то его попросят ввести пароль, даже если он его не имеет (в файле
/etc/shadow, если для этого пользователя имеется запись в файле теневых паролей, иначе используется файл
/etc/passwd), а группа имеет, или если пользователь не является членом группы, а группа имеет пароль\&. Если пользователь не является членом группы, а у группы пустой пароль, то пользователю будет отказано в доступе\&.
.PP
Если есть запись для этой группы в файле
/etc/gshadow, то список членов и пароль этой группы будут взяты из этого файла, иначе используется запись из файла
/etc/group\&.
.SH "НАСТРОЙКА"
.PP
На работу этого инструмента влияют следующие переменные настройки из
/etc/login\&.defs:
.PP
\fBSYSLOG_SG_ENAB\fR (логический)
.RS 4
Включить протоколирование \(Fosyslog\(Fc действий
\fBsg\fR\&.
.RE
.SH "ФАЙЛЫ"
.PP
/etc/passwd
.RS 4
содержит информацию о пользователях
.RE
.PP
/etc/shadow
.RS 4
содержит защищаемую информацию о пользователях
.RE
.PP
/etc/group
.RS 4
содержит информацию о группах
.RE
.PP
/etc/gshadow
.RS 4
содержит защищаемую информацию о группах
.RE
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBid\fR(1),
\fBlogin\fR(1),
\fBsu\fR(1),
\fBsg\fR(1),
\fBgpasswd\fR(1),
\fBgroup\fR(5), \fBgshadow\fR(5)\&.
