'\" t
.\"     Title: sg
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 05/09/2014
.\"    Manual: Пользовательские команды
.\"    Source: shadow-utils 4.2
.\"  Language: Russian
.\"
.TH "sg" "1" "05/09/2014" "shadow\-utils 4\&.2" "Пользовательские команды"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВАНИЕ"
sg \- выполняет команду с правами другой группы
.SH "СИНТАКСИС"
.HP \w'\fBsg\fR\ 'u
\fBsg\fR [\-] [группа\ [\-c]\ команда]
.SH "ОПИСАНИЕ"
.PP
Команда
\fBsg\fR
работает подобно команде
\fBnewgrp\fR, но в качестве параметра ожидает команду\&. Команда будет выполнена оболочкой
/bin/sh\&. В большинстве оболочек, откуда может запускаться
\fBsg\fR, команду из нескольких слов нужно заключать в кавычки\&. Другим отличием между
\fBnewgrp\fR
и
\fBsg\fR
является то, что некоторые оболочки воспринимают
\fBnewgrp\fR
особенным образом, заменяя себя новым экземпляром оболочки, которую создаёт
\fBnewgrp\fR\&. Этого не происходит с командой
\fBsg\fR, поэтому после завершения работы
\fBsg\fR
вы возвращаетесь в предыдущую группу\&.
.SH "НАСТРОЙКА"
.PP
На работу этого инструмента влияют следующие переменные настройки из
/etc/login\&.defs:
.PP
\fBSYSLOG_SG_ENAB\fR (логический)
.RS 4
Включить протоколирование \(Fosyslog\(Fc действий
\fBsg\fR\&.
.RE
.SH "ФАЙЛЫ"
.PP
/etc/passwd
.RS 4
содержит информацию о пользователях
.RE
.PP
/etc/shadow
.RS 4
содержит защищаемую информацию о пользователях
.RE
.PP
/etc/group
.RS 4
содержит информацию о группах
.RE
.PP
/etc/gshadow
.RS 4
содержит защищаемую информацию о группах
.RE
.SH "СМОТРИТЕ ТАКЖЕ"
.PP
\fBid\fR(1),
\fBlogin\fR(1),
\fBnewgrp\fR(1),
\fBsu\fR(1),
\fBgpasswd\fR(1),
\fBgroup\fR(5), \fBgshadow\fR(5)\&.
