'\" t
.\"     Title: expiry
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 09/05/2014
.\"    Manual: Comandi utente
.\"    Source: shadow-utils 4.2
.\"  Language: Italian
.\"
.TH "EXPIRY" "1" "09/05/2014" "shadow\-utils 4\&.2" "Comandi utente"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NOME"
expiry \- controlla e fa rispettare la scadenza della password
.SH "SINOSSI"
.HP \w'\fBexpiry\fR\ 'u
\fBexpiry\fR \fIopzione\fR
.SH "DESCRIZIONE"
.PP
\fBexpiry\fR
controlla (\fB\-c\fR) la scadenza della password in uso e, se necessario, richiede (\fB\-f\fR) che venga cambiata quando necessario\&. Questo comando pu\(`o essere eseguito da un utente qualsiasi\&.
.SH "OPZIONI"
.PP
Il comando
\fBexpiry\fR
accetta le seguenti opzioni:
.PP
\fB\-c\fR, \fB\-\-check\fR
.RS 4
Controlla la scadenza della password dell\*(Aqutente corrente\&.
.RE
.PP
\fB\-f\fR, \fB\-\-force\fR
.RS 4
Forza un cambio di password se l\*(Aqutente corrente ha una password scaduta\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Mostra un messaggio di aiuto ed esce\&.
.RE
.SH "FILE"
.PP
/etc/passwd
.RS 4
Informazioni sugli account utente\&.
.RE
.PP
/etc/shadow
.RS 4
Informazioni sicure sugli account utente\&.
.RE
.SH "VEDERE ANCHE"
.PP
\fBpasswd\fR(5),
\fBshadow\fR(5)\&.
