'\" t
.\"     Title: suauth
.\"    Author: Marek Micha\(/lkiewicz
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 09.05.2014
.\"    Manual: Dateiformate und konvertierung
.\"    Source: shadow-utils 4.2
.\"  Language: German
.\"
.TH "SUAUTH" "5" "09.05.2014" "shadow\-utils 4\&.2" "Dateiformate und konvertierung"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
suauth \- ausf\(:uhrliche Kontrolldatei f\(:ur su
.SH "\(:UBERSICHT"
.HP \w'\fB/etc/suauth\fR\ 'u
\fB/etc/suauth\fR
.SH "BESCHREIBUNG"
.PP
Wenn der Befehl su aufgerufen wird, wird die Datei
/etc/suauth
ausgewertet\&. Dadurch kann das Verhalten des Befehls su ver\(:andert werden\&. Dies h\(:angt von Folgendem ab:
.sp
.if n \{\
.RS 4
.\}
.nf
      1) auf welchen Benutzer su gerichtet ist
    
.fi
.if n \{\
.RE
.\}
.PP
2) dem Benutzer, der su ausf\(:uhrt (oder einer Gruppe, deren Mitglied er ist)
.PP
Die Datei ist folgenderma\(ssen aufgebaut, wobei Zeilen, die mit einem # beginnen, als Kommentare behandelt und daher ignoriert werden:
.sp
.if n \{\
.RS 4
.\}
.nf
      Herkunfts\-ID:Ziel\-ID:AKTION
    
.fi
.if n \{\
.RE
.\}
.PP
Hierbei kann to\-id
\fIALL\fR, eine Aufz\(:ahlung von Benutzernamen, die durch ein \(Fc,\(Fo getrennt werden, oder
\fIALL EXCEPT\fR, die von einer Aufz\(:ahlung von Benutzernamen gefolgt werden, die durch ein \(Fc,\(Fo getrennt werden, sein\&.
.PP
from\-id hat das gleiche Format wie to\-id mit der Ausnahme, dass zus\(:atzlich
\fIGROUP\fR
zul\(:assig ist\&. Auch
\fIALL EXCEPT GROUP\fR
ist zul\(:assig\&. Nach
\fIGROUP\fR
werden ein oder mehrere Gruppennamen aufgef\(:uhrt, die durch \(Fc,\(Fo getrennt sind\&. Die Haupt\-ID einer Gruppe reicht nicht aus, sondern ein Eintrag in
\fB/etc/group\fR(5)
ist notwendig\&.
.PP
Als Aktion k\(:onnen nur die folgenden Optionen angegeben werden\&.
.PP
\fIDENY\fR
.RS 4
Der Versuch, su auszuf\(:uhren, wird abgebrochen, ehe nach einem Passwort gefragt wird\&.
.RE
.PP
\fINOPASS\fR
.RS 4
Der Versuch, su auszuf\(:uhren, hat automatisch Erfolg\&. Ein Passwort wird nicht abgefragt\&.
.RE
.PP
\fIOWNPASS\fR
.RS 4
Damit der Befehl su Erfolg hat, muss der Benutzer sein eigenes Passwort eingeben\&. Darauf wird er hingewiesen\&.
.RE
.PP
Beachten Sie, dass es sich um drei selbst\(:andige Felder handelt, die durch einen Doppelpunkt getrennt sind\&. Neben den Doppelpunkten darf sich kein Leerzeichen befinden\&. Beachten Sie zudem, dass die Datei von oben nach unten Zeile f\(:ur Zeile durchgegangen wird\&. Die erste Regel, die zutreffend ist, wird angewendet, ohne dass die Datei weiter ausgewertet wird\&. Damit kann ein Systemadministrator eine strenge Kontrolle aus\(:uben\&.
.SH "BEISPIEL"
.sp
.if n \{\
.RS 4
.\}
.nf
      # /etc/suauth\-Beispielsdatei
      #
      # Einige besondere Benutzer d\(:urfen su
      # auf Root mit ihrem eigenen Passwort ausf\(:uhren\&.
      #
      root:chris,birddog:OWNPASS
      #
      # Alle anderen Benutzer d\(:urfen nicht su auf Root
      # ausf\(:uhren, falls sie nicht in der Gruppe wheel
      # sind\&. Dies wird bei BSD so gehandhabt\&.
      #
      root:ALL EXCEPT GROUP wheel:DENY
      #
      # Die Konten terry und birddog geh\(:oren derselben
      # Person\&. Sie k\(:onnen ohne Passwort aufeinander
      # zugreifen\&.
      #
      terry:birddog:NOPASS
      birddog:terry:NOPASS
      #
    
.fi
.if n \{\
.RE
.\}
.SH "DATEIEN"
.PP
/etc/suauth
.RS 4
.RE
.SH "FEHLER"
.PP
Es gibt zahlreiche Fehlerquellen\&. Die Auswertung der Datei ist sehr empfindlich bei Syntaxfehlern, zus\(:atzlichen Leerzeichen (au\(sser am Anfang und Schluss einer Zeile) und dem besonderen Zeichen, das die verschiedenen Felder von einander trennt\&.
.SH "DIAGNOSE"
.PP
Fehler beim Auswerten der Datei werden an
\fBsyslogd\fR(8)
mit der Stufe ERR an das Ger\(:at AUTH gemeldet\&.
.SH "SIEHE AUCH"
.PP
\fBsu\fR(1)\&.
