'\" t
.\"     Title: vipw
.\"    Author: Marek Micha\(/lkiewicz
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 09/05/2014
.\"    Manual: Kommandoer for systemh\(oandtering
.\"    Source: shadow-utils 4.2
.\"  Language: Danish
.\"
.TH "VIPW" "8" "09/05/2014" "shadow\-utils 4\&.2" "Kommandoer for systemh\(oandterin"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAVN"
vipw, vigr \- rediger adgangskoden, gruppe, shadow\-adgangskode\- eller shadow\-gruppe\-fil
.SH "SYNOPSIS"
.HP \w'\fBvipw\fR\ 'u
\fBvipw\fR [\fItilvalg\fR]
.HP \w'\fBvigr\fR\ 'u
\fBvigr\fR [\fItilvalg\fR]
.SH "BESKRIVELSE"
.PP
Kommandoerne
\fBvipw\fR
og
\fBvigr\fR
redigerer filerne
/etc/passwd
og
/etc/group, respektivt\&. Med flaget
\fB\-s\fR
vil de redigere versionerne for Shadow for disse filer,
/etc/shadow
og
/etc/gshadow, respektivt\&. Programmerne vil s\(aette de passende l\(oase for at forhindre fil\(/odel\(aeggelse\&. N\(oar der kigges efter et redigerngsprogram, s\(oa vil programmet \(/ofrst fors\(/oge med milj\(/ovariablen
\fB$VISUAL\fR, derefter milj\(/ovariablen
\fB$EDITOR\fR, og endelig standardredigeringsprogrammet,
\fBvi\fR(1)\&.
.SH "TILVALG"
.PP
Tilvalgene som g\(aelder for kommandoerne
\fBvipw\fR
og
\fBvigr\fR
er:
.PP
\fB\-g\fR, \fB\-\-group\fR
.RS 4
Rediger gruppedatabase\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Vis hj\(aelpeteksten og afslut\&.
.RE
.PP
\fB\-p\fR, \fB\-\-passwd\fR
.RS 4
Rediger passwd\-database\&.
.RE
.PP
\fB\-q\fR, \fB\-\-quiet\fR
.RS 4
Stille tilstand\&.
.RE
.PP
\fB\-R\fR, \fB\-\-root\fR\ \&\fICHROOT_DIR\fR
.RS 4
Brug \(aendringer i mappen
\fICHROOT_DIR\fR
og brug konfigurationsfilerne fra mappen
\fICHROOT_DIR\fR\&.
.RE
.PP
\fB\-s\fR, \fB\-\-shadow\fR
.RS 4
Rediger shadow\- eller gshadow\-database\&.
.RE
.SH "MILJ\(/O"
.PP
\fBVISUEL\fR
.RS 4
Redigeringsprogram der skal bruges\&.
.RE
.PP
\fBREDIGERINGSPROGRAM\fR
.RS 4
Redigeringsprogram der skal bruges hvis
\fBVISUAL\fR
ikke er angivet\&.
.RE
.SH "FILER"
.PP
/etc/group
.RS 4
Information om gruppekonto\&.
.RE
.PP
/etc/gshadow
.RS 4
Information om sikret gruppekonto\&.
.RE
.PP
/etc/passwd
.RS 4
Information om brugerkonto\&.
.RE
.PP
/etc/shadow
.RS 4
Information om sikret brugerkonto\&.
.RE
.SH "SE OGS\(oA"
.PP
\fBvi\fR(1),
\fBgruppe\fR(5),
\fBgshadow\fR(5),
\fBpasswd\fR(5), ,
\fBshadow\fR(5)\&.
