'\" t
.\"     Title: chpasswd
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 09.05.2014
.\"    Manual: Befehle zur Systemverwaltung
.\"    Source: shadow-utils 4.2
.\"  Language: German
.\"
.TH "CHPASSWD" "8" "09.05.2014" "shadow\-utils 4\&.2" "Befehle zur Systemverwaltung"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
chpasswd \- aktualisiert Passw\(:orter im Batch\-Modus
.SH "\(:UBERSICHT"
.HP \w'\fBchpasswd\fR\ 'u
\fBchpasswd\fR [\fIOptionen\fR]
.SH "BESCHREIBUNG"
.PP
Der Befehl
\fBchpasswd\fR
liest eine Liste von Benutzername\-Passwort\-Paaren von der Standardeingabe\&. Damit werden Benutzerdaten aktualisiert\&. Jede Zeile muss folgendes Format haben:
.PP
\fIBenutzername\fR:\fIPasswort\fR
.PP
Das Passwort muss standardm\(:a\(ssig im Klartext angegeben werden und von
\fBchpasswd\fR
verschl\(:usselt\&. Soweit vorhanden, wird auch das Alter des Passworts aktualisiert\&.
.PP
Der standardm\(:a\(ssige Verschl\(:usselungsalgorithmus kann systemweit mit den Variablen
\fBENCRYPT_METHOD\fR
oder
\fBMD5_CRYPT_ENAB\fR
in
/etc/login\&.defs
definiert werden\&. Dieser kann mit den Optionen
\fB\-e\fR,
\fB\-m\fR
oder
\fB\-c\fR
\(:uberschrieben werden\&.
.PP
\fBchpasswd\fR
aktualisiert zun\(:achst alle Passw\(:orter im Arbeitsspeicher und schreibt dann die \(:Anderungen auf das Speichermedium, falls keine Fehler aufgetreten sind\&.
.PP
Dieser Befehl ist f\(:ur den Einsatz in gro\(ssen Umgebungen vorgesehen, in der viele Konten gleichzeitig erstellt werden m\(:ussen\&.
.SH "OPTIONEN"
.PP
Die Optionen, die vom Befehl
\fBchpasswd\fR
unterst\(:utzt werden, sind:
.PP
\fB\-c\fR, \fB\-\-crypt\-method\fR\ \&\fIMETHODE\fR
.RS 4
Definiert die Methode, mit der die Passw\(:orter verschl\(:usselt werden\&.
.sp
Die verf\(:ugbaren Methoden sind DES, MD5, NONE und SHA256 oder SHA512, soweit Ihre libc sie unterst\(:utzt\&.
.sp
Standardm\(:a\(ssig (wenn keine der Optionen
\fB\-c\fR,
\fB\-m\fR
oder
\fB\-e\fR
angegeben wird) wird die Verschl\(:usselungsmethode durch die Variablen
\fBENCRYPT_METHOD\fR
oder
\fBMD5_CRYPT_ENAB\fR
in
/etc/login\&.defs
bestimmt\&.
.RE
.PP
\fB\-e\fR, \fB\-\-encrypted\fR
.RS 4
Passw\(:orter werden verschl\(:usselt angegeben\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
zeigt die Hilfe an und beendet das Programm
.RE
.PP
\fB\-m\fR, \fB\-\-md5\fR
.RS 4
werwendet zur Verschl\(:usselung MD5 anstelle von DES, wenn die Passw\(:orter unverschl\(:usselt angegeben werden
.RE
.PP
\fB\-R\fR, \fB\-\-root\fR\ \&\fICHROOT_VERZ\fR
.RS 4
f\(:uhrt die Ver\(:anderungen in dem Verzeichnis
\fICHROOT_VERZ\fR
durch und verwendet die Konfigurationsdateien aus dem Verzeichnis
\fICHROOT_VERZ\fR
.RE
.PP
\fB\-s\fR, \fB\-\-sha\-rounds\fR\ \&\fIRUNDEN\fR
.RS 4
Verwendet die angegebene Anzahl von Runden, um die Passw\(:orter zu verschl\(:usseln\&.
.sp
Ein Wert von 0 bedeutet, dass das System die Standardanzahl der Runden (5000) f\(:ur die Verschl\(:usselung verwenden wird\&.
.sp
Der Mindestwert ist 1000, der H\(:ochstwert 999\&.999\&.999\&.
.sp
Sie k\(:onnen diese Option nur mit den Verschl\(:usselungsmethoden SHA256 und SHA512 verwenden\&.
.sp
Standardm\(:a\(ssig wird die Anzahl der Runden von den Variablen
\fBSHA_CRYPT_MIN_ROUNDS\fR
und
\fBSHA_CRYPT_MAX_ROUNDS\fR/etc/login\&.defs
bestimmt\&.
.RE
.SH "WARNUNGEN"
.PP
Achten Sie darauf, dass die Rechte und Umask korrekt vergeben sind, um zu verhindern, dass andere Benutzer unverschl\(:usselte Dateien lesen k\(:onnen\&.
.SH "KONFIGURATION"
.PP
Die folgenden Konfigurationsvariablen in
/etc/login\&.defs
beeinflussen das Verhalten dieses Werkzeugs:
.PP
\fBENCRYPT_METHOD\fR (Zeichenkette)
.RS 4
Damit wird der standardm\(:a\(ssige Verschl\(:usselungsalgorithmus, mit dem Passw\(:orter verschl\(:usselt werden, bestimmt (soweit nicht in der Befehlszeile ein Algorithmus angegeben wird)\&.
.sp
Ihm kann einer der folgenden Wert zugewiesen werden:
\fIDES\fR
(default),
\fIMD5\fR, \fISHA256\fR, \fISHA512\fR\&.
.sp
Hinweis: Dieser Parameter \(:uberschreibt die Variable
\fBMD5_CRYPT_ENAB\fR\&.
.RE
.PP
\fBMD5_CRYPT_ENAB\fR (boolesch)
.RS 4
Legt fest, ob Passw\(:orter mit dem auf MD5 beruhenden Algorithmus verschl\(:usselt werden\&. Falls diesem Wert
\fIyes\fR
zugewiesen ist, werden neue Passw\(:orter mit dem auf MD5 beruhenden Algorithmus verschl\(:usselt, der zu dem in der aktuellen Ver\(:offentlichung von FreeBSD eingesetzten Algorithmus kompatibel ist\&. Passw\(:orter k\(:onnen dann beliebig lang sein, auch die Salt\-Zeichenketten sind l\(:anger\&. Setzen Sie diesen Wert auf
\fIno\fR, wenn Sie verschl\(:usselte Passw\(:orter auf ein anderes System kopieren m\(:ochten, das den neuen Algorithmus nicht versteht\&. Der Standardwert ist
\fIno\fR\&.
.sp
Dieser Variable geht die Variable
\fBENCRYPT_METHOD\fR
und eine Option auf der Befehlszeile, mit der der Verschl\(:usselungsalgorithmus bestimmt wird, vor\&.
.sp
Der Einsatz dieser Variable ist veraltet\&. Sie sollten
\fBENCRYPT_METHOD\fR
verwenden\&.
.RE
.PP
\fBSHA_CRYPT_MIN_ROUNDS\fR (Zahl), \fBSHA_CRYPT_MAX_ROUNDS\fR (Zahl)
.RS 4
Wenn
\fBENCRYPT_METHOD\fR
auf
\fISHA256\fR
oder
\fISHA512\fR
gesetzt ist, legt dies die Anzahl der Runden von SHA fest, die standardm\(:a\(ssig vom Verschl\(:usselungsalgorithmus verwendet werden (falls die Anzahl der Runden nicht auf der Befehlszeile angegeben wird)\&.
.sp
Je mehr Runden Sie definieren, umso schwieriger ist es, das Passwort mit sturem Durchprobieren (brute force) zu knacken; umso mehr Rechenleistung wird jedoch auch f\(:ur die Anmeldung eines Benutzers ben\(:otigt\&.
.sp
Falls Sie nichts angeben, wird libc die Standardanzahl der Runden festlegen (5000)\&.
.sp
Die Werte m\(:ussen zwischen 1000\-999\&.999\&.999 liegen\&.
.sp
Falls nur der Wert f\(:ur
\fBSHA_CRYPT_MIN_ROUNDS\fR
oder
\fBSHA_CRYPT_MAX_ROUNDS\fR
festgelegt wird, wird dieser Wert verwendet\&.
.sp
Falls
\fBSHA_CRYPT_MIN_ROUNDS\fR
>
\fBSHA_CRYPT_MAX_ROUNDS\fR, wird der h\(:ohere Wert verwendet\&.
.RE
.SH "DATEIEN"
.PP
/etc/passwd
.RS 4
Informationen zu den Benutzerkonten
.RE
.PP
/etc/shadow
.RS 4
verschl\(:usselte Informationen zu den Benutzerkonten
.RE
.PP
/etc/login\&.defs
.RS 4
Konfiguration der Shadow\-Passwort\-Werkzeugsammlung
.RE
.SH "SIEHE AUCH"
.PP
\fBpasswd\fR(1),
\fBnewusers\fR(8),
\fBlogin.defs\fR(5),\fBuseradd\fR(8)\&.
