'\" t
.\"     Title: nologin
.\"    Author: Nicolas Fran\(,cois <nicolas.francois@centraliens.net>
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 09.05.2014
.\"    Manual: Befehle zur Systemverwaltung
.\"    Source: shadow-utils 4.2
.\"  Language: German
.\"
.TH "NOLOGIN" "8" "09.05.2014" "shadow\-utils 4\&.2" "Befehle zur Systemverwaltung"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
nologin \- lehnt h\(:oflich eine Anmeldung ab
.SH "\(:UBERSICHT"
.HP \w'\fBnologin\fR\ 'u
\fBnologin\fR
.SH "BESCHREIBUNG"
.PP
Der Befehl
\fBnologin\fR
zeigt die Meldung an, dass ein Konto nicht verf\(:ugbar ist, und gibt einen Wert von ungleich Null zur\(:uck\&. Dies ist als Einsatz f\(:ur das Shell\-Feld bei abgeschalteten Konten vorgesehen\&.
.PP
Wie Sie alle Konten abschalten, erfahren Sie unter
\fBnologin\fR(5)\&.
.SH "SIEHE AUCH"
.PP
\fBlogin\fR(1),
\fBnologin\fR(5)\&.
.SH "GESCHICHTE"
.PP
Der Befehl
\fBnologin\fR
tauchte erstmals in BSD 4\&.4 auf\&.
