'\" t
.\"     Title: pwck
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 09.05.2014
.\"    Manual: Befehle zur Systemverwaltung
.\"    Source: shadow-utils 4.2
.\"  Language: German
.\"
.TH "PWCK" "8" "09.05.2014" "shadow\-utils 4\&.2" "Befehle zur Systemverwaltung"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
pwck \- \(:uberpr\(:uft die Stimmigkeit der Passwortdateien
.SH "\(:UBERSICHT"
.HP \w'\fBpwck\fR\ 'u
\fBpwck\fR [Optionen] [\fIpasswd\fR\ [\ \fIshadow\fR\ ]]
.SH "BESCHREIBUNG"
.PP
Der Befehl
\fBpwck\fR
\(:uberpr\(:uft die Stimmigkeit der Benutzer\- und Authentifizierungsdaten\&. Alle Eintr\(:age in
/etc/passwd
und
/etc/shadow
werden darauf \(:uberpr\(:uft, ob der Eintrag das richtige Format hat und g\(:ultige Daten enth\(:alt\&. Der Benutzer wird aufgefordert, Eintr\(:age zu l\(:oschen, die falsch formatiert sind oder andere unbehebbare Fehler enthalten\&.
.PP
Es wird \(:uberpr\(:uft, ob jeder Eintrag folgende Eigenschaften aufweist:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
die richtige Anzahl von Feldern
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
einen eindeutigen und g\(:ultigen Benutzernamen
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
eine g\(:ultige Benutzer\- und Gruppenkennung
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
eine g\(:ultige Hauptgruppe
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
ein g\(:ultiges Home\-Verzeichnis
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
eine g\(:ultige Anmelde\-Shell
.RE
.PP
Eine \(:Uberpr\(:ufung von
shadow
findet statt, wenn ein zweiter Parameter angegeben wird oder auf dem System
/etc/shadow
existiert\&.
.PP
Diese Tests umfassen Folgendes:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
ob jedem Eintrag in passwd ein Eintrag in shadow entspricht und umgekehrt
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
ob die Passw\(:orter in der Shadow\-Datei niedergelegt sind
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
ob die shadow\-Eintr\(:age die richtige Anzahl von Feldern haben
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
ob die Shadow\-Eintr\(:age in shadow eindeutig sind
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
dass das Datum der letzten Passwort\(:anderung nicht in der Zukunft liegt
.RE
.PP
Fehler bei der \(:Uberpr\(:ufung der richtigen Anzahl der Felder und des eindeutigen Benutzernames sind schwerwiegend\&. Wenn ein Eintrag die falsche Anzahl von Feldern ausweist, wird der Benutzer aufgefordert, die gesamte Zeile zu l\(:oschen\&. Wenn dies der Benutzer ablehnt, werden alle weiteren Tests ausgelassen\&. Bei einem Eintrag mit einem mehrfach verwendeten Benutzernamen wird der Benutzer aufgefordert, diesen Eintrag zu l\(:oschen\&. Sollte er dies ablehnen, werden dennoch die \(:ubrigen Test ausgef\(:uhrt\&. Bei allen anderen Fehlern wird eine Warnung abgegeben und der Benutzer aufgefordert, den Fehler mittels des Befehls
\fBusermod\fR
zu beheben\&.
.PP
Die Befehle, welche die Datei
/etc/passwd
bearbeiten, k\(:onnen falsche oder doppelte Eintr\(:age nicht ver\(:andern\&. In solchen F\(:allen sollte
\fBpwck\fR
verwendet werden, um den betreffenden Eintrag zu entfernen\&.
.SH "OPTIONEN"
.PP
Die Optionen
\fB\-r\fR
und
\fB\-s\fR
k\(:onnen nicht zusammen verwendet werden\&.
.PP
Die Optionen, die vom Befehl
\fBpwck\fR
unterst\(:utzt werden, sind:
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
zeigt die Hilfe an und beendet das Programm
.RE
.PP
\fB\-q\fR, \fB\-\-quiet\fR
.RS 4
meldet nur Fehler\&. Warnungen, die keine Handlung des Benutzers erfordern, werden nicht angezeigt
.RE
.PP
\fB\-r\fR, \fB\-\-read\-only\fR
.RS 4
f\(:uhrt den Befehl
\fBpwck\fR
im Modus Nur\-Lesen aus
.RE
.PP
\fB\-R\fR, \fB\-\-root\fR\ \&\fICHROOT_VERZ\fR
.RS 4
f\(:uhrt die Ver\(:anderungen in dem Verzeichnis
\fICHROOT_VERZ\fR
durch und verwendet die Konfigurationsdateien aus dem Verzeichnis
\fICHROOT_VERZ\fR
.RE
.PP
\fB\-s\fR, \fB\-\-sort\fR
.RS 4
ordnet die Eintr\(:age in
/etc/passwd
und
/etc/shadow
nach der UID
.RE
.PP
Standardm\(:a\(ssig bearbeitet
\fBpwck\fR
die Dateien
/etc/passwd
und
/etc/shadow\&. Der Benutzer kann andere Dateien mit den Parametern
\fIpasswd\fR
und
\fIshadow\fR
ausw\(:ahlen\&.
.SH "KONFIGURATION"
.PP
Die folgenden Konfigurationsvariablen in
/etc/login\&.defs
beeinflussen das Verhalten dieses Werkzeugs:
.PP
\fBPASS_MAX_DAYS\fR (Zahl)
.RS 4
Die maximale Anzahl von Tagen, f\(:ur die ein Passwort verwendet werden darf\&. Wenn das Passwort \(:alter ist, wird ein Wechsel des Passworts erzwungen\&. Falls nicht angegeben, wird \-1 angenommen (was zur Folge hat, dass diese Beschr\(:ankung abgeschaltet ist)\&.
.RE
.PP
\fBPASS_MIN_DAYS\fR (Zahl)
.RS 4
Die Mindestanzahl von Tagen, bevor ein Wechsel des Passworts zugelassen wird\&. Ein vorheriger Versuch, das Passwort zu \(:andern, wird abgelehnt\&. Falls nicht angegeben, wird \-1 angenommen (was zur Folge hat, dass diese Beschr\(:ankung abgeschaltet ist)\&.
.RE
.PP
\fBPASS_WARN_AGE\fR (Zahl)
.RS 4
Die Anzahl von Tagen, an denen der Benutzer vorgewarnt wird, bevor das Passwort verf\(:allt\&. Eine Null bedeutet, dass eine Warnung nur am Tag des Verfalls ausgegeben wird\&. Ein negativer Wert bedeutet, dass keine Vorwarnung erfolgt\&. Falls nicht angegeben, wird keine Vorwarnung ausgegeben\&.
.RE
.SH "DATEIEN"
.PP
/etc/group
.RS 4
Informationen zu den Gruppenkonten
.RE
.PP
/etc/passwd
.RS 4
Informationen zu den Benutzerkonten
.RE
.PP
/etc/shadow
.RS 4
verschl\(:usselte Informationen zu den Benutzerkonten
.RE
.SH "R\(:UCKGABEWERTE"
.PP
Der Befehl
\fBpwck\fR
gibt beim Beenden folgende Werte zur\(:uck:
.PP
\fI0\fR
.RS 4
Erfolg
.RE
.PP
\fI1\fR
.RS 4
unzul\(:assige Syntax f\(:ur diesen Befehl
.RE
.PP
\fI2\fR
.RS 4
ein oder mehrere fehlerhafte Passworteintr\(:age
.RE
.PP
\fI3\fR
.RS 4
Die Passwortdatei kann nicht ge\(:offnet werden\&.
.RE
.PP
\fI4\fR
.RS 4
Die Passwortdatei kann nicht gesperret werden\&.
.RE
.PP
\fI5\fR
.RS 4
Die Passwortdatei kann nicht aktualisieren werden\&.
.RE
.PP
\fI6\fR
.RS 4
Die Passwortdatei kann nicht sortieren werden\&.
.RE
.SH "SIEHE AUCH"
.PP
\fBgroup\fR(5),
\fBgrpck\fR(8),
\fBpasswd\fR(5),
\fBshadow\fR(5),
\fBusermod\fR(8)\&.
