'\" t
.\"     Title: grpck
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 09-05-2014
.\"    Manual: Systemhanteringskommandon
.\"    Source: shadow-utils 4.2
.\"  Language: Swedish
.\"
.TH "GRPCK" "8" "09-05-2014" "shadow\-utils 4\&.2" "Systemhanteringskommandon"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAMN"
grpck \- validera integriteten f\(:or gruppfiler
.SH "SYNOPSIS"
.HP \w'\fBgrpck\fR\ 'u
\fBgrpck\fR [flaggor] [\fIgrupp\fR\ [\ \fIshadow\fR\ ]]
.SH "BESKRIVNING"
.PP
The
\fBgrpck\fR
command verifies the integrity of the groups information\&. It checks that all entries in
/etc/groupand /etc/gshadow
have the proper format and contain valid data\&. The user is prompted to delete entries that are improperly formatted or which have other uncorrectable errors\&.
.PP
Kontroller g\(:ors f\(:or att validera att varje post har:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
korrekt antal f\(:alt
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
a unique and valid group name
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
a valid group identifier
(/etc/group only)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
a valid list of members
and administrators
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
a corresponding entry in the
/etc/gshadow
file (respectively
/etc/group
for the
gshadow
checks)
.RE
.PP
The checks for correct number of fields and unique group name are fatal\&. If an entry has the wrong number of fields, the user will be prompted to delete the entire line\&. If the user does not answer affirmatively, all further checks are bypassed\&. An entry with a duplicated group name is prompted for deletion, but the remaining checks will still be made\&. All other errors are warnings and the user is encouraged to run the
\fBgroupmod\fR
command to correct the error\&.
.PP
The commands which operate on the
/etc/groupand /etc/gshadow files
are not able to alter corrupted or duplicated entries\&.
\fBgrpck\fR
should be used in those circumstances to remove the offending entries\&.
.SH "FLAGGOR"
.PP
The
\fB\-r\fR
and
\fB\-s\fR
options cannot be combined\&.
.PP
The options which apply to the
\fBgrpck\fR
command are:
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Visa hj\(:alpmeddelande och avsluta\&.
.RE
.PP
\fB\-r\fR, \fB\-\-read\-only\fR
.RS 4
Execute the
\fBgrpck\fR
command in read\-only mode\&. This causes all questions regarding changes to be answered
\fIno\fR
without user intervention\&.
.RE
.PP
\fB\-R\fR, \fB\-\-root\fR\ \&\fICHROOT_DIR\fR
.RS 4
Apply changes in the
\fICHROOT_DIR\fR
directory and use the configuration files from the
\fICHROOT_DIR\fR
directory\&.
.RE
.PP
\fB\-s\fR, \fB\-\-sort\fR
.RS 4
Sort entries in
/etc/groupand /etc/gshadow
by GID\&.
.RE
.PP
By default,
\fBgrpck\fR
operates on
/etc/groupand /etc/gshadow\&. The user may select alternate files with the
\fIgroup\fRand \fIshadow\fR parameters\&.
.SH "CONFIGURATION"
.PP
The following configuration variables in
/etc/login\&.defs
change the behavior of this tool:
.PP
\fBMAX_MEMBERS_PER_GROUP\fR (number)
.RS 4
Maximum members per group entry\&. When the maximum is reached, a new group entry (line) is started in
/etc/group
(with the same name, same password, and same GID)\&.
.sp
The default value is 0, meaning that there are no limits in the number of members in a group\&.
.sp
This feature (split group) permits to limit the length of lines in the group file\&. This is useful to make sure that lines for NIS groups are not larger than 1024 characters\&.
.sp
If you need to enforce such limit, you can use 25\&.
.sp
Note: split groups may not be supported by all tools (even in the Shadow toolsuite)\&. You should not use this variable unless you really need it\&.
.RE
.SH "FILER"
.PP
/etc/group
.RS 4
Gruppkontoinformation\&.
.RE
.PP
/etc/gshadow
.RS 4
S\(:aker gruppkontoinformation\&.
.RE
.PP
/etc/passwd
.RS 4
Anv\(:andarkontoinformation\&.
.RE
.SH "AVSLUTNINGSV\(:ARDEN"
.PP
Kommandot
\fBgrpck\fR
avslutas med f\(:oljande v\(:arden:
.PP
\fI0\fR
.RS 4
lyckad
.RE
.PP
\fI1\fR
.RS 4
ogiltig kommandosyntax
.RE
.PP
\fI2\fR
.RS 4
en eller flera felaktiga grupposter
.RE
.PP
\fI3\fR
.RS 4
kan inte \(:oppna gruppfiler
.RE
.PP
\fI4\fR
.RS 4
kan inte l\(oasa gruppfiler
.RE
.PP
\fI5\fR
.RS 4
kan inte uppdatera gruppfiler
.RE
.SH "SE OCKS\(oA"
.PP
\fBgroup\fR(5),
\fBgroupmod\fR(8),
\fBgshadow\fR(5),\fBpasswd\fR(5),
\fBpwck\fR(8),
\fBshadow\fR(5)\&.
