'\" t
.\"     Title: lastlog
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 09-05-2014
.\"    Manual: Systemhanteringskommandon
.\"    Source: shadow-utils 4.2
.\"  Language: Swedish
.\"
.TH "LASTLOG" "8" "09-05-2014" "shadow\-utils 4\&.2" "Systemhanteringskommandon"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAMN"
lastlog \- reports the most recent login of all users or of a given user
.SH "SYNOPSIS"
.HP \w'\fBlastlog\fR\ 'u
\fBlastlog\fR [\fIflaggor\fR]
.SH "BESKRIVNING"
.PP
\fBlastlog\fR
formats and prints the contents of the last login log
/var/log/lastlog
file\&. The
\fIlogin\-name\fR,
\fIport\fR, and
\fIlast login time\fR
will be printed\&. The default (no flags) causes lastlog entries to be printed, sorted by their order in
/etc/passwd\&.
.SH "FLAGGOR"
.PP
Flaggorna som g\(:aller f\(:or kommandot
\fBlastlog\fR
\(:ar:
.PP
\fB\-b\fR, \fB\-\-before\fR\ \&\fIDAGAR\fR
.RS 4
Print only lastlog records older than
\fIDAYS\fR\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Visa hj\(:alpmeddelande och avsluta\&.
.RE
.PP
\fB\-R\fR, \fB\-\-root\fR\ \&\fICHROOT_DIR\fR
.RS 4
Apply changes in the
\fICHROOT_DIR\fR
directory and use the configuration files from the
\fICHROOT_DIR\fR
directory\&.
.RE
.PP
\fB\-t\fR, \fB\-\-time\fR\ \&\fIDAGAR\fR
.RS 4
Print the lastlog records more recent than
\fIDAYS\fR\&.
.RE
.PP
\fB\-u\fR, \fB\-\-user\fR\ \&\fILOGIN\fR|\fIRANGE\fR
.RS 4
Print the lastlog record of the specified user(s)\&.
.sp
The users can be specified by a login name, a numerical user ID, or a
\fIRANGE\fR
of users\&. This
\fIRANGE\fR
of users can be specified with a min and max values (\fIUID_MIN\-UID_MAX\fR), a max value (\fI\-UID_MAX\fR), or a min value (\fIUID_MIN\-\fR)\&.
.RE
.PP
If the user has never logged in the message
\fI** Never logged in**\fR
will be displayed instead of the port and time\&.
.PP
Only the entries for the current users of the system will be displayed\&. Other entries may exist for users that were deleted previously\&.
.SH "NOTERA"
.PP
The
lastlog
file is a database which contains info on the last login of each user\&. You should not rotate it\&. It is a sparse file, so its size on the disk is usually much smaller than the one shown by "\fBls \-l\fR" (which can indicate a really big file if you have in
passwd
users with a high UID)\&. You can display its real size with "\fBls \-s\fR"\&.
.SH "FILER"
.PP
/var/log/lastlog
.RS 4
Databastider f\(:or tidigare anv\(:andarinloggningar\&.
.RE
.SH "T\(:ANK P\(oA"
.PP
Large gaps in UID numbers will cause the lastlog program to run longer with no output to the screen (i\&.e\&. if in lastlog database there is no entries for users with UID between 170 and 800 lastlog will appear to hang as it processes entries with UIDs 171\-799)\&.
