'\" t
.\"     Title: logoutd
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 09-05-2014
.\"    Manual: Systemhanteringskommandon
.\"    Source: shadow-utils 4.2
.\"  Language: Swedish
.\"
.TH "LOGOUTD" "8" "09-05-2014" "shadow\-utils 4\&.2" "Systemhanteringskommandon"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAMN"
logoutd \- enforce login time restrictions
.SH "SYNOPSIS"
.HP \w'\fBlogoutd\fR\ 'u
\fBlogoutd\fR
.SH "BESKRIVNING"
.PP
\fBlogoutd\fR
enforces the login time and port restrictions specified in
/etc/porttime\&.
\fBlogoutd\fR
should be started from
/etc/rc\&. The
/var/run/utmp
file is scanned periodically and each user name is checked to see if the named user is permitted on the named port at the current time\&. Any login session which is violating the restrictions in
/etc/porttime
is terminated\&.
.SH "FILER"
.PP
/etc/porttime
.RS 4
Fil som inneh\(oaller port\(oatkomst
.RE
.PP
/var/run/utmp
.RS 4
Lista p\(oa aktuella inloggningssessioner\&.
.RE
