'\" t
.\"     Title: nologin
.\"    Author: Nicolas Fran\(,cois <nicolas.francois@centraliens.net>
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 09-05-2014
.\"    Manual: Systemhanteringskommandon
.\"    Source: shadow-utils 4.2
.\"  Language: Swedish
.\"
.TH "NOLOGIN" "8" "09-05-2014" "shadow\-utils 4\&.2" "Systemhanteringskommandon"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAMN"
nologin \- v\(:agra sn\(:allt en inloggning
.SH "SYNOPSIS"
.HP \w'\fBnologin\fR\ 'u
\fBnologin\fR
.SH "BESKRIVNING"
.PP
The
\fBnologin\fR
command displays a message that an account is not available and exits non\-zero\&. It is intended as a replacement shell field for accounts that have been disabled\&.
.PP
F\(:or att inaktivera alla inloggningar, unders\(:ok
\fBnologin\fR(5)\&.
.SH "SE OCKS\(oA"
.PP
\fBlogin\fR(1),
\fBnologin\fR(5)\&.
.SH "HISTORY"
.PP
The
\fBnologin\fR
command appearred in BSD 4\&.4\&.
