'\" t
.\"     Title: newgrp
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 09/05/2014
.\"    Manual: User Commands
.\"    Source: shadow-utils 4.2
.\"  Language: Danish
.\"
.TH "NEWGRP" "1" "09/05/2014" "shadow\-utils 4\&.2" "User Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAVN"
newgrp \- log ind p\(oa en ny gruppe
.SH "SYNOPSIS"
.HP \w'\fBnewgrp\fR\ 'u
\fBnewgrp\fR [\-] [\fIgroup\fR]
.SH "BESKRIVELSE"
.PP
Kommandoen
\fBnewgrp\fR
bruges til at \(aendre den aktuelle grupp\-id under en logindsession\&. Hvis det valgfrie flag
\fB\-\fR
er angivet, s\(oa vil brugerens milj\(/o blive geninitialiseres som om at brugeren havde logget ind, ellers bevares det aktuelle milj\(/o, inklusiv aktuel arbejdsmappe, u\(aendret\&.
.PP
\fBnewgrp\fR
changes the current real group ID to the named group, or to the default group listed in
/etc/passwd
if no group name is given\&.
\fBnewgrp\fR
also tries to add the group to the user groupset\&. If not root, the user will be prompted for a password if she does not have a password (in
/etc/shadow
if this user has an entry in the shadowed password file, or in
/etc/passwd
otherwise) and the group does, or if the user is not listed as a member and the group has a password\&. The user will be denied access if the group password is empty and the user is not listed as a member\&.
.PP
If there is an entry for this group in
/etc/gshadow, then the list of members and the password of this group will be taken from this file, otherwise, the entry in
/etc/group
is considered\&.
.SH "KONFIGURATION"
.PP
De f\(/olgende konfigurationsvariabler i
/etc/login\&.defs
\(aendrer opf\(/orelsen for dette v\(aerkt\(/oj:
.PP
\fBSYSLOG_SG_ENAB\fR (boolean)
.RS 4
Enable "syslog" logging of
\fBsg\fR
activity\&.
.RE
.SH "FILER"
.PP
/etc/passwd
.RS 4
Information om brugerkonto\&.
.RE
.PP
/etc/shadow
.RS 4
Information om sikret brugerkonto\&.
.RE
.PP
/etc/group
.RS 4
Information om gruppekonto\&.
.RE
.PP
/etc/gshadow
.RS 4
Information om sikret gruppekonto\&.
.RE
.SH "SE OGS\(oA"
.PP
\fBid\fR(1),
\fBlogin\fR(1),
\fBsu\fR(1),
\fBsg\fR(1),
\fBgpasswd\fR(1),
\fBgroup\fR(5), \fBgshadow\fR(5)\&.
