'\" t
.\"     Title: gshadow
.\"    Author: Nicolas Fran\(,cois <nicolas.francois@centraliens.net>
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 09-05-2014
.\"    Manual: Filformat och konversioner
.\"    Source: shadow-utils 4.2
.\"  Language: Swedish
.\"
.TH "GSHADOW" "5" "09-05-2014" "shadow\-utils 4\&.2" "Filformat och konversioner"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAMN"
gshadow \- skuggad gruppfil
.SH "BESKRIVNING"
.PP
/etc/gshadow
contains the shadowed information for group accounts\&.
.PP
Denna fil f\(oar inte vara l\(:asbar av vanliga anv\(:andare om l\(:osenordss\(:akerheten ska uppr\(:atth\(oallas\&.
.PP
Each line of this file contains the following colon\-separated fields:
.PP
\fBgruppnamn\fR
.RS 4
It must be a valid group name, which exist on the system\&.
.RE
.PP
\fBkrypterat l\(:osenord\fR
.RS 4
Referera till
\fBcrypt\fR(3)
f\(:or detaljer om hur denna str\(:ang tolkas\&.
.sp
If the password field contains some string that is not a valid result of
\fBcrypt\fR(3), for instance ! or *, users will not be able to use a unix password to access the group (but group members do not need the password)\&.
.sp
The password is used when an user who is not a member of the group wants to gain the permissions of this group (see
\fBnewgrp\fR(1))\&.
.sp
This field may be empty, in which case only the group members can gain the group permissions\&.
.sp
A password field which starts with a exclamation mark means that the password is locked\&. The remaining characters on the line represent the password field before the password was locked\&.
.sp
This password supersedes any password specified in
/etc/group\&.
.RE
.PP
\fBadministrators\fR
.RS 4
It must be a comma\-separated list of user names\&.
.sp
Administrators can change the password or the members of the group\&.
.sp
Administrators also have the same permissions as the members (see below)\&.
.RE
.PP
\fBmembers\fR
.RS 4
It must be a comma\-separated list of user names\&.
.sp
Members can access the group without being prompted for a password\&.
.sp
You should use the same list of users as in
/etc/group\&.
.RE
.SH "FILER"
.PP
/etc/group
.RS 4
Gruppkontoinformation\&.
.RE
.PP
/etc/gshadow
.RS 4
S\(:aker gruppkontoinformation\&.
.RE
.SH "SE OCKS\(oA"
.PP
\fBgpasswd\fR(5),
\fBgroup\fR(5),
\fBgrpck\fR(8),
\fBgrpconv\fR(8),
\fBnewgrp\fR(1)\&.
