'\" t
.\"     Title: passwd
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 09-05-2014
.\"    Manual: Filformat och konversioner
.\"    Source: shadow-utils 4.2
.\"  Language: Swedish
.\"
.TH "PASSWD" "5" "09-05-2014" "shadow\-utils 4\&.2" "Filformat och konversioner"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAMN"
passwd \- l\(:osenordsfilen
.SH "BESKRIVNING"
.PP
/etc/passwd
inneh\(oaller en rad f\(:or varje anv\(:andarkonto men sju f\(:alt separerade med kolontecken (\(rq:\(rq)\&. Dessa f\(:alt \(:ar:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
inloggningsnamn
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
valfritt krypterat l\(:osenord
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
numeriskt anv\(:andar\-id
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
numeriskt grupp\-id
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
anv\(:andarnamn eller kommentarsf\(:alt
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
anv\(:andarens hemkatalog
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
optional user command interpreter
.RE
.PP
The encrypted password field may be blank, in which case no password is required to authenticate as the specified login name\&. However, some applications which read the
/etc/passwd
file may decide not to permit
\fIany\fR
access at all if the
\fIpassword\fR
field is blank\&. If the
\fIpassword\fR
field is a lower\-case
\(rqx\(rq, then the encrypted password is actually stored in the
\fBshadow\fR(5)
file instead; there
\fImust\fR
be a corresponding line in the
/etc/shadow
file, or else the user account is invalid\&. If the
\fIpassword\fR
field is any other string, then it will be treated as an encrypted password, as specified by
\fBcrypt\fR(3)\&.
.PP
The comment field is used by various system utilities, such as
\fBfinger\fR(1)\&.
.PP
The home directory field provides the name of the initial working directory\&. The
\fBlogin\fR
program uses this information to set the value of the
\fB$HOME\fR
environmental variable\&.
.PP
The command interpreter field provides the name of the user\*(Aqs command language interpreter, or the name of the initial program to execute\&. The
\fBlogin\fR
program uses this information to set the value of the
\fB$SHELL\fR
environmental variable\&. If this field is empty, it defaults to the value
/bin/sh\&.
.SH "FILER"
.PP
/etc/passwd
.RS 4
Anv\(:andarkontoinformation\&.
.RE
.PP
/etc/shadow
.RS 4
optional encrypted password file
.RE
.PP
/etc/passwd\-
.RS 4
Backup file for /etc/passwd\&.
.sp
Note that this file is used by the tools of the shadow toolsuite, but not by all user and password management tools\&.
.RE
.SH "SE OCKS\(oA"
.PP
\fBcrypt\fR(3),
\fBgetent\fR(1),
\fBgetpwnam\fR(3),
\fBlogin\fR(1),
\fBpasswd\fR(1),
\fBpwck\fR(8),
\fBpwconv\fR(8),
\fBpwunconv\fR(8),
\fBshadow\fR(5),
\fBsu\fR(1),
\fBsulogin\fR(8)\&.
