#!/usr/bin/expect

set timeout 2
expect_after default {puts "\nFAIL"; exit 1}

spawn /bin/sh
expect "# "

send "grpck\r"
expect "invalid group file entry"
expect "delete line 'foo:x:-1:'? "
send "yes\r"
expect "no matching group file entry in /etc/group"
expect "delete line 'foo:*::'? "
send "yes\r"
expect "grpck: the files have been updated"
expect "# "
send "echo \$?\r"
expect "2"
send "exit\r"
puts "OK\n"
exit 0
