'\" t
.\"     Title: gshadow
.\"    Author: Nicolas Fran\(,cois <nicolas.francois@centraliens.net>
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 09/05/2014
.\"    Manual: File Formats and Conversions
.\"    Source: shadow-utils 4.2
.\"  Language: Danish
.\"
.TH "GSHADOW" "5" "09/05/2014" "shadow\-utils 4\&.2" "File Formats and Conversions"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAVN"
gshadow \- shadowed group file
.SH "BESKRIVELSE"
.PP
/etc/gshadow
contains the shadowed information for group accounts\&.
.PP
This file must not be readable by regular users if password security is to be maintained\&.
.PP
Each line of this file contains the following colon\-separated fields:
.PP
\fBgruppenavn\fR
.RS 4
Det skal v\(aere et gyldigt gruppenavn, som findes p\(oa systemet\&.
.RE
.PP
\fBencrypted password\fR
.RS 4
Refer to
\fBcrypt\fR(3)
for details on how this string is interpreted\&.
.sp
If the password field contains some string that is not a valid result of
\fBcrypt\fR(3), for instance ! or *, users will not be able to use a unix password to access the group (but group members do not need the password)\&.
.sp
The password is used when an user who is not a member of the group wants to gain the permissions of this group (see
\fBnewgrp\fR(1))\&.
.sp
This field may be empty, in which case only the group members can gain the group permissions\&.
.sp
A password field which starts with a exclamation mark means that the password is locked\&. The remaining characters on the line represent the password field before the password was locked\&.
.sp
This password supersedes any password specified in
/etc/group\&.
.RE
.PP
\fBadministratorer\fR
.RS 4
Det skal v\(aere en kommaadskilt liste af brugernavne\&.
.sp
Administratorer kan \(aendre adgangskoden eller medlemmerne af gruppen\&.
.sp
Administratorer har ogs\(oa de samme rettigheder som medlemmerne (se nedenfor)\&.
.RE
.PP
\fBmedlemmer\fR
.RS 4
Det skal v\(aere en kommaadskilt liste af brugernavne\&.
.sp
Medlemmer kan tilg\(oa gruppen uden at blive spurgt efter en adgangskode\&.
.sp
Du skal bruge den samme liste over brugere som i
/etc/group\&.
.RE
.SH "FILER"
.PP
/etc/group
.RS 4
Information om gruppekonto\&.
.RE
.PP
/etc/gshadow
.RS 4
Information om sikret gruppekonto\&.
.RE
.SH "SE OGS\(oA"
.PP
\fBgpasswd\fR(5),
\fBgroup\fR(5),
\fBgrpck\fR(8),
\fBgrpconv\fR(8),
\fBnewgrp\fR(1)\&.
