'\" t
.\"     Title: porttime
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 09/05/2014
.\"    Manual: Formati di file e conversioni
.\"    Source: shadow-utils 4.2
.\"  Language: Italian
.\"
.TH "PORTTIME" "5" "09/05/2014" "shadow\-utils 4\&.2" "Formati di file e conversioni"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NOME"
porttime \- file delle porte e degli orari d\*(Aqaccesso
.SH "DESCRIZIONE"
.PP
\fIporttime\fR
contiene un elenco di device tty, nomi utente e orari di accesso permessi\&.
.PP
Ciascuna voce \(`e composta da tre campi separati da due punti\&. Il primo \(`e un elenco di device tty, separati da virgole, oppure un asterisco per indicare che la voce corrisponde a qualsiasi device\&. Il secondo campo \(`e un elenco di nomi utente, separati da virgole, oppure un asterisco per indicare che la voce corrisponde ad ogni utente\&. Il terzo campo \(`e un elenco degli orari, separati da virgole, in cui \(`e consentito l\*(Aqaccesso\&.
.PP
Un orario di accesso consiste in zero o pi\(`u giorni della settimana abbreviati in
\fIMo\fR
(luned\(`i),
\fITu\fR,
\fIWe\fR,
\fITh\fR,
\fIFr\fR,
\fISa\fR
e
\fISu\fR
(domenica), seguiti da una coppia di orari, separati da un trattino\&. L\*(Aqabbreviazione
\fIWk\fR
rappresenta tutti i giorni da luned\(`i a venerd\(`i, mentre
\fIAl\fR
indica tutti i giorni della settimana\&. Se non si specifica alcun giorno, viene usato implicitamente
\fIAl\fR\&.
.SH "ESEMPI"
.PP
La voce seguente permette l\*(Aqaccesso all\*(Aqutente
\fBjfh\fR
da qualsiasi porta durante i giorni lavorativi dalle 9 alle 17\&.
.PP
*:jfh:Wk0900\-1700
.PP
Le voci seguenti permettono l\*(Aqaccesso solo agli utenti
\fIroot\fR
e
\fIoper\fR
da
/dev/console
a qualsiasi ora\&. Qui viene mostrato come il file
/etc/porttime
sia una lista ordinata di orari d\*(Aqaccesso: ogni altro utente corrisponderebbe alla seconda voce, che impedisce l\*(Aqaccesso in qualsiasi orario\&.
.sp
.if n \{\
.RS 4
.\}
.nf
      console:root,oper:Al0000\-2400
      console:*:
    
.fi
.if n \{\
.RE
.\}
.PP
La voce seguente permette l\*(Aqaccesso all\*(Aqutente
\fIgames\fR
da qualsiasi porta durante gli orari non lavorativi\&.
.PP
*:games:Wk1700\-0900,SaSu0000\-2400
.SH "FILE"
.PP
/etc/porttime
.RS 4
File contenente gli accessi alle porte\&.
.RE
.SH "VEDERE ANCHE"
.PP
\fBlogin\fR(1)\&.
