'\" t
.\"     Title: groupmems
.\"    Author: George Kraft, IV
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 09/05/2014
.\"    Manual: Comandi per la gestione del sistema
.\"    Source: shadow-utils 4.2
.\"  Language: Italian
.\"
.TH "GROUPMEMS" "8" "09/05/2014" "shadow\-utils 4\&.2" "Comandi per la gestione del si"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NOME"
groupmems \- membri amministratori del gruppo primario dell\*(Aqutente
.SH "SINOSSI"
.HP \w'\fBgroupmems\fR\ 'u
\fBgroupmems\fR \-a\ \fIuser_name\fR | \-d\ \fIuser_name\fR | [\-g\ \fIgroup_name\fR] | \-l | \-p 
.SH "DESCRIZIONE"
.PP
Il comando
\fBgroupmems\fR
permette a utenti di amministrare la lista di membri del proprio gruppo senza richiedere i privilegi di amministratore\&. Il comando
\fBgroupmems\fR
\(`e per sistemi che configurano gli utenti perch\('e siano in un gruppo primario con lo stesso nome dell\*(Aqutente (esempio: guest/guest)\&.
.PP
Solo il super utente, come amministratore, pu\(`o utilizzare
\fBgroupmems\fR
per modificare l\*(Aqelenco di membri di altri gruppi\&.
.SH "OPZIONI"
.PP
Il comando
\fBgroupmems\fR
accetta le seguenti opzioni:
.PP
\fB\-a\fR, \fB\-\-add\fR\ \&\fIuser_name\fR
.RS 4
Aggiunge un utente all\*(Aqelenco di membri del gruppo\&.
.sp
Se esiste il file
/etc/gshadow
e il gruppo non vi \(`e presente, viene aggiunto\&.
.RE
.PP
\fB\-d\fR, \fB\-\-delete\fR\ \&\fIuser_name\fR
.RS 4
Cancella un utente dall\*(Aqelenco degli utenti del gruppo\&.
.sp
Se esiste il file
/etc/gshadow, l\*(Aqutente verr\(`a rimosso dalle liste di utenti e amministratori del gruppo\&.
.sp
Se esiste il file
/etc/gshadow
e il gruppo non vi \(`e presente, viene aggiunto\&.
.RE
.PP
\fB\-g\fR, \fB\-\-group\fR\ \&\fIgroup_name\fR
.RS 4
Il super utente pu\(`o specificare quale elenco di membri del gruppo modificare\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Mostra un messaggio di aiuto ed esce\&.
.RE
.PP
\fB\-l\fR, \fB\-\-list\fR
.RS 4
Elenca tutti i membri del gruppo\&.
.RE
.PP
\fB\-p\fR, \fB\-\-purge\fR
.RS 4
Elimina tutti gli utenti dalla lista dei membri del gruppo\&.
.sp
Se esiste il file
/etc/gshadow
e il gruppo non vi \(`e presente, viene aggiunto\&.
.RE
.PP
\fB\-R\fR, \fB\-\-root\fR\ \&\fICHROOT_DIR\fR
.RS 4
Effettua le modifiche nella directory
\fICHROOT_DIR\fR
e usa i file di configurazione dalla directory
\fICHROOT_DIR\fR\&.
.RE
.SH "CONFIGURAZIONE"
.PP
L\*(Aqeseguibile
\fBgroupmems\fR
dovrebbe avere i permessi
2770
ed essere di propriet\(`a di
\fIroot\fR
e del gruppo
\fIgroups\fR\&. L\*(Aqamministratore di sistema pu\(`o aggiungere utenti al gruppo
\fIgroups\fR
per permettere loro di poter gestire l\*(Aqelenco di membri del proprio gruppo tramite il comando
\fBgroupmems\fR\&.
.sp
.if n \{\
.RS 4
.\}
.nf
        $ groupadd \-r groups
        $ chmod 2770 groupmems
        $ chown root\&.groups groupmems
        $ groupmems \-g groups \-a gk4
    
.fi
.if n \{\
.RE
.\}
.SH "CONFIGURAZIONE"
.PP
Le seguenti variabili di configurazione in
/etc/login\&.defs
cambiano il comportamento di questo strumento:
.PP
\fBMAX_MEMBERS_PER_GROUP\fR (numero)
.RS 4
Numero massimo di membri per gruppo\&. Quando viene raggiunto il massimo, viene creata una nuova riga per il gruppo nel file
/etc/group
(con lo stesso nome, stessa password e stesso GID)\&.
.sp
Il valore predefinito \(`e 0, che non pone nessun limite al numero di membri per gruppo\&.
.sp
Questa opzione (dividi gruppo) permette di limitare la lunghezza delle righe nel file \(Fogroup\(Fc\&. Questo \(`e utile per essere certi che le righe per gruppi NIS non eccedano i 1024 caratteri\&.
.sp
Se si deve impostare questo limite, si pu\(`o usare 25\&.
.sp
Nota: la divisione dei gruppi potrebbe non essere supportata da ogni strumento (anche all\*(Aqinterno del pacchetto Shadow)\&. Non si dovrebbe utilizzare questa variabile a meno di esserci forzati\&.
.RE
.SH "FILE"
.PP
/etc/group
.RS 4
Informazioni sugli account di gruppo\&.
.RE
.PP
/etc/gshadow
.RS 4
informazioni sicure sugli account di gruppo
.RE
.SH "VEDERE ANCHE"
.PP
\fBchfn\fR(1),
\fBchsh\fR(1),
\fBpasswd\fR(1),
\fBgroupadd\fR(8),
\fBgroupdel\fR(8),
\fBuseradd\fR(8),
\fBuserdel\fR(8),
\fBusermod\fR(8)\&.
